// Path: routes/ApisAppsV1WatchNamespaces{namespace}Replicasets{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAppsV1NamespacedReplicaSet } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/watch/namespaces/:namespace/replicasets/:name', watchAppsV1NamespacedReplicaSet)

export default router;
