// Path: routes/ApisCoordination.k8s.ioV1alpha2Namespaces{namespace}LeasecandidatesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoordinationV1alpha2CollectionNamespacedLeaseCandidate } from '../controllers/CoordinationV1alpha2Controller'
import { listCoordinationV1alpha2NamespacedLeaseCandidate } from '../controllers/CoordinationV1alpha2Controller'
import { createCoordinationV1alpha2NamespacedLeaseCandidate } from '../controllers/CoordinationV1alpha2Controller'

import {router} from './router';

router.delete('/apis/coordination.k8s.io/v1alpha2/namespaces/:namespace/leasecandidates', deleteCoordinationV1alpha2CollectionNamespacedLeaseCandidate)

router.get('/apis/coordination.k8s.io/v1alpha2/namespaces/:namespace/leasecandidates', listCoordinationV1alpha2NamespacedLeaseCandidate)

router.post('/apis/coordination.k8s.io/v1alpha2/namespaces/:namespace/leasecandidates', createCoordinationV1alpha2NamespacedLeaseCandidate)

export default router;
