// Path: routes/ApisCoordination.k8s.ioV1WatchNamespaces{namespace}LeasesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoordinationV1NamespacedLeaseList } from '../controllers/CoordinationV1Controller'

import {router} from './router';

router.get('/apis/coordination.k8s.io/v1/watch/namespaces/:namespace/leases', watchCoordinationV1NamespacedLeaseList)

export default router;
