// Path: routes/ApisScheduling.k8s.ioV1PriorityclassesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteSchedulingV1CollectionPriorityClass } from '../controllers/SchedulingV1Controller'
import { listSchedulingV1PriorityClass } from '../controllers/SchedulingV1Controller'
import { createSchedulingV1PriorityClass } from '../controllers/SchedulingV1Controller'

import {router} from './router';

router.delete('/apis/scheduling.k8s.io/v1/priorityclasses', deleteSchedulingV1CollectionPriorityClass)

router.get('/apis/scheduling.k8s.io/v1/priorityclasses', listSchedulingV1PriorityClass)

router.post('/apis/scheduling.k8s.io/v1/priorityclasses', createSchedulingV1PriorityClass)

export default router;
