// Path: routes/ApisAutoscalingV1WatchNamespaces{namespace}Horizontalpodautoscalers{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAutoscalingV1NamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV1Controller'

import {router} from './router';

router.get('/apis/autoscaling/v1/watch/namespaces/:namespace/horizontalpodautoscalers/:name', watchAutoscalingV1NamespacedHorizontalPodAutoscaler)

export default router;
