// Path: routes/ApisRbac.authorization.k8s.ioV1WatchRolebindingsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchRbacAuthorizationV1RoleBindingListForAllNamespaces } from '../controllers/RbacAuthorizationV1Controller'

import {router} from './router';

router.get('/apis/rbac.authorization.k8s.io/v1/watch/rolebindings', watchRbacAuthorizationV1RoleBindingListForAllNamespaces)

export default router;
