// Path: routes/ApisApiregistration.k8s.ioV1WatchApiservicesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchApiregistrationV1APIServiceList } from '../controllers/ApiregistrationV1Controller'

import {router} from './router';

router.get('/apis/apiregistration.k8s.io/v1/watch/apiservices', watchApiregistrationV1APIServiceList)

export default router;
