// Path: routes/ApisResource.k8s.ioV1beta1Namespaces{namespace}Resourceclaims{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteResourceV1beta1NamespacedResourceClaim } from '../controllers/ResourceV1beta1Controller'
import { readResourceV1beta1NamespacedResourceClaim } from '../controllers/ResourceV1beta1Controller'
import { patchResourceV1beta1NamespacedResourceClaim } from '../controllers/ResourceV1beta1Controller'
import { replaceResourceV1beta1NamespacedResourceClaim } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.delete('/apis/resource.k8s.io/v1beta1/namespaces/:namespace/resourceclaims/:name', deleteResourceV1beta1NamespacedResourceClaim)

router.get('/apis/resource.k8s.io/v1beta1/namespaces/:namespace/resourceclaims/:name', readResourceV1beta1NamespacedResourceClaim)

router.patch('/apis/resource.k8s.io/v1beta1/namespaces/:namespace/resourceclaims/:name', patchResourceV1beta1NamespacedResourceClaim)

router.put('/apis/resource.k8s.io/v1beta1/namespaces/:namespace/resourceclaims/:name', replaceResourceV1beta1NamespacedResourceClaim)

export default router;
