// Path: routes/ApisAppsV1Namespaces{namespace}ControllerrevisionsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAppsV1CollectionNamespacedControllerRevision } from '../controllers/AppsV1Controller'
import { listAppsV1NamespacedControllerRevision } from '../controllers/AppsV1Controller'
import { createAppsV1NamespacedControllerRevision } from '../controllers/AppsV1Controller'

import {router} from './router';

router.delete('/apis/apps/v1/namespaces/:namespace/controllerrevisions', deleteAppsV1CollectionNamespacedControllerRevision)

router.get('/apis/apps/v1/namespaces/:namespace/controllerrevisions', listAppsV1NamespacedControllerRevision)

router.post('/apis/apps/v1/namespaces/:namespace/controllerrevisions', createAppsV1NamespacedControllerRevision)

export default router;
