// Path: routes/ApisAppsV1WatchReplicasetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAppsV1ReplicaSetListForAllNamespaces } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/watch/replicasets', watchAppsV1ReplicaSetListForAllNamespaces)

export default router;
