// Path: routes/ApisResource.k8s.ioV1beta1Deviceclasses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteResourceV1beta1DeviceClass } from '../controllers/ResourceV1beta1Controller'
import { readResourceV1beta1DeviceClass } from '../controllers/ResourceV1beta1Controller'
import { patchResourceV1beta1DeviceClass } from '../controllers/ResourceV1beta1Controller'
import { replaceResourceV1beta1DeviceClass } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.delete('/apis/resource.k8s.io/v1beta1/deviceclasses/:name', deleteResourceV1beta1DeviceClass)

router.get('/apis/resource.k8s.io/v1beta1/deviceclasses/:name', readResourceV1beta1DeviceClass)

router.patch('/apis/resource.k8s.io/v1beta1/deviceclasses/:name', patchResourceV1beta1DeviceClass)

router.put('/apis/resource.k8s.io/v1beta1/deviceclasses/:name', replaceResourceV1beta1DeviceClass)

export default router;
