// Path: routes/ApisStorage.k8s.ioV1CsistoragecapacitiesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listStorageV1CSIStorageCapacityForAllNamespaces } from '../controllers/StorageV1Controller'

import {router} from './router';

router.get('/apis/storage.k8s.io/v1/csistoragecapacities', listStorageV1CSIStorageCapacityForAllNamespaces)

export default router;
