// Path: routes/ApisAppsV1DeploymentsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listAppsV1DeploymentForAllNamespaces } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/deployments', listAppsV1DeploymentForAllNamespaces)

export default router;
