// Path: routes/ApisAppsV1ReplicasetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listAppsV1ReplicaSetForAllNamespaces } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/replicasets', listAppsV1ReplicaSetForAllNamespaces)

export default router;
