// Path: routes/ApisStorage.k8s.ioV1alpha1Volumeattributesclasses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteStorageV1alpha1VolumeAttributesClass } from '../controllers/StorageV1alpha1Controller'
import { readStorageV1alpha1VolumeAttributesClass } from '../controllers/StorageV1alpha1Controller'
import { patchStorageV1alpha1VolumeAttributesClass } from '../controllers/StorageV1alpha1Controller'
import { replaceStorageV1alpha1VolumeAttributesClass } from '../controllers/StorageV1alpha1Controller'

import {router} from './router';

router.delete('/apis/storage.k8s.io/v1alpha1/volumeattributesclasses/:name', deleteStorageV1alpha1VolumeAttributesClass)

router.get('/apis/storage.k8s.io/v1alpha1/volumeattributesclasses/:name', readStorageV1alpha1VolumeAttributesClass)

router.patch('/apis/storage.k8s.io/v1alpha1/volumeattributesclasses/:name', patchStorageV1alpha1VolumeAttributesClass)

router.put('/apis/storage.k8s.io/v1alpha1/volumeattributesclasses/:name', replaceStorageV1alpha1VolumeAttributesClass)

export default router;
