// Path: routes/ApisCertificates.k8s.ioV1CertificatesigningrequestsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCertificatesV1CollectionCertificateSigningRequest } from '../controllers/CertificatesV1Controller'
import { listCertificatesV1CertificateSigningRequest } from '../controllers/CertificatesV1Controller'
import { createCertificatesV1CertificateSigningRequest } from '../controllers/CertificatesV1Controller'

import {router} from './router';

router.delete('/apis/certificates.k8s.io/v1/certificatesigningrequests', deleteCertificatesV1CollectionCertificateSigningRequest)

router.get('/apis/certificates.k8s.io/v1/certificatesigningrequests', listCertificatesV1CertificateSigningRequest)

router.post('/apis/certificates.k8s.io/v1/certificatesigningrequests', createCertificatesV1CertificateSigningRequest)

export default router;
