// Path: routes/ApisFlowcontrol.apiserver.k8s.ioV1WatchFlowschemasRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchFlowcontrolApiserverV1FlowSchemaList } from '../controllers/FlowcontrolApiserverV1Controller'

import {router} from './router';

router.get('/apis/flowcontrol.apiserver.k8s.io/v1/watch/flowschemas', watchFlowcontrolApiserverV1FlowSchemaList)

export default router;
