// Path: routes/ApisAppsV1Namespaces{namespace}ReplicasetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAppsV1CollectionNamespacedReplicaSet } from '../controllers/AppsV1Controller'
import { listAppsV1NamespacedReplicaSet } from '../controllers/AppsV1Controller'
import { createAppsV1NamespacedReplicaSet } from '../controllers/AppsV1Controller'

import {router} from './router';

router.delete('/apis/apps/v1/namespaces/:namespace/replicasets', deleteAppsV1CollectionNamespacedReplicaSet)

router.get('/apis/apps/v1/namespaces/:namespace/replicasets', listAppsV1NamespacedReplicaSet)

router.post('/apis/apps/v1/namespaces/:namespace/replicasets', createAppsV1NamespacedReplicaSet)

export default router;
