// Path: routes/ApisAppsV1WatchDaemonsetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAppsV1DaemonSetListForAllNamespaces } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/watch/daemonsets', watchAppsV1DaemonSetListForAllNamespaces)

export default router;
