// Path: routes/ApisNetworking.k8s.ioV1WatchIpaddresses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchNetworkingV1IPAddress } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1/watch/ipaddresses/:name', watchNetworkingV1IPAddress)

export default router;
