// Path: routes/ApisStorage.k8s.ioV1beta1WatchVolumeattributesclassesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchStorageV1beta1VolumeAttributesClassList } from '../controllers/StorageV1beta1Controller'

import {router} from './router';

router.get('/apis/storage.k8s.io/v1beta1/watch/volumeattributesclasses', watchStorageV1beta1VolumeAttributesClassList)

export default router;
