// Path: routes/ApisRbac.authorization.k8s.ioV1Namespaces{namespace}RolebindingsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteRbacAuthorizationV1CollectionNamespacedRoleBinding } from '../controllers/RbacAuthorizationV1Controller'
import { listRbacAuthorizationV1NamespacedRoleBinding } from '../controllers/RbacAuthorizationV1Controller'
import { createRbacAuthorizationV1NamespacedRoleBinding } from '../controllers/RbacAuthorizationV1Controller'

import {router} from './router';

router.delete('/apis/rbac.authorization.k8s.io/v1/namespaces/:namespace/rolebindings', deleteRbacAuthorizationV1CollectionNamespacedRoleBinding)

router.get('/apis/rbac.authorization.k8s.io/v1/namespaces/:namespace/rolebindings', listRbacAuthorizationV1NamespacedRoleBinding)

router.post('/apis/rbac.authorization.k8s.io/v1/namespaces/:namespace/rolebindings', createRbacAuthorizationV1NamespacedRoleBinding)

export default router;
