// Path: routes/ApisStorage.k8s.ioV1WatchNamespaces{namespace}CsistoragecapacitiesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchStorageV1NamespacedCSIStorageCapacityList } from '../controllers/StorageV1Controller'

import {router} from './router';

router.get('/apis/storage.k8s.io/v1/watch/namespaces/:namespace/csistoragecapacities', watchStorageV1NamespacedCSIStorageCapacityList)

export default router;
