// Path: routes/ApisCertificates.k8s.ioV1WatchCertificatesigningrequestsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCertificatesV1CertificateSigningRequestList } from '../controllers/CertificatesV1Controller'

import {router} from './router';

router.get('/apis/certificates.k8s.io/v1/watch/certificatesigningrequests', watchCertificatesV1CertificateSigningRequestList)

export default router;
