// Path: routes/ApisResource.k8s.ioV1beta1WatchResourceclaimtemplatesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchResourceV1beta1ResourceClaimTemplateListForAllNamespaces } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.get('/apis/resource.k8s.io/v1beta1/watch/resourceclaimtemplates', watchResourceV1beta1ResourceClaimTemplateListForAllNamespaces)

export default router;
