// Path: routes/ApisAutoscalingV2Namespaces{namespace}Horizontalpodautoscalers{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAutoscalingV2NamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV2Controller'
import { readAutoscalingV2NamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV2Controller'
import { patchAutoscalingV2NamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV2Controller'
import { replaceAutoscalingV2NamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV2Controller'

import {router} from './router';

router.delete('/apis/autoscaling/v2/namespaces/:namespace/horizontalpodautoscalers/:name', deleteAutoscalingV2NamespacedHorizontalPodAutoscaler)

router.get('/apis/autoscaling/v2/namespaces/:namespace/horizontalpodautoscalers/:name', readAutoscalingV2NamespacedHorizontalPodAutoscaler)

router.patch('/apis/autoscaling/v2/namespaces/:namespace/horizontalpodautoscalers/:name', patchAutoscalingV2NamespacedHorizontalPodAutoscaler)

router.put('/apis/autoscaling/v2/namespaces/:namespace/horizontalpodautoscalers/:name', replaceAutoscalingV2NamespacedHorizontalPodAutoscaler)

export default router;
