// Path: routes/ApisNetworking.k8s.ioV1WatchNamespaces{namespace}Networkpolicies{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchNetworkingV1NamespacedNetworkPolicy } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1/watch/namespaces/:namespace/networkpolicies/:name', watchNetworkingV1NamespacedNetworkPolicy)

export default router;
