// Path: routes/ApisDiscovery.k8s.ioV1WatchEndpointslicesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchDiscoveryV1EndpointSliceListForAllNamespaces } from '../controllers/DiscoveryV1Controller'

import {router} from './router';

router.get('/apis/discovery.k8s.io/v1/watch/endpointslices', watchDiscoveryV1EndpointSliceListForAllNamespaces)

export default router;
