// Path: routes/ApisCoordination.k8s.ioV1alpha2Namespaces{namespace}Leasecandidates{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoordinationV1alpha2NamespacedLeaseCandidate } from '../controllers/CoordinationV1alpha2Controller'
import { readCoordinationV1alpha2NamespacedLeaseCandidate } from '../controllers/CoordinationV1alpha2Controller'
import { patchCoordinationV1alpha2NamespacedLeaseCandidate } from '../controllers/CoordinationV1alpha2Controller'
import { replaceCoordinationV1alpha2NamespacedLeaseCandidate } from '../controllers/CoordinationV1alpha2Controller'

import {router} from './router';

router.delete('/apis/coordination.k8s.io/v1alpha2/namespaces/:namespace/leasecandidates/:name', deleteCoordinationV1alpha2NamespacedLeaseCandidate)

router.get('/apis/coordination.k8s.io/v1alpha2/namespaces/:namespace/leasecandidates/:name', readCoordinationV1alpha2NamespacedLeaseCandidate)

router.patch('/apis/coordination.k8s.io/v1alpha2/namespaces/:namespace/leasecandidates/:name', patchCoordinationV1alpha2NamespacedLeaseCandidate)

router.put('/apis/coordination.k8s.io/v1alpha2/namespaces/:namespace/leasecandidates/:name', replaceCoordinationV1alpha2NamespacedLeaseCandidate)

export default router;
