// Path: routes/ApisApiextensions.k8s.ioV1Customresourcedefinitions{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readApiextensionsV1CustomResourceDefinitionStatus } from '../controllers/ApiextensionsV1Controller'
import { patchApiextensionsV1CustomResourceDefinitionStatus } from '../controllers/ApiextensionsV1Controller'
import { replaceApiextensionsV1CustomResourceDefinitionStatus } from '../controllers/ApiextensionsV1Controller'

import {router} from './router';

router.get('/apis/apiextensions.k8s.io/v1/customresourcedefinitions/:name/status', readApiextensionsV1CustomResourceDefinitionStatus)

router.patch('/apis/apiextensions.k8s.io/v1/customresourcedefinitions/:name/status', patchApiextensionsV1CustomResourceDefinitionStatus)

router.put('/apis/apiextensions.k8s.io/v1/customresourcedefinitions/:name/status', replaceApiextensionsV1CustomResourceDefinitionStatus)

export default router;
