// Path: routes/ApisCoordination.k8s.ioV1Namespaces{namespace}Leases{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoordinationV1NamespacedLease } from '../controllers/CoordinationV1Controller'
import { readCoordinationV1NamespacedLease } from '../controllers/CoordinationV1Controller'
import { patchCoordinationV1NamespacedLease } from '../controllers/CoordinationV1Controller'
import { replaceCoordinationV1NamespacedLease } from '../controllers/CoordinationV1Controller'

import {router} from './router';

router.delete('/apis/coordination.k8s.io/v1/namespaces/:namespace/leases/:name', deleteCoordinationV1NamespacedLease)

router.get('/apis/coordination.k8s.io/v1/namespaces/:namespace/leases/:name', readCoordinationV1NamespacedLease)

router.patch('/apis/coordination.k8s.io/v1/namespaces/:namespace/leases/:name', patchCoordinationV1NamespacedLease)

router.put('/apis/coordination.k8s.io/v1/namespaces/:namespace/leases/:name', replaceCoordinationV1NamespacedLease)

export default router;
