// Path: routes/ApisNode.k8s.ioV1WatchRuntimeclasses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchNodeV1RuntimeClass } from '../controllers/NodeV1Controller'

import {router} from './router';

router.get('/apis/node.k8s.io/v1/watch/runtimeclasses/:name', watchNodeV1RuntimeClass)

export default router;
