// Path: routes/ApisNetworking.k8s.ioV1WatchNamespaces{namespace}IngressesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchNetworkingV1NamespacedIngressList } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1/watch/namespaces/:namespace/ingresses', watchNetworkingV1NamespacedIngressList)

export default router;
