// Path: routes/ApisNetworking.k8s.ioV1beta1WatchServicecidrs{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchNetworkingV1beta1ServiceCIDR } from '../controllers/NetworkingV1beta1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1beta1/watch/servicecidrs/:name', watchNetworkingV1beta1ServiceCIDR)

export default router;
