// Path: routes/ApisResource.k8s.ioV1beta1WatchResourceclaimsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchResourceV1beta1ResourceClaimListForAllNamespaces } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.get('/apis/resource.k8s.io/v1beta1/watch/resourceclaims', watchResourceV1beta1ResourceClaimListForAllNamespaces)

export default router;
