// Path: routes/ApisNetworking.k8s.ioV1Namespaces{namespace}IngressesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNetworkingV1CollectionNamespacedIngress } from '../controllers/NetworkingV1Controller'
import { listNetworkingV1NamespacedIngress } from '../controllers/NetworkingV1Controller'
import { createNetworkingV1NamespacedIngress } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.delete('/apis/networking.k8s.io/v1/namespaces/:namespace/ingresses', deleteNetworkingV1CollectionNamespacedIngress)

router.get('/apis/networking.k8s.io/v1/namespaces/:namespace/ingresses', listNetworkingV1NamespacedIngress)

router.post('/apis/networking.k8s.io/v1/namespaces/:namespace/ingresses', createNetworkingV1NamespacedIngress)

export default router;
