// Path: routes/ApisNode.k8s.ioV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getNodeV1APIResources } from '../controllers/NodeV1Controller'

import {router} from './router';

router.get('/apis/node.k8s.io/v1/', getNodeV1APIResources)

export default router;
