// Path: routes/ApisAuthorization.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getAuthorizationAPIGroup } from '../controllers/AuthorizationController'

import {router} from './router';

router.get('/apis/authorization.k8s.io/', getAuthorizationAPIGroup)

export default router;
