// Path: routes/ApisPolicyV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getPolicyV1APIResources } from '../controllers/PolicyV1Controller'

import {router} from './router';

router.get('/apis/policy/v1/', getPolicyV1APIResources)

export default router;
