// Path: routes/ApisDiscovery.k8s.ioV1WatchNamespaces{namespace}Endpointslices{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchDiscoveryV1NamespacedEndpointSlice } from '../controllers/DiscoveryV1Controller'

import {router} from './router';

router.get('/apis/discovery.k8s.io/v1/watch/namespaces/:namespace/endpointslices/:name', watchDiscoveryV1NamespacedEndpointSlice)

export default router;
