// Path: routes/ApisBatchV1WatchNamespaces{namespace}Jobs{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchBatchV1NamespacedJob } from '../controllers/BatchV1Controller'

import {router} from './router';

router.get('/apis/batch/v1/watch/namespaces/:namespace/jobs/:name', watchBatchV1NamespacedJob)

export default router;
