// Path: routes/ApisBatchV1WatchNamespaces{namespace}Cronjobs{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchBatchV1NamespacedCronJob } from '../controllers/BatchV1Controller'

import {router} from './router';

router.get('/apis/batch/v1/watch/namespaces/:namespace/cronjobs/:name', watchBatchV1NamespacedCronJob)

export default router;
