// Path: routes/ApisResource.k8s.ioV1alpha3Namespaces{namespace}ResourceclaimsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteResourceV1alpha3CollectionNamespacedResourceClaim } from '../controllers/ResourceV1alpha3Controller'
import { listResourceV1alpha3NamespacedResourceClaim } from '../controllers/ResourceV1alpha3Controller'
import { createResourceV1alpha3NamespacedResourceClaim } from '../controllers/ResourceV1alpha3Controller'

import {router} from './router';

router.delete('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaims', deleteResourceV1alpha3CollectionNamespacedResourceClaim)

router.get('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaims', listResourceV1alpha3NamespacedResourceClaim)

router.post('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaims', createResourceV1alpha3NamespacedResourceClaim)

export default router;
