// Path: routes/ApisBatchV1JobsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listBatchV1JobForAllNamespaces } from '../controllers/BatchV1Controller'

import {router} from './router';

router.get('/apis/batch/v1/jobs', listBatchV1JobForAllNamespaces)

export default router;
