// Path: routes/ApisAppsV1WatchNamespaces{namespace}Controllerrevisions{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAppsV1NamespacedControllerRevision } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/watch/namespaces/:namespace/controllerrevisions/:name', watchAppsV1NamespacedControllerRevision)

export default router;
