// Path: routes/ApisRbac.authorization.k8s.ioV1WatchClusterrolesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchRbacAuthorizationV1ClusterRoleList } from '../controllers/RbacAuthorizationV1Controller'

import {router} from './router';

router.get('/apis/rbac.authorization.k8s.io/v1/watch/clusterroles', watchRbacAuthorizationV1ClusterRoleList)

export default router;
