// Path: routes/ApisStoragemigration.k8s.ioV1alpha1WatchStorageversionmigrationsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchStoragemigrationV1alpha1StorageVersionMigrationList } from '../controllers/StoragemigrationV1alpha1Controller'

import {router} from './router';

router.get('/apis/storagemigration.k8s.io/v1alpha1/watch/storageversionmigrations', watchStoragemigrationV1alpha1StorageVersionMigrationList)

export default router;
