// Path: routes/ApisNetworking.k8s.ioV1beta1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getNetworkingV1beta1APIResources } from '../controllers/NetworkingV1beta1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1beta1/', getNetworkingV1beta1APIResources)

export default router;
