// Path: routes/ApisAdmissionregistration.k8s.ioV1beta1Validatingadmissionpolicies{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readAdmissionregistrationV1beta1ValidatingAdmissionPolicyStatus } from '../controllers/AdmissionregistrationV1beta1Controller'
import { patchAdmissionregistrationV1beta1ValidatingAdmissionPolicyStatus } from '../controllers/AdmissionregistrationV1beta1Controller'
import { replaceAdmissionregistrationV1beta1ValidatingAdmissionPolicyStatus } from '../controllers/AdmissionregistrationV1beta1Controller'

import {router} from './router';

router.get('/apis/admissionregistration.k8s.io/v1beta1/validatingadmissionpolicies/:name/status', readAdmissionregistrationV1beta1ValidatingAdmissionPolicyStatus)

router.patch('/apis/admissionregistration.k8s.io/v1beta1/validatingadmissionpolicies/:name/status', patchAdmissionregistrationV1beta1ValidatingAdmissionPolicyStatus)

router.put('/apis/admissionregistration.k8s.io/v1beta1/validatingadmissionpolicies/:name/status', replaceAdmissionregistrationV1beta1ValidatingAdmissionPolicyStatus)

export default router;
