// Path: routes/ApisStorage.k8s.ioV1WatchCsistoragecapacitiesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchStorageV1CSIStorageCapacityListForAllNamespaces } from '../controllers/StorageV1Controller'

import {router} from './router';

router.get('/apis/storage.k8s.io/v1/watch/csistoragecapacities', watchStorageV1CSIStorageCapacityListForAllNamespaces)

export default router;
