// Path: routes/ApisNetworking.k8s.ioV1WatchIngressesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchNetworkingV1IngressListForAllNamespaces } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1/watch/ingresses', watchNetworkingV1IngressListForAllNamespaces)

export default router;
