// Path: routes/ApisCertificates.k8s.ioV1alpha1ClustertrustbundlesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCertificatesV1alpha1CollectionClusterTrustBundle } from '../controllers/CertificatesV1alpha1Controller'
import { listCertificatesV1alpha1ClusterTrustBundle } from '../controllers/CertificatesV1alpha1Controller'
import { createCertificatesV1alpha1ClusterTrustBundle } from '../controllers/CertificatesV1alpha1Controller'

import {router} from './router';

router.delete('/apis/certificates.k8s.io/v1alpha1/clustertrustbundles', deleteCertificatesV1alpha1CollectionClusterTrustBundle)

router.get('/apis/certificates.k8s.io/v1alpha1/clustertrustbundles', listCertificatesV1alpha1ClusterTrustBundle)

router.post('/apis/certificates.k8s.io/v1alpha1/clustertrustbundles', createCertificatesV1alpha1ClusterTrustBundle)

export default router;
