// Path: routes/ApisStorage.k8s.ioV1alpha1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getStorageV1alpha1APIResources } from '../controllers/StorageV1alpha1Controller'

import {router} from './router';

router.get('/apis/storage.k8s.io/v1alpha1/', getStorageV1alpha1APIResources)

export default router;
