// Path: routes/ApisNode.k8s.ioV1WatchRuntimeclassesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchNodeV1RuntimeClassList } from '../controllers/NodeV1Controller'

import {router} from './router';

router.get('/apis/node.k8s.io/v1/watch/runtimeclasses', watchNodeV1RuntimeClassList)

export default router;
