// Path: routes/ApisAppsV1Namespaces{namespace}Controllerrevisions{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAppsV1NamespacedControllerRevision } from '../controllers/AppsV1Controller'
import { readAppsV1NamespacedControllerRevision } from '../controllers/AppsV1Controller'
import { patchAppsV1NamespacedControllerRevision } from '../controllers/AppsV1Controller'
import { replaceAppsV1NamespacedControllerRevision } from '../controllers/AppsV1Controller'

import {router} from './router';

router.delete('/apis/apps/v1/namespaces/:namespace/controllerrevisions/:name', deleteAppsV1NamespacedControllerRevision)

router.get('/apis/apps/v1/namespaces/:namespace/controllerrevisions/:name', readAppsV1NamespacedControllerRevision)

router.patch('/apis/apps/v1/namespaces/:namespace/controllerrevisions/:name', patchAppsV1NamespacedControllerRevision)

router.put('/apis/apps/v1/namespaces/:namespace/controllerrevisions/:name', replaceAppsV1NamespacedControllerRevision)

export default router;
