// Path: routes/ApisNetworking.k8s.ioV1IngressesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listNetworkingV1IngressForAllNamespaces } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1/ingresses', listNetworkingV1IngressForAllNamespaces)

export default router;
