// Path: routes/ApisAdmissionregistration.k8s.ioV1MutatingwebhookconfigurationsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAdmissionregistrationV1CollectionMutatingWebhookConfiguration } from '../controllers/AdmissionregistrationV1Controller'
import { listAdmissionregistrationV1MutatingWebhookConfiguration } from '../controllers/AdmissionregistrationV1Controller'
import { createAdmissionregistrationV1MutatingWebhookConfiguration } from '../controllers/AdmissionregistrationV1Controller'

import {router} from './router';

router.delete('/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations', deleteAdmissionregistrationV1CollectionMutatingWebhookConfiguration)

router.get('/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations', listAdmissionregistrationV1MutatingWebhookConfiguration)

router.post('/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations', createAdmissionregistrationV1MutatingWebhookConfiguration)

export default router;
