// Path: routes/ApisResource.k8s.ioV1beta1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getResourceV1beta1APIResources } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.get('/apis/resource.k8s.io/v1beta1/', getResourceV1beta1APIResources)

export default router;
