// Path: routes/ApisResource.k8s.ioV1alpha3Namespaces{namespace}Resourceclaims{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteResourceV1alpha3NamespacedResourceClaim } from '../controllers/ResourceV1alpha3Controller'
import { readResourceV1alpha3NamespacedResourceClaim } from '../controllers/ResourceV1alpha3Controller'
import { patchResourceV1alpha3NamespacedResourceClaim } from '../controllers/ResourceV1alpha3Controller'
import { replaceResourceV1alpha3NamespacedResourceClaim } from '../controllers/ResourceV1alpha3Controller'

import {router} from './router';

router.delete('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaims/:name', deleteResourceV1alpha3NamespacedResourceClaim)

router.get('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaims/:name', readResourceV1alpha3NamespacedResourceClaim)

router.patch('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaims/:name', patchResourceV1alpha3NamespacedResourceClaim)

router.put('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaims/:name', replaceResourceV1alpha3NamespacedResourceClaim)

export default router;
