// Path: routes/ApisStorage.k8s.ioV1CsidriversRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteStorageV1CollectionCSIDriver } from '../controllers/StorageV1Controller'
import { listStorageV1CSIDriver } from '../controllers/StorageV1Controller'
import { createStorageV1CSIDriver } from '../controllers/StorageV1Controller'

import {router} from './router';

router.delete('/apis/storage.k8s.io/v1/csidrivers', deleteStorageV1CollectionCSIDriver)

router.get('/apis/storage.k8s.io/v1/csidrivers', listStorageV1CSIDriver)

router.post('/apis/storage.k8s.io/v1/csidrivers', createStorageV1CSIDriver)

export default router;
