// Path: routes/ApisRbac.authorization.k8s.ioV1WatchNamespaces{namespace}Roles{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchRbacAuthorizationV1NamespacedRole } from '../controllers/RbacAuthorizationV1Controller'

import {router} from './router';

router.get('/apis/rbac.authorization.k8s.io/v1/watch/namespaces/:namespace/roles/:name', watchRbacAuthorizationV1NamespacedRole)

export default router;
