// Path: routes/ApisAdmissionregistration.k8s.ioV1ValidatingwebhookconfigurationsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAdmissionregistrationV1CollectionValidatingWebhookConfiguration } from '../controllers/AdmissionregistrationV1Controller'
import { listAdmissionregistrationV1ValidatingWebhookConfiguration } from '../controllers/AdmissionregistrationV1Controller'
import { createAdmissionregistrationV1ValidatingWebhookConfiguration } from '../controllers/AdmissionregistrationV1Controller'

import {router} from './router';

router.delete('/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations', deleteAdmissionregistrationV1CollectionValidatingWebhookConfiguration)

router.get('/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations', listAdmissionregistrationV1ValidatingWebhookConfiguration)

router.post('/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations', createAdmissionregistrationV1ValidatingWebhookConfiguration)

export default router;
