// Path: routes/ApisAutoscalingV2WatchHorizontalpodautoscalersRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAutoscalingV2HorizontalPodAutoscalerListForAllNamespaces } from '../controllers/AutoscalingV2Controller'

import {router} from './router';

router.get('/apis/autoscaling/v2/watch/horizontalpodautoscalers', watchAutoscalingV2HorizontalPodAutoscalerListForAllNamespaces)

export default router;
