// Path: routes/ApisAppsV1Namespaces{namespace}DeploymentsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAppsV1CollectionNamespacedDeployment } from '../controllers/AppsV1Controller'
import { listAppsV1NamespacedDeployment } from '../controllers/AppsV1Controller'
import { createAppsV1NamespacedDeployment } from '../controllers/AppsV1Controller'

import {router} from './router';

router.delete('/apis/apps/v1/namespaces/:namespace/deployments', deleteAppsV1CollectionNamespacedDeployment)

router.get('/apis/apps/v1/namespaces/:namespace/deployments', listAppsV1NamespacedDeployment)

router.post('/apis/apps/v1/namespaces/:namespace/deployments', createAppsV1NamespacedDeployment)

export default router;
