// Path: routes/ApisAppsV1WatchDeploymentsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAppsV1DeploymentListForAllNamespaces } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/watch/deployments', watchAppsV1DeploymentListForAllNamespaces)

export default router;
