// Path: routes/ApisApiextensions.k8s.ioV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getApiextensionsV1APIResources } from '../controllers/ApiextensionsV1Controller'

import {router} from './router';

router.get('/apis/apiextensions.k8s.io/v1/', getApiextensionsV1APIResources)

export default router;
