// Path: routes/ApisInternal.apiserver.k8s.ioV1alpha1Storageversions{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteInternalApiserverV1alpha1StorageVersion } from '../controllers/InternalApiserverV1alpha1Controller'
import { readInternalApiserverV1alpha1StorageVersion } from '../controllers/InternalApiserverV1alpha1Controller'
import { patchInternalApiserverV1alpha1StorageVersion } from '../controllers/InternalApiserverV1alpha1Controller'
import { replaceInternalApiserverV1alpha1StorageVersion } from '../controllers/InternalApiserverV1alpha1Controller'

import {router} from './router';

router.delete('/apis/internal.apiserver.k8s.io/v1alpha1/storageversions/:name', deleteInternalApiserverV1alpha1StorageVersion)

router.get('/apis/internal.apiserver.k8s.io/v1alpha1/storageversions/:name', readInternalApiserverV1alpha1StorageVersion)

router.patch('/apis/internal.apiserver.k8s.io/v1alpha1/storageversions/:name', patchInternalApiserverV1alpha1StorageVersion)

router.put('/apis/internal.apiserver.k8s.io/v1alpha1/storageversions/:name', replaceInternalApiserverV1alpha1StorageVersion)

export default router;
