// Path: routes/ApisStorage.k8s.ioV1WatchCsinodesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchStorageV1CSINodeList } from '../controllers/StorageV1Controller'

import {router} from './router';

router.get('/apis/storage.k8s.io/v1/watch/csinodes', watchStorageV1CSINodeList)

export default router;
