// Path: routes/ApisPolicyRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getPolicyAPIGroup } from '../controllers/PolicyController'

import {router} from './router';

router.get('/apis/policy/', getPolicyAPIGroup)

export default router;
