// Path: routes/ApisAdmissionregistration.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getAdmissionregistrationAPIGroup } from '../controllers/AdmissionregistrationController'

import { router } from './router';

router.get('/apis/admissionregistration.k8s.io/', getAdmissionregistrationAPIGroup)

export default router;
