// Path: routes/ApisAutoscalingV2Namespaces{namespace}Horizontalpodautoscalers{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readAutoscalingV2NamespacedHorizontalPodAutoscalerStatus } from '../controllers/AutoscalingV2Controller'
import { patchAutoscalingV2NamespacedHorizontalPodAutoscalerStatus } from '../controllers/AutoscalingV2Controller'
import { replaceAutoscalingV2NamespacedHorizontalPodAutoscalerStatus } from '../controllers/AutoscalingV2Controller'

import {router} from './router';

router.get('/apis/autoscaling/v2/namespaces/:namespace/horizontalpodautoscalers/:name/status', readAutoscalingV2NamespacedHorizontalPodAutoscalerStatus)

router.patch('/apis/autoscaling/v2/namespaces/:namespace/horizontalpodautoscalers/:name/status', patchAutoscalingV2NamespacedHorizontalPodAutoscalerStatus)

router.put('/apis/autoscaling/v2/namespaces/:namespace/horizontalpodautoscalers/:name/status', replaceAutoscalingV2NamespacedHorizontalPodAutoscalerStatus)

export default router;
