// Path: routes/ApisCoordination.k8s.ioV1alpha2WatchLeasecandidatesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoordinationV1alpha2LeaseCandidateListForAllNamespaces } from '../controllers/CoordinationV1alpha2Controller'

import {router} from './router';

router.get('/apis/coordination.k8s.io/v1alpha2/watch/leasecandidates', watchCoordinationV1alpha2LeaseCandidateListForAllNamespaces)

export default router;
