// Path: routes/ApisDiscovery.k8s.ioV1Namespaces{namespace}EndpointslicesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteDiscoveryV1CollectionNamespacedEndpointSlice } from '../controllers/DiscoveryV1Controller'
import { listDiscoveryV1NamespacedEndpointSlice } from '../controllers/DiscoveryV1Controller'
import { createDiscoveryV1NamespacedEndpointSlice } from '../controllers/DiscoveryV1Controller'

import {router} from './router';

router.delete('/apis/discovery.k8s.io/v1/namespaces/:namespace/endpointslices', deleteDiscoveryV1CollectionNamespacedEndpointSlice)

router.get('/apis/discovery.k8s.io/v1/namespaces/:namespace/endpointslices', listDiscoveryV1NamespacedEndpointSlice)

router.post('/apis/discovery.k8s.io/v1/namespaces/:namespace/endpointslices', createDiscoveryV1NamespacedEndpointSlice)

export default router;
