// Path: routes/ApisPolicyV1PoddisruptionbudgetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listPolicyV1PodDisruptionBudgetForAllNamespaces } from '../controllers/PolicyV1Controller'

import {router} from './router';

router.get('/apis/policy/v1/poddisruptionbudgets', listPolicyV1PodDisruptionBudgetForAllNamespaces)

export default router;
