// Path: routes/ApisResource.k8s.ioV1beta1WatchDeviceclasses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchResourceV1beta1DeviceClass } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.get('/apis/resource.k8s.io/v1beta1/watch/deviceclasses/:name', watchResourceV1beta1DeviceClass)

export default router;
