// Path: routes/ApisAutoscalingRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getAutoscalingAPIGroup } from '../controllers/AutoscalingController'

import {router} from './router';

router.get('/apis/autoscaling/', getAutoscalingAPIGroup)

export default router;
