// Path: routes/ApisCoordination.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getCoordinationAPIGroup } from '../controllers/CoordinationController'

import {router} from './router';

router.get('/apis/coordination.k8s.io/', getCoordinationAPIGroup)

export default router;
