// Path: routes/ApisAppsV1WatchStatefulsetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAppsV1StatefulSetListForAllNamespaces } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/watch/statefulsets', watchAppsV1StatefulSetListForAllNamespaces)

export default router;
