// Path: routes/ApisResource.k8s.ioV1alpha3ResourceslicesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteResourceV1alpha3CollectionResourceSlice } from '../controllers/ResourceV1alpha3Controller'
import { listResourceV1alpha3ResourceSlice } from '../controllers/ResourceV1alpha3Controller'
import { createResourceV1alpha3ResourceSlice } from '../controllers/ResourceV1alpha3Controller'

import {router} from './router';

router.delete('/apis/resource.k8s.io/v1alpha3/resourceslices', deleteResourceV1alpha3CollectionResourceSlice)

router.get('/apis/resource.k8s.io/v1alpha3/resourceslices', listResourceV1alpha3ResourceSlice)

router.post('/apis/resource.k8s.io/v1alpha3/resourceslices', createResourceV1alpha3ResourceSlice)

export default router;
