// Path: routes/ApisFlowcontrol.apiserver.k8s.ioV1Flowschemas{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readFlowcontrolApiserverV1FlowSchemaStatus } from '../controllers/FlowcontrolApiserverV1Controller'
import { patchFlowcontrolApiserverV1FlowSchemaStatus } from '../controllers/FlowcontrolApiserverV1Controller'
import { replaceFlowcontrolApiserverV1FlowSchemaStatus } from '../controllers/FlowcontrolApiserverV1Controller'

import {router} from './router';

router.get('/apis/flowcontrol.apiserver.k8s.io/v1/flowschemas/:name/status', readFlowcontrolApiserverV1FlowSchemaStatus)

router.patch('/apis/flowcontrol.apiserver.k8s.io/v1/flowschemas/:name/status', patchFlowcontrolApiserverV1FlowSchemaStatus)

router.put('/apis/flowcontrol.apiserver.k8s.io/v1/flowschemas/:name/status', replaceFlowcontrolApiserverV1FlowSchemaStatus)

export default router;
