// Path: routes/ApisAutoscalingV2WatchNamespaces{namespace}HorizontalpodautoscalersRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAutoscalingV2NamespacedHorizontalPodAutoscalerList } from '../controllers/AutoscalingV2Controller'

import {router} from './router';

router.get('/apis/autoscaling/v2/watch/namespaces/:namespace/horizontalpodautoscalers', watchAutoscalingV2NamespacedHorizontalPodAutoscalerList)

export default router;
