// Path: routes/ApisAuthentication.k8s.ioV1TokenreviewsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { createAuthenticationV1TokenReview } from '../controllers/AuthenticationV1Controller'

import {router} from './router';

router.post('/apis/authentication.k8s.io/v1/tokenreviews', createAuthenticationV1TokenReview)

export default router;
