// Path: routes/ApisScheduling.k8s.ioV1Priorityclasses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteSchedulingV1PriorityClass } from '../controllers/SchedulingV1Controller'
import { readSchedulingV1PriorityClass } from '../controllers/SchedulingV1Controller'
import { patchSchedulingV1PriorityClass } from '../controllers/SchedulingV1Controller'
import { replaceSchedulingV1PriorityClass } from '../controllers/SchedulingV1Controller'

import {router} from './router';

router.delete('/apis/scheduling.k8s.io/v1/priorityclasses/:name', deleteSchedulingV1PriorityClass)

router.get('/apis/scheduling.k8s.io/v1/priorityclasses/:name', readSchedulingV1PriorityClass)

router.patch('/apis/scheduling.k8s.io/v1/priorityclasses/:name', patchSchedulingV1PriorityClass)

router.put('/apis/scheduling.k8s.io/v1/priorityclasses/:name', replaceSchedulingV1PriorityClass)

export default router;
