// Path: routes/ApisFlowcontrol.apiserver.k8s.ioV1Prioritylevelconfigurations{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readFlowcontrolApiserverV1PriorityLevelConfigurationStatus } from '../controllers/FlowcontrolApiserverV1Controller'
import { patchFlowcontrolApiserverV1PriorityLevelConfigurationStatus } from '../controllers/FlowcontrolApiserverV1Controller'
import { replaceFlowcontrolApiserverV1PriorityLevelConfigurationStatus } from '../controllers/FlowcontrolApiserverV1Controller'

import {router} from './router';

router.get('/apis/flowcontrol.apiserver.k8s.io/v1/prioritylevelconfigurations/:name/status', readFlowcontrolApiserverV1PriorityLevelConfigurationStatus)

router.patch('/apis/flowcontrol.apiserver.k8s.io/v1/prioritylevelconfigurations/:name/status', patchFlowcontrolApiserverV1PriorityLevelConfigurationStatus)

router.put('/apis/flowcontrol.apiserver.k8s.io/v1/prioritylevelconfigurations/:name/status', replaceFlowcontrolApiserverV1PriorityLevelConfigurationStatus)

export default router;
