// Path: routes/ApisEvents.k8s.ioV1EventsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listEventsV1EventForAllNamespaces } from '../controllers/EventsV1Controller'

import {router} from './router';

router.get('/apis/events.k8s.io/v1/events', listEventsV1EventForAllNamespaces)

export default router;
