// Path: routes/ApisAutoscalingV1Namespaces{namespace}HorizontalpodautoscalersRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAutoscalingV1CollectionNamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV1Controller'
import { listAutoscalingV1NamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV1Controller'
import { createAutoscalingV1NamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV1Controller'

import {router} from './router';

router.delete('/apis/autoscaling/v1/namespaces/:namespace/horizontalpodautoscalers', deleteAutoscalingV1CollectionNamespacedHorizontalPodAutoscaler)

router.get('/apis/autoscaling/v1/namespaces/:namespace/horizontalpodautoscalers', listAutoscalingV1NamespacedHorizontalPodAutoscaler)

router.post('/apis/autoscaling/v1/namespaces/:namespace/horizontalpodautoscalers', createAutoscalingV1NamespacedHorizontalPodAutoscaler)

export default router;
