// Path: routes/ApisAdmissionregistration.k8s.ioV1alpha1Mutatingadmissionpolicies{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAdmissionregistrationV1alpha1MutatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1alpha1Controller'
import { readAdmissionregistrationV1alpha1MutatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1alpha1Controller'
import { patchAdmissionregistrationV1alpha1MutatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1alpha1Controller'
import { replaceAdmissionregistrationV1alpha1MutatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1alpha1Controller'

import {router} from './router';

router.delete('/apis/admissionregistration.k8s.io/v1alpha1/mutatingadmissionpolicies/:name', deleteAdmissionregistrationV1alpha1MutatingAdmissionPolicy)

router.get('/apis/admissionregistration.k8s.io/v1alpha1/mutatingadmissionpolicies/:name', readAdmissionregistrationV1alpha1MutatingAdmissionPolicy)

router.patch('/apis/admissionregistration.k8s.io/v1alpha1/mutatingadmissionpolicies/:name', patchAdmissionregistrationV1alpha1MutatingAdmissionPolicy)

router.put('/apis/admissionregistration.k8s.io/v1alpha1/mutatingadmissionpolicies/:name', replaceAdmissionregistrationV1alpha1MutatingAdmissionPolicy)

export default router;
