// Path: routes/ApisNetworking.k8s.ioV1WatchServicecidrs{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchNetworkingV1ServiceCIDR } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1/watch/servicecidrs/:name', watchNetworkingV1ServiceCIDR)

export default router;
