// Path: routes/ApisBatchV1WatchCronjobsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchBatchV1CronJobListForAllNamespaces } from '../controllers/BatchV1Controller'

import {router} from './router';

router.get('/apis/batch/v1/watch/cronjobs', watchBatchV1CronJobListForAllNamespaces)

export default router;
