// Path: routes/ApisApiregistration.k8s.ioV1WatchApiservices{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchApiregistrationV1APIService } from '../controllers/ApiregistrationV1Controller'

import {router} from './router';

router.get('/apis/apiregistration.k8s.io/v1/watch/apiservices/:name', watchApiregistrationV1APIService)

export default router;
