// Path: routes/ApisStorage.k8s.ioV1alpha1VolumeattributesclassesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteStorageV1alpha1CollectionVolumeAttributesClass } from '../controllers/StorageV1alpha1Controller'
import { listStorageV1alpha1VolumeAttributesClass } from '../controllers/StorageV1alpha1Controller'
import { createStorageV1alpha1VolumeAttributesClass } from '../controllers/StorageV1alpha1Controller'

import {router} from './router';

router.delete('/apis/storage.k8s.io/v1alpha1/volumeattributesclasses', deleteStorageV1alpha1CollectionVolumeAttributesClass)

router.get('/apis/storage.k8s.io/v1alpha1/volumeattributesclasses', listStorageV1alpha1VolumeAttributesClass)

router.post('/apis/storage.k8s.io/v1alpha1/volumeattributesclasses', createStorageV1alpha1VolumeAttributesClass)

export default router;
