// Path: routes/ApisRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getAPIVersions } from '../controllers/ApisController'

import {router} from './router';

router.get('/apis/', getAPIVersions)

export default router;
