// Path: routes/ApisAppsV1WatchNamespaces{namespace}StatefulsetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAppsV1NamespacedStatefulSetList } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/watch/namespaces/:namespace/statefulsets', watchAppsV1NamespacedStatefulSetList)

export default router;
