// Path: routes/ApisAutoscalingV1HorizontalpodautoscalersRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listAutoscalingV1HorizontalPodAutoscalerForAllNamespaces } from '../controllers/AutoscalingV1Controller'

import {router} from './router';

router.get('/apis/autoscaling/v1/horizontalpodautoscalers', listAutoscalingV1HorizontalPodAutoscalerForAllNamespaces)

export default router;
