// Path: routes/ApisAdmissionregistration.k8s.ioV1beta1Validatingadmissionpolicies{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAdmissionregistrationV1beta1ValidatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1beta1Controller'
import { readAdmissionregistrationV1beta1ValidatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1beta1Controller'
import { patchAdmissionregistrationV1beta1ValidatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1beta1Controller'
import { replaceAdmissionregistrationV1beta1ValidatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1beta1Controller'

import {router} from './router';

router.delete('/apis/admissionregistration.k8s.io/v1beta1/validatingadmissionpolicies/:name', deleteAdmissionregistrationV1beta1ValidatingAdmissionPolicy)

router.get('/apis/admissionregistration.k8s.io/v1beta1/validatingadmissionpolicies/:name', readAdmissionregistrationV1beta1ValidatingAdmissionPolicy)

router.patch('/apis/admissionregistration.k8s.io/v1beta1/validatingadmissionpolicies/:name', patchAdmissionregistrationV1beta1ValidatingAdmissionPolicy)

router.put('/apis/admissionregistration.k8s.io/v1beta1/validatingadmissionpolicies/:name', replaceAdmissionregistrationV1beta1ValidatingAdmissionPolicy)

export default router;
