// Path: routes/ApisFlowcontrol.apiserver.k8s.ioV1WatchFlowschemas{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchFlowcontrolApiserverV1FlowSchema } from '../controllers/FlowcontrolApiserverV1Controller'

import {router} from './router';

router.get('/apis/flowcontrol.apiserver.k8s.io/v1/watch/flowschemas/:name', watchFlowcontrolApiserverV1FlowSchema)

export default router;
