// Path: routes/ApisAdmissionregistration.k8s.ioV1Validatingadmissionpolicies{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAdmissionregistrationV1ValidatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1Controller'
import { readAdmissionregistrationV1ValidatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1Controller'
import { patchAdmissionregistrationV1ValidatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1Controller'
import { replaceAdmissionregistrationV1ValidatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1Controller'

import {router} from './router';

router.delete('/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies/:name', deleteAdmissionregistrationV1ValidatingAdmissionPolicy)

router.get('/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies/:name', readAdmissionregistrationV1ValidatingAdmissionPolicy)

router.patch('/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies/:name', patchAdmissionregistrationV1ValidatingAdmissionPolicy)

router.put('/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies/:name', replaceAdmissionregistrationV1ValidatingAdmissionPolicy)

export default router;
