// Path: routes/ApisCoordination.k8s.ioV1alpha2Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getCoordinationV1alpha2APIResources } from '../controllers/CoordinationV1alpha2Controller'

import {router} from './router';

router.get('/apis/coordination.k8s.io/v1alpha2/', getCoordinationV1alpha2APIResources)

export default router;
