// Path: routes/ApisAppsV1Namespaces{namespace}Replicasets{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readAppsV1NamespacedReplicaSetStatus } from '../controllers/AppsV1Controller'
import { patchAppsV1NamespacedReplicaSetStatus } from '../controllers/AppsV1Controller'
import { replaceAppsV1NamespacedReplicaSetStatus } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/namespaces/:namespace/replicasets/:name/status', readAppsV1NamespacedReplicaSetStatus)

router.patch('/apis/apps/v1/namespaces/:namespace/replicasets/:name/status', patchAppsV1NamespacedReplicaSetStatus)

router.put('/apis/apps/v1/namespaces/:namespace/replicasets/:name/status', replaceAppsV1NamespacedReplicaSetStatus)

export default router;
