// Path: routes/ApisAdmissionregistration.k8s.ioV1Mutatingwebhookconfigurations{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAdmissionregistrationV1MutatingWebhookConfiguration } from '../controllers/AdmissionregistrationV1Controller'
import { readAdmissionregistrationV1MutatingWebhookConfiguration } from '../controllers/AdmissionregistrationV1Controller'
import { patchAdmissionregistrationV1MutatingWebhookConfiguration } from '../controllers/AdmissionregistrationV1Controller'
import { replaceAdmissionregistrationV1MutatingWebhookConfiguration } from '../controllers/AdmissionregistrationV1Controller'

import {router} from './router';

router.delete('/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/:name', deleteAdmissionregistrationV1MutatingWebhookConfiguration)

router.get('/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/:name', readAdmissionregistrationV1MutatingWebhookConfiguration)

router.patch('/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/:name', patchAdmissionregistrationV1MutatingWebhookConfiguration)

router.put('/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/:name', replaceAdmissionregistrationV1MutatingWebhookConfiguration)

export default router;
