// Path: routes/ApisResource.k8s.ioV1beta1ResourceclaimsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listResourceV1beta1ResourceClaimForAllNamespaces } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.get('/apis/resource.k8s.io/v1beta1/resourceclaims', listResourceV1beta1ResourceClaimForAllNamespaces)

export default router;
