// Path: routes/ApisNetworking.k8s.ioV1WatchNetworkpoliciesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchNetworkingV1NetworkPolicyListForAllNamespaces } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1/watch/networkpolicies', watchNetworkingV1NetworkPolicyListForAllNamespaces)

export default router;
