// Path: routes/ApisStorage.k8s.ioV1Csinodes{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteStorageV1CSINode } from '../controllers/StorageV1Controller'
import { readStorageV1CSINode } from '../controllers/StorageV1Controller'
import { patchStorageV1CSINode } from '../controllers/StorageV1Controller'
import { replaceStorageV1CSINode } from '../controllers/StorageV1Controller'

import {router} from './router';

router.delete('/apis/storage.k8s.io/v1/csinodes/:name', deleteStorageV1CSINode)

router.get('/apis/storage.k8s.io/v1/csinodes/:name', readStorageV1CSINode)

router.patch('/apis/storage.k8s.io/v1/csinodes/:name', patchStorageV1CSINode)

router.put('/apis/storage.k8s.io/v1/csinodes/:name', replaceStorageV1CSINode)

export default router;
