// Path: routes/ApisRbac.authorization.k8s.ioV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getRbacAuthorizationV1APIResources } from '../controllers/RbacAuthorizationV1Controller'

import {router} from './router';

router.get('/apis/rbac.authorization.k8s.io/v1/', getRbacAuthorizationV1APIResources)

export default router;
