// Path: routes/ApisStoragemigration.k8s.ioV1alpha1Storageversionmigrations{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteStoragemigrationV1alpha1StorageVersionMigration } from '../controllers/StoragemigrationV1alpha1Controller'
import { readStoragemigrationV1alpha1StorageVersionMigration } from '../controllers/StoragemigrationV1alpha1Controller'
import { patchStoragemigrationV1alpha1StorageVersionMigration } from '../controllers/StoragemigrationV1alpha1Controller'
import { replaceStoragemigrationV1alpha1StorageVersionMigration } from '../controllers/StoragemigrationV1alpha1Controller'

import {router} from './router';

router.delete('/apis/storagemigration.k8s.io/v1alpha1/storageversionmigrations/:name', deleteStoragemigrationV1alpha1StorageVersionMigration)

router.get('/apis/storagemigration.k8s.io/v1alpha1/storageversionmigrations/:name', readStoragemigrationV1alpha1StorageVersionMigration)

router.patch('/apis/storagemigration.k8s.io/v1alpha1/storageversionmigrations/:name', patchStoragemigrationV1alpha1StorageVersionMigration)

router.put('/apis/storagemigration.k8s.io/v1alpha1/storageversionmigrations/:name', replaceStoragemigrationV1alpha1StorageVersionMigration)

export default router;
