// Path: routes/ApisPolicyV1Namespaces{namespace}PoddisruptionbudgetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deletePolicyV1CollectionNamespacedPodDisruptionBudget } from '../controllers/PolicyV1Controller'
import { listPolicyV1NamespacedPodDisruptionBudget } from '../controllers/PolicyV1Controller'
import { createPolicyV1NamespacedPodDisruptionBudget } from '../controllers/PolicyV1Controller'

import {router} from './router';

router.delete('/apis/policy/v1/namespaces/:namespace/poddisruptionbudgets', deletePolicyV1CollectionNamespacedPodDisruptionBudget)

router.get('/apis/policy/v1/namespaces/:namespace/poddisruptionbudgets', listPolicyV1NamespacedPodDisruptionBudget)

router.post('/apis/policy/v1/namespaces/:namespace/poddisruptionbudgets', createPolicyV1NamespacedPodDisruptionBudget)

export default router;
