// Path: routes/ApisCertificates.k8s.ioV1WatchCertificatesigningrequests{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCertificatesV1CertificateSigningRequest } from '../controllers/CertificatesV1Controller'

import {router} from './router';

router.get('/apis/certificates.k8s.io/v1/watch/certificatesigningrequests/:name', watchCertificatesV1CertificateSigningRequest)

export default router;
