// Path: routes/ApisApiregistration.k8s.ioV1ApiservicesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteApiregistrationV1CollectionAPIService } from '../controllers/ApiregistrationV1Controller'
import { listApiregistrationV1APIService } from '../controllers/ApiregistrationV1Controller'
import { createApiregistrationV1APIService } from '../controllers/ApiregistrationV1Controller'

import {router} from './router';

router.delete('/apis/apiregistration.k8s.io/v1/apiservices', deleteApiregistrationV1CollectionAPIService)

router.get('/apis/apiregistration.k8s.io/v1/apiservices', listApiregistrationV1APIService)

router.post('/apis/apiregistration.k8s.io/v1/apiservices', createApiregistrationV1APIService)

export default router;
