// Path: routes/ApisEvents.k8s.ioV1Namespaces{namespace}EventsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteEventsV1CollectionNamespacedEvent } from '../controllers/EventsV1Controller'
import { listEventsV1NamespacedEvent } from '../controllers/EventsV1Controller'
import { createEventsV1NamespacedEvent } from '../controllers/EventsV1Controller'

import {router} from './router';

router.delete('/apis/events.k8s.io/v1/namespaces/:namespace/events', deleteEventsV1CollectionNamespacedEvent)

router.get('/apis/events.k8s.io/v1/namespaces/:namespace/events', listEventsV1NamespacedEvent)

router.post('/apis/events.k8s.io/v1/namespaces/:namespace/events', createEventsV1NamespacedEvent)

export default router;
