// Path: routes/ApisAutoscalingV1WatchNamespaces{namespace}HorizontalpodautoscalersRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAutoscalingV1NamespacedHorizontalPodAutoscalerList } from '../controllers/AutoscalingV1Controller'

import {router} from './router';

router.get('/apis/autoscaling/v1/watch/namespaces/:namespace/horizontalpodautoscalers', watchAutoscalingV1NamespacedHorizontalPodAutoscalerList)

export default router;
