// Path: routes/ApisRbac.authorization.k8s.ioV1WatchClusterrolebindings{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchRbacAuthorizationV1ClusterRoleBinding } from '../controllers/RbacAuthorizationV1Controller'

import {router} from './router';

router.get('/apis/rbac.authorization.k8s.io/v1/watch/clusterrolebindings/:name', watchRbacAuthorizationV1ClusterRoleBinding)

export default router;
