// Path: routes/ApisCertificates.k8s.ioV1alpha1WatchClustertrustbundlesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCertificatesV1alpha1ClusterTrustBundleList } from '../controllers/CertificatesV1alpha1Controller'

import {router} from './router';

router.get('/apis/certificates.k8s.io/v1alpha1/watch/clustertrustbundles', watchCertificatesV1alpha1ClusterTrustBundleList)

export default router;
