// Path: routes/ApisStorage.k8s.ioV1alpha1WatchVolumeattributesclasses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchStorageV1alpha1VolumeAttributesClass } from '../controllers/StorageV1alpha1Controller'

import {router} from './router';

router.get('/apis/storage.k8s.io/v1alpha1/watch/volumeattributesclasses/:name', watchStorageV1alpha1VolumeAttributesClass)

export default router;
