// Path: routes/ApisNetworking.k8s.ioV1Servicecidrs{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNetworkingV1ServiceCIDR } from '../controllers/NetworkingV1Controller'
import { readNetworkingV1ServiceCIDR } from '../controllers/NetworkingV1Controller'
import { patchNetworkingV1ServiceCIDR } from '../controllers/NetworkingV1Controller'
import { replaceNetworkingV1ServiceCIDR } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.delete('/apis/networking.k8s.io/v1/servicecidrs/:name', deleteNetworkingV1ServiceCIDR)

router.get('/apis/networking.k8s.io/v1/servicecidrs/:name', readNetworkingV1ServiceCIDR)

router.patch('/apis/networking.k8s.io/v1/servicecidrs/:name', patchNetworkingV1ServiceCIDR)

router.put('/apis/networking.k8s.io/v1/servicecidrs/:name', replaceNetworkingV1ServiceCIDR)

export default router;
