// Path: routes/ApisNode.k8s.ioV1Runtimeclasses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNodeV1RuntimeClass } from '../controllers/NodeV1Controller'
import { readNodeV1RuntimeClass } from '../controllers/NodeV1Controller'
import { patchNodeV1RuntimeClass } from '../controllers/NodeV1Controller'
import { replaceNodeV1RuntimeClass } from '../controllers/NodeV1Controller'

import {router} from './router';

router.delete('/apis/node.k8s.io/v1/runtimeclasses/:name', deleteNodeV1RuntimeClass)

router.get('/apis/node.k8s.io/v1/runtimeclasses/:name', readNodeV1RuntimeClass)

router.patch('/apis/node.k8s.io/v1/runtimeclasses/:name', patchNodeV1RuntimeClass)

router.put('/apis/node.k8s.io/v1/runtimeclasses/:name', replaceNodeV1RuntimeClass)

export default router;
