// Path: routes/ApisResource.k8s.ioV1alpha3Namespaces{namespace}Resourceclaims{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readResourceV1alpha3NamespacedResourceClaimStatus } from '../controllers/ResourceV1alpha3Controller'
import { patchResourceV1alpha3NamespacedResourceClaimStatus } from '../controllers/ResourceV1alpha3Controller'
import { replaceResourceV1alpha3NamespacedResourceClaimStatus } from '../controllers/ResourceV1alpha3Controller'

import {router} from './router';

router.get('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaims/:name/status', readResourceV1alpha3NamespacedResourceClaimStatus)

router.patch('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaims/:name/status', patchResourceV1alpha3NamespacedResourceClaimStatus)

router.put('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaims/:name/status', replaceResourceV1alpha3NamespacedResourceClaimStatus)

export default router;
