// Path: routes/ApisAdmissionregistration.k8s.ioV1Validatingadmissionpolicybindings{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAdmissionregistrationV1ValidatingAdmissionPolicyBinding } from '../controllers/AdmissionregistrationV1Controller'
import { readAdmissionregistrationV1ValidatingAdmissionPolicyBinding } from '../controllers/AdmissionregistrationV1Controller'
import { patchAdmissionregistrationV1ValidatingAdmissionPolicyBinding } from '../controllers/AdmissionregistrationV1Controller'
import { replaceAdmissionregistrationV1ValidatingAdmissionPolicyBinding } from '../controllers/AdmissionregistrationV1Controller'

import {router} from './router';

router.delete('/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicybindings/:name', deleteAdmissionregistrationV1ValidatingAdmissionPolicyBinding)

router.get('/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicybindings/:name', readAdmissionregistrationV1ValidatingAdmissionPolicyBinding)

router.patch('/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicybindings/:name', patchAdmissionregistrationV1ValidatingAdmissionPolicyBinding)

router.put('/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicybindings/:name', replaceAdmissionregistrationV1ValidatingAdmissionPolicyBinding)

export default router;
