// Path: routes/ApisCoordination.k8s.ioV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getCoordinationV1APIResources } from '../controllers/CoordinationV1Controller'

import {router} from './router';

router.get('/apis/coordination.k8s.io/v1/', getCoordinationV1APIResources)

export default router;
