// Path: routes/ApisInternal.apiserver.k8s.ioV1alpha1WatchStorageversionsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchInternalApiserverV1alpha1StorageVersionList } from '../controllers/InternalApiserverV1alpha1Controller'

import {router} from './router';

router.get('/apis/internal.apiserver.k8s.io/v1alpha1/watch/storageversions', watchInternalApiserverV1alpha1StorageVersionList)

export default router;
