// Path: routes/ApisResource.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getResourceAPIGroup } from '../controllers/ResourceController'

import {router} from './router';

router.get('/apis/resource.k8s.io/', getResourceAPIGroup)

export default router;
