// Path: routes/ApisResource.k8s.ioV1beta1Resourceslices{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteResourceV1beta1ResourceSlice } from '../controllers/ResourceV1beta1Controller'
import { readResourceV1beta1ResourceSlice } from '../controllers/ResourceV1beta1Controller'
import { patchResourceV1beta1ResourceSlice } from '../controllers/ResourceV1beta1Controller'
import { replaceResourceV1beta1ResourceSlice } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.delete('/apis/resource.k8s.io/v1beta1/resourceslices/:name', deleteResourceV1beta1ResourceSlice)

router.get('/apis/resource.k8s.io/v1beta1/resourceslices/:name', readResourceV1beta1ResourceSlice)

router.patch('/apis/resource.k8s.io/v1beta1/resourceslices/:name', patchResourceV1beta1ResourceSlice)

router.put('/apis/resource.k8s.io/v1beta1/resourceslices/:name', replaceResourceV1beta1ResourceSlice)

export default router;
