// Path: routes/ApisApiregistration.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getApiregistrationAPIGroup } from '../controllers/ApiregistrationController'

import {router} from './router';

router.get('/apis/apiregistration.k8s.io/', getApiregistrationAPIGroup)

export default router;
