// Path: routes/ApisAdmissionregistration.k8s.ioV1ValidatingadmissionpoliciesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAdmissionregistrationV1CollectionValidatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1Controller'
import { listAdmissionregistrationV1ValidatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1Controller'
import { createAdmissionregistrationV1ValidatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1Controller'

import {router} from './router';

router.delete('/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies', deleteAdmissionregistrationV1CollectionValidatingAdmissionPolicy)

router.get('/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies', listAdmissionregistrationV1ValidatingAdmissionPolicy)

router.post('/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies', createAdmissionregistrationV1ValidatingAdmissionPolicy)

export default router;
