// Path: routes/ApisAdmissionregistration.k8s.ioV1beta1ValidatingadmissionpolicybindingsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAdmissionregistrationV1beta1CollectionValidatingAdmissionPolicyBinding } from '../controllers/AdmissionregistrationV1beta1Controller'
import { listAdmissionregistrationV1beta1ValidatingAdmissionPolicyBinding } from '../controllers/AdmissionregistrationV1beta1Controller'
import { createAdmissionregistrationV1beta1ValidatingAdmissionPolicyBinding } from '../controllers/AdmissionregistrationV1beta1Controller'

import {router} from './router';

router.delete('/apis/admissionregistration.k8s.io/v1beta1/validatingadmissionpolicybindings', deleteAdmissionregistrationV1beta1CollectionValidatingAdmissionPolicyBinding)

router.get('/apis/admissionregistration.k8s.io/v1beta1/validatingadmissionpolicybindings', listAdmissionregistrationV1beta1ValidatingAdmissionPolicyBinding)

router.post('/apis/admissionregistration.k8s.io/v1beta1/validatingadmissionpolicybindings', createAdmissionregistrationV1beta1ValidatingAdmissionPolicyBinding)

export default router;
