// Path: routes/ApisAppsV1Namespaces{namespace}Replicasets{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAppsV1NamespacedReplicaSet } from '../controllers/AppsV1Controller'
import { readAppsV1NamespacedReplicaSet } from '../controllers/AppsV1Controller'
import { patchAppsV1NamespacedReplicaSet } from '../controllers/AppsV1Controller'
import { replaceAppsV1NamespacedReplicaSet } from '../controllers/AppsV1Controller'

import {router} from './router';

router.delete('/apis/apps/v1/namespaces/:namespace/replicasets/:name', deleteAppsV1NamespacedReplicaSet)

router.get('/apis/apps/v1/namespaces/:namespace/replicasets/:name', readAppsV1NamespacedReplicaSet)

router.patch('/apis/apps/v1/namespaces/:namespace/replicasets/:name', patchAppsV1NamespacedReplicaSet)

router.put('/apis/apps/v1/namespaces/:namespace/replicasets/:name', replaceAppsV1NamespacedReplicaSet)

export default router;
