// Path: routes/ApisAutoscalingV1Namespaces{namespace}Horizontalpodautoscalers{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAutoscalingV1NamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV1Controller'
import { readAutoscalingV1NamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV1Controller'
import { patchAutoscalingV1NamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV1Controller'
import { replaceAutoscalingV1NamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV1Controller'

import {router} from './router';

router.delete('/apis/autoscaling/v1/namespaces/:namespace/horizontalpodautoscalers/:name', deleteAutoscalingV1NamespacedHorizontalPodAutoscaler)

router.get('/apis/autoscaling/v1/namespaces/:namespace/horizontalpodautoscalers/:name', readAutoscalingV1NamespacedHorizontalPodAutoscaler)

router.patch('/apis/autoscaling/v1/namespaces/:namespace/horizontalpodautoscalers/:name', patchAutoscalingV1NamespacedHorizontalPodAutoscaler)

router.put('/apis/autoscaling/v1/namespaces/:namespace/horizontalpodautoscalers/:name', replaceAutoscalingV1NamespacedHorizontalPodAutoscaler)

export default router;
