// Path: routes/ApisAppsV1WatchNamespaces{namespace}Deployments{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAppsV1NamespacedDeployment } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/watch/namespaces/:namespace/deployments/:name', watchAppsV1NamespacedDeployment)

export default router;
