// Path: routes/ApisDiscovery.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getDiscoveryAPIGroup } from '../controllers/DiscoveryController'

import {router} from './router';

router.get('/apis/discovery.k8s.io/', getDiscoveryAPIGroup)

export default router;
