// Path: routes/ApisPolicyV1WatchNamespaces{namespace}PoddisruptionbudgetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchPolicyV1NamespacedPodDisruptionBudgetList } from '../controllers/PolicyV1Controller'

import {router} from './router';

router.get('/apis/policy/v1/watch/namespaces/:namespace/poddisruptionbudgets', watchPolicyV1NamespacedPodDisruptionBudgetList)

export default router;
