// Path: routes/ApisFlowcontrol.apiserver.k8s.ioV1FlowschemasRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteFlowcontrolApiserverV1CollectionFlowSchema } from '../controllers/FlowcontrolApiserverV1Controller'
import { listFlowcontrolApiserverV1FlowSchema } from '../controllers/FlowcontrolApiserverV1Controller'
import { createFlowcontrolApiserverV1FlowSchema } from '../controllers/FlowcontrolApiserverV1Controller'

import {router} from './router';

router.delete('/apis/flowcontrol.apiserver.k8s.io/v1/flowschemas', deleteFlowcontrolApiserverV1CollectionFlowSchema)

router.get('/apis/flowcontrol.apiserver.k8s.io/v1/flowschemas', listFlowcontrolApiserverV1FlowSchema)

router.post('/apis/flowcontrol.apiserver.k8s.io/v1/flowschemas', createFlowcontrolApiserverV1FlowSchema)

export default router;
