// Path: routes/ApisAppsV1Namespaces{namespace}StatefulsetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAppsV1CollectionNamespacedStatefulSet } from '../controllers/AppsV1Controller'
import { listAppsV1NamespacedStatefulSet } from '../controllers/AppsV1Controller'
import { createAppsV1NamespacedStatefulSet } from '../controllers/AppsV1Controller'

import {router} from './router';

router.delete('/apis/apps/v1/namespaces/:namespace/statefulsets', deleteAppsV1CollectionNamespacedStatefulSet)

router.get('/apis/apps/v1/namespaces/:namespace/statefulsets', listAppsV1NamespacedStatefulSet)

router.post('/apis/apps/v1/namespaces/:namespace/statefulsets', createAppsV1NamespacedStatefulSet)

export default router;
