// Path: routes/ApisStorage.k8s.ioV1alpha1WatchVolumeattributesclassesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchStorageV1alpha1VolumeAttributesClassList } from '../controllers/StorageV1alpha1Controller'

import {router} from './router';

router.get('/apis/storage.k8s.io/v1alpha1/watch/volumeattributesclasses', watchStorageV1alpha1VolumeAttributesClassList)

export default router;
