// Path: routes/ApisCoordination.k8s.ioV1WatchNamespaces{namespace}Leases{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoordinationV1NamespacedLease } from '../controllers/CoordinationV1Controller'

import {router} from './router';

router.get('/apis/coordination.k8s.io/v1/watch/namespaces/:namespace/leases/:name', watchCoordinationV1NamespacedLease)

export default router;
