// Path: routes/ApisAppsV1Namespaces{namespace}Statefulsets{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readAppsV1NamespacedStatefulSetStatus } from '../controllers/AppsV1Controller'
import { patchAppsV1NamespacedStatefulSetStatus } from '../controllers/AppsV1Controller'
import { replaceAppsV1NamespacedStatefulSetStatus } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/namespaces/:namespace/statefulsets/:name/status', readAppsV1NamespacedStatefulSetStatus)

router.patch('/apis/apps/v1/namespaces/:namespace/statefulsets/:name/status', patchAppsV1NamespacedStatefulSetStatus)

router.put('/apis/apps/v1/namespaces/:namespace/statefulsets/:name/status', replaceAppsV1NamespacedStatefulSetStatus)

export default router;
