// Path: routes/ApisScheduling.k8s.ioV1WatchPriorityclassesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchSchedulingV1PriorityClassList } from '../controllers/SchedulingV1Controller'

import {router} from './router';

router.get('/apis/scheduling.k8s.io/v1/watch/priorityclasses', watchSchedulingV1PriorityClassList)

export default router;
