// Path: routes/ApisAuthorization.k8s.ioV1Namespaces{namespace}LocalsubjectaccessreviewsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { createAuthorizationV1NamespacedLocalSubjectAccessReview } from '../controllers/AuthorizationV1Controller'

import {router} from './router';

router.post('/apis/authorization.k8s.io/v1/namespaces/:namespace/localsubjectaccessreviews', createAuthorizationV1NamespacedLocalSubjectAccessReview)

export default router;
