// Path: routes/ApisAuthorization.k8s.ioV1SelfsubjectrulesreviewsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { createAuthorizationV1SelfSubjectRulesReview } from '../controllers/AuthorizationV1Controller'

import {router} from './router';

router.post('/apis/authorization.k8s.io/v1/selfsubjectrulesreviews', createAuthorizationV1SelfSubjectRulesReview)

export default router;
