// Path: routes/ApisCertificates.k8s.ioV1Certificatesigningrequests{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCertificatesV1CertificateSigningRequest } from '../controllers/CertificatesV1Controller'
import { readCertificatesV1CertificateSigningRequest } from '../controllers/CertificatesV1Controller'
import { patchCertificatesV1CertificateSigningRequest } from '../controllers/CertificatesV1Controller'
import { replaceCertificatesV1CertificateSigningRequest } from '../controllers/CertificatesV1Controller'

import {router} from './router';

router.delete('/apis/certificates.k8s.io/v1/certificatesigningrequests/:name', deleteCertificatesV1CertificateSigningRequest)

router.get('/apis/certificates.k8s.io/v1/certificatesigningrequests/:name', readCertificatesV1CertificateSigningRequest)

router.patch('/apis/certificates.k8s.io/v1/certificatesigningrequests/:name', patchCertificatesV1CertificateSigningRequest)

router.put('/apis/certificates.k8s.io/v1/certificatesigningrequests/:name', replaceCertificatesV1CertificateSigningRequest)

export default router;
