// Path: routes/ApisRbac.authorization.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getRbacAuthorizationAPIGroup } from '../controllers/RbacAuthorizationController'

import {router} from './router';

router.get('/apis/rbac.authorization.k8s.io/', getRbacAuthorizationAPIGroup)

export default router;
