// Path: routes/ApisNetworking.k8s.ioV1beta1IpaddressesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNetworkingV1beta1CollectionIPAddress } from '../controllers/NetworkingV1beta1Controller'
import { listNetworkingV1beta1IPAddress } from '../controllers/NetworkingV1beta1Controller'
import { createNetworkingV1beta1IPAddress } from '../controllers/NetworkingV1beta1Controller'

import {router} from './router';

router.delete('/apis/networking.k8s.io/v1beta1/ipaddresses', deleteNetworkingV1beta1CollectionIPAddress)

router.get('/apis/networking.k8s.io/v1beta1/ipaddresses', listNetworkingV1beta1IPAddress)

router.post('/apis/networking.k8s.io/v1beta1/ipaddresses', createNetworkingV1beta1IPAddress)

export default router;
