// Path: routes/ApisCertificates.k8s.ioV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getCertificatesV1APIResources } from '../controllers/CertificatesV1Controller'

import {router} from './router';

router.get('/apis/certificates.k8s.io/v1/', getCertificatesV1APIResources)

export default router;
