// Path: routes/ApisInternal.apiserver.k8s.ioV1alpha1StorageversionsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteInternalApiserverV1alpha1CollectionStorageVersion } from '../controllers/InternalApiserverV1alpha1Controller'
import { listInternalApiserverV1alpha1StorageVersion } from '../controllers/InternalApiserverV1alpha1Controller'
import { createInternalApiserverV1alpha1StorageVersion } from '../controllers/InternalApiserverV1alpha1Controller'

import {router} from './router';

router.delete('/apis/internal.apiserver.k8s.io/v1alpha1/storageversions', deleteInternalApiserverV1alpha1CollectionStorageVersion)

router.get('/apis/internal.apiserver.k8s.io/v1alpha1/storageversions', listInternalApiserverV1alpha1StorageVersion)

router.post('/apis/internal.apiserver.k8s.io/v1alpha1/storageversions', createInternalApiserverV1alpha1StorageVersion)

export default router;
