// Path: routes/ApisResource.k8s.ioV1alpha3Namespaces{namespace}Resourceclaimtemplates{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteResourceV1alpha3NamespacedResourceClaimTemplate } from '../controllers/ResourceV1alpha3Controller'
import { readResourceV1alpha3NamespacedResourceClaimTemplate } from '../controllers/ResourceV1alpha3Controller'
import { patchResourceV1alpha3NamespacedResourceClaimTemplate } from '../controllers/ResourceV1alpha3Controller'
import { replaceResourceV1alpha3NamespacedResourceClaimTemplate } from '../controllers/ResourceV1alpha3Controller'

import {router} from './router';

router.delete('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaimtemplates/:name', deleteResourceV1alpha3NamespacedResourceClaimTemplate)

router.get('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaimtemplates/:name', readResourceV1alpha3NamespacedResourceClaimTemplate)

router.patch('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaimtemplates/:name', patchResourceV1alpha3NamespacedResourceClaimTemplate)

router.put('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaimtemplates/:name', replaceResourceV1alpha3NamespacedResourceClaimTemplate)

export default router;
