// Path: routes/ApisPolicyV1WatchPoddisruptionbudgetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchPolicyV1PodDisruptionBudgetListForAllNamespaces } from '../controllers/PolicyV1Controller'

import {router} from './router';

router.get('/apis/policy/v1/watch/poddisruptionbudgets', watchPolicyV1PodDisruptionBudgetListForAllNamespaces)

export default router;
