// Path: routes/ApisStorage.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getStorageAPIGroup } from '../controllers/StorageController'

import {router} from './router';

router.get('/apis/storage.k8s.io/', getStorageAPIGroup)

export default router;
