// Path: routes/ApisApiregistration.k8s.ioV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getApiregistrationV1APIResources } from '../controllers/ApiregistrationV1Controller'

import {router} from './router';

router.get('/apis/apiregistration.k8s.io/v1/', getApiregistrationV1APIResources)

export default router;
