// Path: routes/ApisNetworking.k8s.ioV1Servicecidrs{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readNetworkingV1ServiceCIDRStatus } from '../controllers/NetworkingV1Controller'
import { patchNetworkingV1ServiceCIDRStatus } from '../controllers/NetworkingV1Controller'
import { replaceNetworkingV1ServiceCIDRStatus } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1/servicecidrs/:name/status', readNetworkingV1ServiceCIDRStatus)

router.patch('/apis/networking.k8s.io/v1/servicecidrs/:name/status', patchNetworkingV1ServiceCIDRStatus)

router.put('/apis/networking.k8s.io/v1/servicecidrs/:name/status', replaceNetworkingV1ServiceCIDRStatus)

export default router;
