// Path: routes/ApisResource.k8s.ioV1alpha3WatchResourceclaimsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchResourceV1alpha3ResourceClaimListForAllNamespaces } from '../controllers/ResourceV1alpha3Controller'

import {router} from './router';

router.get('/apis/resource.k8s.io/v1alpha3/watch/resourceclaims', watchResourceV1alpha3ResourceClaimListForAllNamespaces)

export default router;
