// Path: routes/ApisInternal.apiserver.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getInternalApiserverAPIGroup } from '../controllers/InternalApiserverController'

import {router} from './router';

router.get('/apis/internal.apiserver.k8s.io/', getInternalApiserverAPIGroup)

export default router;
