// Path: routes/ApisCoordination.k8s.ioV1alpha2LeasecandidatesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listCoordinationV1alpha2LeaseCandidateForAllNamespaces } from '../controllers/CoordinationV1alpha2Controller'

import {router} from './router';

router.get('/apis/coordination.k8s.io/v1alpha2/leasecandidates', listCoordinationV1alpha2LeaseCandidateForAllNamespaces)

export default router;
