// Path: routes/ApisStoragemigration.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getStoragemigrationAPIGroup } from '../controllers/StoragemigrationController'

import {router} from './router';

router.get('/apis/storagemigration.k8s.io/', getStoragemigrationAPIGroup)

export default router;
