// Path: routes/ApisAppsV1Namespaces{namespace}Statefulsets{name}ScaleRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readAppsV1NamespacedStatefulSetScale } from '../controllers/AppsV1Controller'
import { patchAppsV1NamespacedStatefulSetScale } from '../controllers/AppsV1Controller'
import { replaceAppsV1NamespacedStatefulSetScale } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/namespaces/:namespace/statefulsets/:name/scale', readAppsV1NamespacedStatefulSetScale)

router.patch('/apis/apps/v1/namespaces/:namespace/statefulsets/:name/scale', patchAppsV1NamespacedStatefulSetScale)

router.put('/apis/apps/v1/namespaces/:namespace/statefulsets/:name/scale', replaceAppsV1NamespacedStatefulSetScale)

export default router;
