// Path: routes/ApisAdmissionregistration.k8s.ioV1alpha1MutatingadmissionpoliciesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAdmissionregistrationV1alpha1CollectionMutatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1alpha1Controller'
import { listAdmissionregistrationV1alpha1MutatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1alpha1Controller'
import { createAdmissionregistrationV1alpha1MutatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1alpha1Controller'

import {router} from './router';

router.delete('/apis/admissionregistration.k8s.io/v1alpha1/mutatingadmissionpolicies', deleteAdmissionregistrationV1alpha1CollectionMutatingAdmissionPolicy)

router.get('/apis/admissionregistration.k8s.io/v1alpha1/mutatingadmissionpolicies', listAdmissionregistrationV1alpha1MutatingAdmissionPolicy)

router.post('/apis/admissionregistration.k8s.io/v1alpha1/mutatingadmissionpolicies', createAdmissionregistrationV1alpha1MutatingAdmissionPolicy)

export default router;
