// Path: routes/ApisAuthorization.k8s.ioV1SelfsubjectaccessreviewsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { createAuthorizationV1SelfSubjectAccessReview } from '../controllers/AuthorizationV1Controller'

import {router} from './router';

router.post('/apis/authorization.k8s.io/v1/selfsubjectaccessreviews', createAuthorizationV1SelfSubjectAccessReview)

export default router;
