// Path: routes/ApisAdmissionregistration.k8s.ioV1WatchValidatingadmissionpolicybindings{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAdmissionregistrationV1ValidatingAdmissionPolicyBinding } from '../controllers/AdmissionregistrationV1Controller'

import {router} from './router';

router.get('/apis/admissionregistration.k8s.io/v1/watch/validatingadmissionpolicybindings/:name', watchAdmissionregistrationV1ValidatingAdmissionPolicyBinding)

export default router;
