// Path: routes/ApisStorage.k8s.ioV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getStorageV1APIResources } from '../controllers/StorageV1Controller'

import {router} from './router';

router.get('/apis/storage.k8s.io/v1/', getStorageV1APIResources)

export default router;
