// Path: routes/ApisAppsV1WatchNamespaces{namespace}ReplicasetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAppsV1NamespacedReplicaSetList } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/watch/namespaces/:namespace/replicasets', watchAppsV1NamespacedReplicaSetList)

export default router;
