// Path: routes/ApisResource.k8s.ioV1alpha3Deviceclasses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteResourceV1alpha3DeviceClass } from '../controllers/ResourceV1alpha3Controller'
import { readResourceV1alpha3DeviceClass } from '../controllers/ResourceV1alpha3Controller'
import { patchResourceV1alpha3DeviceClass } from '../controllers/ResourceV1alpha3Controller'
import { replaceResourceV1alpha3DeviceClass } from '../controllers/ResourceV1alpha3Controller'

import {router} from './router';

router.delete('/apis/resource.k8s.io/v1alpha3/deviceclasses/:name', deleteResourceV1alpha3DeviceClass)

router.get('/apis/resource.k8s.io/v1alpha3/deviceclasses/:name', readResourceV1alpha3DeviceClass)

router.patch('/apis/resource.k8s.io/v1alpha3/deviceclasses/:name', patchResourceV1alpha3DeviceClass)

router.put('/apis/resource.k8s.io/v1alpha3/deviceclasses/:name', replaceResourceV1alpha3DeviceClass)

export default router;
