// Path: routes/ApisResource.k8s.ioV1beta1Namespaces{namespace}ResourceclaimtemplatesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteResourceV1beta1CollectionNamespacedResourceClaimTemplate } from '../controllers/ResourceV1beta1Controller'
import { listResourceV1beta1NamespacedResourceClaimTemplate } from '../controllers/ResourceV1beta1Controller'
import { createResourceV1beta1NamespacedResourceClaimTemplate } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.delete('/apis/resource.k8s.io/v1beta1/namespaces/:namespace/resourceclaimtemplates', deleteResourceV1beta1CollectionNamespacedResourceClaimTemplate)

router.get('/apis/resource.k8s.io/v1beta1/namespaces/:namespace/resourceclaimtemplates', listResourceV1beta1NamespacedResourceClaimTemplate)

router.post('/apis/resource.k8s.io/v1beta1/namespaces/:namespace/resourceclaimtemplates', createResourceV1beta1NamespacedResourceClaimTemplate)

export default router;
