// Path: routes/ApisNode.k8s.ioV1RuntimeclassesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNodeV1CollectionRuntimeClass } from '../controllers/NodeV1Controller'
import { listNodeV1RuntimeClass } from '../controllers/NodeV1Controller'
import { createNodeV1RuntimeClass } from '../controllers/NodeV1Controller'

import {router} from './router';

router.delete('/apis/node.k8s.io/v1/runtimeclasses', deleteNodeV1CollectionRuntimeClass)

router.get('/apis/node.k8s.io/v1/runtimeclasses', listNodeV1RuntimeClass)

router.post('/apis/node.k8s.io/v1/runtimeclasses', createNodeV1RuntimeClass)

export default router;
