// Path: routes/ApisAppsV1Namespaces{namespace}Deployments{name}ScaleRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readAppsV1NamespacedDeploymentScale } from '../controllers/AppsV1Controller'
import { patchAppsV1NamespacedDeploymentScale } from '../controllers/AppsV1Controller'
import { replaceAppsV1NamespacedDeploymentScale } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/namespaces/:namespace/deployments/:name/scale', readAppsV1NamespacedDeploymentScale)

router.patch('/apis/apps/v1/namespaces/:namespace/deployments/:name/scale', patchAppsV1NamespacedDeploymentScale)

router.put('/apis/apps/v1/namespaces/:namespace/deployments/:name/scale', replaceAppsV1NamespacedDeploymentScale)

export default router;
