// Path: routes/ApisResource.k8s.ioV1beta1ResourceslicesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteResourceV1beta1CollectionResourceSlice } from '../controllers/ResourceV1beta1Controller'
import { listResourceV1beta1ResourceSlice } from '../controllers/ResourceV1beta1Controller'
import { createResourceV1beta1ResourceSlice } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.delete('/apis/resource.k8s.io/v1beta1/resourceslices', deleteResourceV1beta1CollectionResourceSlice)

router.get('/apis/resource.k8s.io/v1beta1/resourceslices', listResourceV1beta1ResourceSlice)

router.post('/apis/resource.k8s.io/v1beta1/resourceslices', createResourceV1beta1ResourceSlice)

export default router;
