// Path: routes/ApisNetworking.k8s.ioV1IpaddressesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNetworkingV1CollectionIPAddress } from '../controllers/NetworkingV1Controller'
import { listNetworkingV1IPAddress } from '../controllers/NetworkingV1Controller'
import { createNetworkingV1IPAddress } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.delete('/apis/networking.k8s.io/v1/ipaddresses', deleteNetworkingV1CollectionIPAddress)

router.get('/apis/networking.k8s.io/v1/ipaddresses', listNetworkingV1IPAddress)

router.post('/apis/networking.k8s.io/v1/ipaddresses', createNetworkingV1IPAddress)

export default router;
