// Path: routes/ApisBatchV1WatchNamespaces{namespace}JobsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchBatchV1NamespacedJobList } from '../controllers/BatchV1Controller'

import {router} from './router';

router.get('/apis/batch/v1/watch/namespaces/:namespace/jobs', watchBatchV1NamespacedJobList)

export default router;
