// Path: routes/ApisRbac.authorization.k8s.ioV1ClusterrolesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteRbacAuthorizationV1CollectionClusterRole } from '../controllers/RbacAuthorizationV1Controller'
import { listRbacAuthorizationV1ClusterRole } from '../controllers/RbacAuthorizationV1Controller'
import { createRbacAuthorizationV1ClusterRole } from '../controllers/RbacAuthorizationV1Controller'

import {router} from './router';

router.delete('/apis/rbac.authorization.k8s.io/v1/clusterroles', deleteRbacAuthorizationV1CollectionClusterRole)

router.get('/apis/rbac.authorization.k8s.io/v1/clusterroles', listRbacAuthorizationV1ClusterRole)

router.post('/apis/rbac.authorization.k8s.io/v1/clusterroles', createRbacAuthorizationV1ClusterRole)

export default router;
