// Path: routes/ApisInternal.apiserver.k8s.ioV1alpha1WatchStorageversions{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchInternalApiserverV1alpha1StorageVersion } from '../controllers/InternalApiserverV1alpha1Controller'

import {router} from './router';

router.get('/apis/internal.apiserver.k8s.io/v1alpha1/watch/storageversions/:name', watchInternalApiserverV1alpha1StorageVersion)

export default router;
