// Path: routes/ApisStoragemigration.k8s.ioV1alpha1Storageversionmigrations{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readStoragemigrationV1alpha1StorageVersionMigrationStatus } from '../controllers/StoragemigrationV1alpha1Controller'
import { patchStoragemigrationV1alpha1StorageVersionMigrationStatus } from '../controllers/StoragemigrationV1alpha1Controller'
import { replaceStoragemigrationV1alpha1StorageVersionMigrationStatus } from '../controllers/StoragemigrationV1alpha1Controller'

import {router} from './router';

router.get('/apis/storagemigration.k8s.io/v1alpha1/storageversionmigrations/:name/status', readStoragemigrationV1alpha1StorageVersionMigrationStatus)

router.patch('/apis/storagemigration.k8s.io/v1alpha1/storageversionmigrations/:name/status', patchStoragemigrationV1alpha1StorageVersionMigrationStatus)

router.put('/apis/storagemigration.k8s.io/v1alpha1/storageversionmigrations/:name/status', replaceStoragemigrationV1alpha1StorageVersionMigrationStatus)

export default router;
