// Path: routes/ApisCoordination.k8s.ioV1Namespaces{namespace}LeasesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoordinationV1CollectionNamespacedLease } from '../controllers/CoordinationV1Controller'
import { listCoordinationV1NamespacedLease } from '../controllers/CoordinationV1Controller'
import { createCoordinationV1NamespacedLease } from '../controllers/CoordinationV1Controller'

import {router} from './router';

router.delete('/apis/coordination.k8s.io/v1/namespaces/:namespace/leases', deleteCoordinationV1CollectionNamespacedLease)

router.get('/apis/coordination.k8s.io/v1/namespaces/:namespace/leases', listCoordinationV1NamespacedLease)

router.post('/apis/coordination.k8s.io/v1/namespaces/:namespace/leases', createCoordinationV1NamespacedLease)

export default router;
