// Path: routes/ApisStorage.k8s.ioV1Storageclasses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteStorageV1StorageClass } from '../controllers/StorageV1Controller'
import { readStorageV1StorageClass } from '../controllers/StorageV1Controller'
import { patchStorageV1StorageClass } from '../controllers/StorageV1Controller'
import { replaceStorageV1StorageClass } from '../controllers/StorageV1Controller'

import {router} from './router';

router.delete('/apis/storage.k8s.io/v1/storageclasses/:name', deleteStorageV1StorageClass)

router.get('/apis/storage.k8s.io/v1/storageclasses/:name', readStorageV1StorageClass)

router.patch('/apis/storage.k8s.io/v1/storageclasses/:name', patchStorageV1StorageClass)

router.put('/apis/storage.k8s.io/v1/storageclasses/:name', replaceStorageV1StorageClass)

export default router;
