// Path: routes/ApisCoordination.k8s.ioV1alpha2WatchNamespaces{namespace}Leasecandidates{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoordinationV1alpha2NamespacedLeaseCandidate } from '../controllers/CoordinationV1alpha2Controller'

import {router} from './router';

router.get('/apis/coordination.k8s.io/v1alpha2/watch/namespaces/:namespace/leasecandidates/:name', watchCoordinationV1alpha2NamespacedLeaseCandidate)

export default router;
