// Path: routes/ApisInternal.apiserver.k8s.ioV1alpha1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getInternalApiserverV1alpha1APIResources } from '../controllers/InternalApiserverV1alpha1Controller'

import {router} from './router';

router.get('/apis/internal.apiserver.k8s.io/v1alpha1/', getInternalApiserverV1alpha1APIResources)

export default router;
