// Path: routes/ApisAppsV1Namespaces{namespace}Statefulsets{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAppsV1NamespacedStatefulSet } from '../controllers/AppsV1Controller'
import { readAppsV1NamespacedStatefulSet } from '../controllers/AppsV1Controller'
import { patchAppsV1NamespacedStatefulSet } from '../controllers/AppsV1Controller'
import { replaceAppsV1NamespacedStatefulSet } from '../controllers/AppsV1Controller'

import {router} from './router';

router.delete('/apis/apps/v1/namespaces/:namespace/statefulsets/:name', deleteAppsV1NamespacedStatefulSet)

router.get('/apis/apps/v1/namespaces/:namespace/statefulsets/:name', readAppsV1NamespacedStatefulSet)

router.patch('/apis/apps/v1/namespaces/:namespace/statefulsets/:name', patchAppsV1NamespacedStatefulSet)

router.put('/apis/apps/v1/namespaces/:namespace/statefulsets/:name', replaceAppsV1NamespacedStatefulSet)

export default router;
