// Path: routes/ApisBatchV1Namespaces{namespace}CronjobsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteBatchV1CollectionNamespacedCronJob } from '../controllers/BatchV1Controller'
import { listBatchV1NamespacedCronJob } from '../controllers/BatchV1Controller'
import { createBatchV1NamespacedCronJob } from '../controllers/BatchV1Controller'

import {router} from './router';

router.delete('/apis/batch/v1/namespaces/:namespace/cronjobs', deleteBatchV1CollectionNamespacedCronJob)

router.get('/apis/batch/v1/namespaces/:namespace/cronjobs', listBatchV1NamespacedCronJob)

router.post('/apis/batch/v1/namespaces/:namespace/cronjobs', createBatchV1NamespacedCronJob)

export default router;
