// Path: routes/ApisNetworking.k8s.ioV1Namespaces{namespace}NetworkpoliciesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNetworkingV1CollectionNamespacedNetworkPolicy } from '../controllers/NetworkingV1Controller'
import { listNetworkingV1NamespacedNetworkPolicy } from '../controllers/NetworkingV1Controller'
import { createNetworkingV1NamespacedNetworkPolicy } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.delete('/apis/networking.k8s.io/v1/namespaces/:namespace/networkpolicies', deleteNetworkingV1CollectionNamespacedNetworkPolicy)

router.get('/apis/networking.k8s.io/v1/namespaces/:namespace/networkpolicies', listNetworkingV1NamespacedNetworkPolicy)

router.post('/apis/networking.k8s.io/v1/namespaces/:namespace/networkpolicies', createNetworkingV1NamespacedNetworkPolicy)

export default router;
