// Path: routes/ApisFlowcontrol.apiserver.k8s.ioV1Flowschemas{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteFlowcontrolApiserverV1FlowSchema } from '../controllers/FlowcontrolApiserverV1Controller'
import { readFlowcontrolApiserverV1FlowSchema } from '../controllers/FlowcontrolApiserverV1Controller'
import { patchFlowcontrolApiserverV1FlowSchema } from '../controllers/FlowcontrolApiserverV1Controller'
import { replaceFlowcontrolApiserverV1FlowSchema } from '../controllers/FlowcontrolApiserverV1Controller'

import {router} from './router';

router.delete('/apis/flowcontrol.apiserver.k8s.io/v1/flowschemas/:name', deleteFlowcontrolApiserverV1FlowSchema)

router.get('/apis/flowcontrol.apiserver.k8s.io/v1/flowschemas/:name', readFlowcontrolApiserverV1FlowSchema)

router.patch('/apis/flowcontrol.apiserver.k8s.io/v1/flowschemas/:name', patchFlowcontrolApiserverV1FlowSchema)

router.put('/apis/flowcontrol.apiserver.k8s.io/v1/flowschemas/:name', replaceFlowcontrolApiserverV1FlowSchema)

export default router;
