// Path: routes/ApisApiextensions.k8s.ioV1CustomresourcedefinitionsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteApiextensionsV1CollectionCustomResourceDefinition } from '../controllers/ApiextensionsV1Controller'
import { listApiextensionsV1CustomResourceDefinition } from '../controllers/ApiextensionsV1Controller'
import { createApiextensionsV1CustomResourceDefinition } from '../controllers/ApiextensionsV1Controller'

import {router} from './router';

router.delete('/apis/apiextensions.k8s.io/v1/customresourcedefinitions', deleteApiextensionsV1CollectionCustomResourceDefinition)

router.get('/apis/apiextensions.k8s.io/v1/customresourcedefinitions', listApiextensionsV1CustomResourceDefinition)

router.post('/apis/apiextensions.k8s.io/v1/customresourcedefinitions', createApiextensionsV1CustomResourceDefinition)

export default router;
