// Path: routes/ApisAdmissionregistration.k8s.ioV1WatchMutatingwebhookconfigurationsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAdmissionregistrationV1MutatingWebhookConfigurationList } from '../controllers/AdmissionregistrationV1Controller'

import {router} from './router';

router.get('/apis/admissionregistration.k8s.io/v1/watch/mutatingwebhookconfigurations', watchAdmissionregistrationV1MutatingWebhookConfigurationList)

export default router;
