// Path: routes/ApisDiscovery.k8s.ioV1Namespaces{namespace}Endpointslices{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteDiscoveryV1NamespacedEndpointSlice } from '../controllers/DiscoveryV1Controller'
import { readDiscoveryV1NamespacedEndpointSlice } from '../controllers/DiscoveryV1Controller'
import { patchDiscoveryV1NamespacedEndpointSlice } from '../controllers/DiscoveryV1Controller'
import { replaceDiscoveryV1NamespacedEndpointSlice } from '../controllers/DiscoveryV1Controller'

import {router} from './router';

router.delete('/apis/discovery.k8s.io/v1/namespaces/:namespace/endpointslices/:name', deleteDiscoveryV1NamespacedEndpointSlice)

router.get('/apis/discovery.k8s.io/v1/namespaces/:namespace/endpointslices/:name', readDiscoveryV1NamespacedEndpointSlice)

router.patch('/apis/discovery.k8s.io/v1/namespaces/:namespace/endpointslices/:name', patchDiscoveryV1NamespacedEndpointSlice)

router.put('/apis/discovery.k8s.io/v1/namespaces/:namespace/endpointslices/:name', replaceDiscoveryV1NamespacedEndpointSlice)

export default router;
