// Path: routes/ApisFlowcontrol.apiserver.k8s.ioV1Prioritylevelconfigurations{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteFlowcontrolApiserverV1PriorityLevelConfiguration } from '../controllers/FlowcontrolApiserverV1Controller'
import { readFlowcontrolApiserverV1PriorityLevelConfiguration } from '../controllers/FlowcontrolApiserverV1Controller'
import { patchFlowcontrolApiserverV1PriorityLevelConfiguration } from '../controllers/FlowcontrolApiserverV1Controller'
import { replaceFlowcontrolApiserverV1PriorityLevelConfiguration } from '../controllers/FlowcontrolApiserverV1Controller'

import {router} from './router';

router.delete('/apis/flowcontrol.apiserver.k8s.io/v1/prioritylevelconfigurations/:name', deleteFlowcontrolApiserverV1PriorityLevelConfiguration)

router.get('/apis/flowcontrol.apiserver.k8s.io/v1/prioritylevelconfigurations/:name', readFlowcontrolApiserverV1PriorityLevelConfiguration)

router.patch('/apis/flowcontrol.apiserver.k8s.io/v1/prioritylevelconfigurations/:name', patchFlowcontrolApiserverV1PriorityLevelConfiguration)

router.put('/apis/flowcontrol.apiserver.k8s.io/v1/prioritylevelconfigurations/:name', replaceFlowcontrolApiserverV1PriorityLevelConfiguration)

export default router;
