// Path: routes/ApisRbac.authorization.k8s.ioV1Namespaces{namespace}Rolebindings{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteRbacAuthorizationV1NamespacedRoleBinding } from '../controllers/RbacAuthorizationV1Controller'
import { readRbacAuthorizationV1NamespacedRoleBinding } from '../controllers/RbacAuthorizationV1Controller'
import { patchRbacAuthorizationV1NamespacedRoleBinding } from '../controllers/RbacAuthorizationV1Controller'
import { replaceRbacAuthorizationV1NamespacedRoleBinding } from '../controllers/RbacAuthorizationV1Controller'

import {router} from './router';

router.delete('/apis/rbac.authorization.k8s.io/v1/namespaces/:namespace/rolebindings/:name', deleteRbacAuthorizationV1NamespacedRoleBinding)

router.get('/apis/rbac.authorization.k8s.io/v1/namespaces/:namespace/rolebindings/:name', readRbacAuthorizationV1NamespacedRoleBinding)

router.patch('/apis/rbac.authorization.k8s.io/v1/namespaces/:namespace/rolebindings/:name', patchRbacAuthorizationV1NamespacedRoleBinding)

router.put('/apis/rbac.authorization.k8s.io/v1/namespaces/:namespace/rolebindings/:name', replaceRbacAuthorizationV1NamespacedRoleBinding)

export default router;
