// Path: routes/ApisScheduling.k8s.ioV1WatchPriorityclasses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchSchedulingV1PriorityClass } from '../controllers/SchedulingV1Controller'

import {router} from './router';

router.get('/apis/scheduling.k8s.io/v1/watch/priorityclasses/:name', watchSchedulingV1PriorityClass)

export default router;
