// Path: routes/ApisBatchRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getBatchAPIGroup } from '../controllers/BatchController'

import {router} from './router';

router.get('/apis/batch/', getBatchAPIGroup)

export default router;
