// Path: routes/ApisBatchV1Namespaces{namespace}Jobs{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readBatchV1NamespacedJobStatus } from '../controllers/BatchV1Controller'
import { patchBatchV1NamespacedJobStatus } from '../controllers/BatchV1Controller'
import { replaceBatchV1NamespacedJobStatus } from '../controllers/BatchV1Controller'

import {router} from './router';

router.get('/apis/batch/v1/namespaces/:namespace/jobs/:name/status', readBatchV1NamespacedJobStatus)

router.patch('/apis/batch/v1/namespaces/:namespace/jobs/:name/status', patchBatchV1NamespacedJobStatus)

router.put('/apis/batch/v1/namespaces/:namespace/jobs/:name/status', replaceBatchV1NamespacedJobStatus)

export default router;
