// Path: routes/ApisEvents.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getEventsAPIGroup } from '../controllers/EventsController'

import {router} from './router';

router.get('/apis/events.k8s.io/', getEventsAPIGroup)

export default router;
