// Path: routes/ApisResource.k8s.ioV1beta1Namespaces{namespace}Resourceclaims{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readResourceV1beta1NamespacedResourceClaimStatus } from '../controllers/ResourceV1beta1Controller'
import { patchResourceV1beta1NamespacedResourceClaimStatus } from '../controllers/ResourceV1beta1Controller'
import { replaceResourceV1beta1NamespacedResourceClaimStatus } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.get('/apis/resource.k8s.io/v1beta1/namespaces/:namespace/resourceclaims/:name/status', readResourceV1beta1NamespacedResourceClaimStatus)

router.patch('/apis/resource.k8s.io/v1beta1/namespaces/:namespace/resourceclaims/:name/status', patchResourceV1beta1NamespacedResourceClaimStatus)

router.put('/apis/resource.k8s.io/v1beta1/namespaces/:namespace/resourceclaims/:name/status', replaceResourceV1beta1NamespacedResourceClaimStatus)

export default router;
