// Path: routes/ApisStorage.k8s.ioV1StorageclassesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteStorageV1CollectionStorageClass } from '../controllers/StorageV1Controller'
import { listStorageV1StorageClass } from '../controllers/StorageV1Controller'
import { createStorageV1StorageClass } from '../controllers/StorageV1Controller'

import {router} from './router';

router.delete('/apis/storage.k8s.io/v1/storageclasses', deleteStorageV1CollectionStorageClass)

router.get('/apis/storage.k8s.io/v1/storageclasses', listStorageV1StorageClass)

router.post('/apis/storage.k8s.io/v1/storageclasses', createStorageV1StorageClass)

export default router;
