// Path: routes/ApisAppsV1Namespaces{namespace}Deployments{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAppsV1NamespacedDeployment } from '../controllers/AppsV1Controller'
import { readAppsV1NamespacedDeployment } from '../controllers/AppsV1Controller'
import { patchAppsV1NamespacedDeployment } from '../controllers/AppsV1Controller'
import { replaceAppsV1NamespacedDeployment } from '../controllers/AppsV1Controller'

import {router} from './router';

router.delete('/apis/apps/v1/namespaces/:namespace/deployments/:name', deleteAppsV1NamespacedDeployment)

router.get('/apis/apps/v1/namespaces/:namespace/deployments/:name', readAppsV1NamespacedDeployment)

router.patch('/apis/apps/v1/namespaces/:namespace/deployments/:name', patchAppsV1NamespacedDeployment)

router.put('/apis/apps/v1/namespaces/:namespace/deployments/:name', replaceAppsV1NamespacedDeployment)

export default router;
