// Path: routes/ApisBatchV1Namespaces{namespace}Cronjobs{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readBatchV1NamespacedCronJobStatus } from '../controllers/BatchV1Controller'
import { patchBatchV1NamespacedCronJobStatus } from '../controllers/BatchV1Controller'
import { replaceBatchV1NamespacedCronJobStatus } from '../controllers/BatchV1Controller'

import {router} from './router';

router.get('/apis/batch/v1/namespaces/:namespace/cronjobs/:name/status', readBatchV1NamespacedCronJobStatus)

router.patch('/apis/batch/v1/namespaces/:namespace/cronjobs/:name/status', patchBatchV1NamespacedCronJobStatus)

router.put('/apis/batch/v1/namespaces/:namespace/cronjobs/:name/status', replaceBatchV1NamespacedCronJobStatus)

export default router;
