// Path: routes/ApisNetworking.k8s.ioV1NetworkpoliciesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listNetworkingV1NetworkPolicyForAllNamespaces } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1/networkpolicies', listNetworkingV1NetworkPolicyForAllNamespaces)

export default router;
