// Path: routes/ApisNetworking.k8s.ioV1Ipaddresses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNetworkingV1IPAddress } from '../controllers/NetworkingV1Controller'
import { readNetworkingV1IPAddress } from '../controllers/NetworkingV1Controller'
import { patchNetworkingV1IPAddress } from '../controllers/NetworkingV1Controller'
import { replaceNetworkingV1IPAddress } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.delete('/apis/networking.k8s.io/v1/ipaddresses/:name', deleteNetworkingV1IPAddress)

router.get('/apis/networking.k8s.io/v1/ipaddresses/:name', readNetworkingV1IPAddress)

router.patch('/apis/networking.k8s.io/v1/ipaddresses/:name', patchNetworkingV1IPAddress)

router.put('/apis/networking.k8s.io/v1/ipaddresses/:name', replaceNetworkingV1IPAddress)

export default router;
