// Path: routes/ApisNetworking.k8s.ioV1ServicecidrsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNetworkingV1CollectionServiceCIDR } from '../controllers/NetworkingV1Controller'
import { listNetworkingV1ServiceCIDR } from '../controllers/NetworkingV1Controller'
import { createNetworkingV1ServiceCIDR } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.delete('/apis/networking.k8s.io/v1/servicecidrs', deleteNetworkingV1CollectionServiceCIDR)

router.get('/apis/networking.k8s.io/v1/servicecidrs', listNetworkingV1ServiceCIDR)

router.post('/apis/networking.k8s.io/v1/servicecidrs', createNetworkingV1ServiceCIDR)

export default router;
