// Path: routes/ApisAutoscalingV2Namespaces{namespace}HorizontalpodautoscalersRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAutoscalingV2CollectionNamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV2Controller'
import { listAutoscalingV2NamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV2Controller'
import { createAutoscalingV2NamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV2Controller'

import {router} from './router';

router.delete('/apis/autoscaling/v2/namespaces/:namespace/horizontalpodautoscalers', deleteAutoscalingV2CollectionNamespacedHorizontalPodAutoscaler)

router.get('/apis/autoscaling/v2/namespaces/:namespace/horizontalpodautoscalers', listAutoscalingV2NamespacedHorizontalPodAutoscaler)

router.post('/apis/autoscaling/v2/namespaces/:namespace/horizontalpodautoscalers', createAutoscalingV2NamespacedHorizontalPodAutoscaler)

export default router;
