// Path: routes/ApisAppsV1WatchNamespaces{namespace}DaemonsetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAppsV1NamespacedDaemonSetList } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/watch/namespaces/:namespace/daemonsets', watchAppsV1NamespacedDaemonSetList)

export default router;
