// Path: routes/ApisNetworking.k8s.ioV1beta1WatchServicecidrsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchNetworkingV1beta1ServiceCIDRList } from '../controllers/NetworkingV1beta1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1beta1/watch/servicecidrs', watchNetworkingV1beta1ServiceCIDRList)

export default router;
