// Path: routes/ApisAutoscalingV2Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getAutoscalingV2APIResources } from '../controllers/AutoscalingV2Controller'

import {router} from './router';

router.get('/apis/autoscaling/v2/', getAutoscalingV2APIResources)

export default router;
