// Path: routes/ApisCertificates.k8s.ioV1alpha1Clustertrustbundles{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCertificatesV1alpha1ClusterTrustBundle } from '../controllers/CertificatesV1alpha1Controller'
import { readCertificatesV1alpha1ClusterTrustBundle } from '../controllers/CertificatesV1alpha1Controller'
import { patchCertificatesV1alpha1ClusterTrustBundle } from '../controllers/CertificatesV1alpha1Controller'
import { replaceCertificatesV1alpha1ClusterTrustBundle } from '../controllers/CertificatesV1alpha1Controller'

import {router} from './router';

router.delete('/apis/certificates.k8s.io/v1alpha1/clustertrustbundles/:name', deleteCertificatesV1alpha1ClusterTrustBundle)

router.get('/apis/certificates.k8s.io/v1alpha1/clustertrustbundles/:name', readCertificatesV1alpha1ClusterTrustBundle)

router.patch('/apis/certificates.k8s.io/v1alpha1/clustertrustbundles/:name', patchCertificatesV1alpha1ClusterTrustBundle)

router.put('/apis/certificates.k8s.io/v1alpha1/clustertrustbundles/:name', replaceCertificatesV1alpha1ClusterTrustBundle)

export default router;
