// Path: routes/ApisScheduling.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getSchedulingAPIGroup } from '../controllers/SchedulingController'

import {router} from './router';

router.get('/apis/scheduling.k8s.io/', getSchedulingAPIGroup)

export default router;
