// Path: routes/ApisAdmissionregistration.k8s.ioV1alpha1WatchMutatingadmissionpoliciesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAdmissionregistrationV1alpha1MutatingAdmissionPolicyList } from '../controllers/AdmissionregistrationV1alpha1Controller'

import {router} from './router';

router.get('/apis/admissionregistration.k8s.io/v1alpha1/watch/mutatingadmissionpolicies', watchAdmissionregistrationV1alpha1MutatingAdmissionPolicyList)

export default router;
