// Path: routes/ApisAutoscalingV1WatchHorizontalpodautoscalersRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAutoscalingV1HorizontalPodAutoscalerListForAllNamespaces } from '../controllers/AutoscalingV1Controller'

import {router} from './router';

router.get('/apis/autoscaling/v1/watch/horizontalpodautoscalers', watchAutoscalingV1HorizontalPodAutoscalerListForAllNamespaces)

export default router;
