// Path: routes/ApisStorage.k8s.ioV1WatchCsinodes{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchStorageV1CSINode } from '../controllers/StorageV1Controller'

import {router} from './router';

router.get('/apis/storage.k8s.io/v1/watch/csinodes/:name', watchStorageV1CSINode)

export default router;
