// Path: routes/ApisCertificates.k8s.ioV1Certificatesigningrequests{name}ApprovalRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readCertificatesV1CertificateSigningRequestApproval } from '../controllers/CertificatesV1Controller'
import { patchCertificatesV1CertificateSigningRequestApproval } from '../controllers/CertificatesV1Controller'
import { replaceCertificatesV1CertificateSigningRequestApproval } from '../controllers/CertificatesV1Controller'

import {router} from './router';

router.get('/apis/certificates.k8s.io/v1/certificatesigningrequests/:name/approval', readCertificatesV1CertificateSigningRequestApproval)

router.patch('/apis/certificates.k8s.io/v1/certificatesigningrequests/:name/approval', patchCertificatesV1CertificateSigningRequestApproval)

router.put('/apis/certificates.k8s.io/v1/certificatesigningrequests/:name/approval', replaceCertificatesV1CertificateSigningRequestApproval)

export default router;
