// Path: routes/ApisDiscovery.k8s.ioV1WatchNamespaces{namespace}EndpointslicesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchDiscoveryV1NamespacedEndpointSliceList } from '../controllers/DiscoveryV1Controller'

import {router} from './router';

router.get('/apis/discovery.k8s.io/v1/watch/namespaces/:namespace/endpointslices', watchDiscoveryV1NamespacedEndpointSliceList)

export default router;
