// Path: routes/ApisEvents.k8s.ioV1WatchNamespaces{namespace}EventsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchEventsV1NamespacedEventList } from '../controllers/EventsV1Controller'

import {router} from './router';

router.get('/apis/events.k8s.io/v1/watch/namespaces/:namespace/events', watchEventsV1NamespacedEventList)

export default router;
