// Path: routes/ApisRbac.authorization.k8s.ioV1Namespaces{namespace}Roles{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteRbacAuthorizationV1NamespacedRole } from '../controllers/RbacAuthorizationV1Controller'
import { readRbacAuthorizationV1NamespacedRole } from '../controllers/RbacAuthorizationV1Controller'
import { patchRbacAuthorizationV1NamespacedRole } from '../controllers/RbacAuthorizationV1Controller'
import { replaceRbacAuthorizationV1NamespacedRole } from '../controllers/RbacAuthorizationV1Controller'

import {router} from './router';

router.delete('/apis/rbac.authorization.k8s.io/v1/namespaces/:namespace/roles/:name', deleteRbacAuthorizationV1NamespacedRole)

router.get('/apis/rbac.authorization.k8s.io/v1/namespaces/:namespace/roles/:name', readRbacAuthorizationV1NamespacedRole)

router.patch('/apis/rbac.authorization.k8s.io/v1/namespaces/:namespace/roles/:name', patchRbacAuthorizationV1NamespacedRole)

router.put('/apis/rbac.authorization.k8s.io/v1/namespaces/:namespace/roles/:name', replaceRbacAuthorizationV1NamespacedRole)

export default router;
