// Path: routes/ApisAuthentication.k8s.ioV1SelfsubjectreviewsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { createAuthenticationV1SelfSubjectReview } from '../controllers/AuthenticationV1Controller'

import {router} from './router';

router.post('/apis/authentication.k8s.io/v1/selfsubjectreviews', createAuthenticationV1SelfSubjectReview)

export default router;
