// Path: routes/ApisFlowcontrol.apiserver.k8s.ioV1PrioritylevelconfigurationsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteFlowcontrolApiserverV1CollectionPriorityLevelConfiguration } from '../controllers/FlowcontrolApiserverV1Controller'
import { listFlowcontrolApiserverV1PriorityLevelConfiguration } from '../controllers/FlowcontrolApiserverV1Controller'
import { createFlowcontrolApiserverV1PriorityLevelConfiguration } from '../controllers/FlowcontrolApiserverV1Controller'

import {router} from './router';

router.delete('/apis/flowcontrol.apiserver.k8s.io/v1/prioritylevelconfigurations', deleteFlowcontrolApiserverV1CollectionPriorityLevelConfiguration)

router.get('/apis/flowcontrol.apiserver.k8s.io/v1/prioritylevelconfigurations', listFlowcontrolApiserverV1PriorityLevelConfiguration)

router.post('/apis/flowcontrol.apiserver.k8s.io/v1/prioritylevelconfigurations', createFlowcontrolApiserverV1PriorityLevelConfiguration)

export default router;
