// Path: routes/ApisNetworking.k8s.ioV1Namespaces{namespace}Ingresses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNetworkingV1NamespacedIngress } from '../controllers/NetworkingV1Controller'
import { readNetworkingV1NamespacedIngress } from '../controllers/NetworkingV1Controller'
import { patchNetworkingV1NamespacedIngress } from '../controllers/NetworkingV1Controller'
import { replaceNetworkingV1NamespacedIngress } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.delete('/apis/networking.k8s.io/v1/namespaces/:namespace/ingresses/:name', deleteNetworkingV1NamespacedIngress)

router.get('/apis/networking.k8s.io/v1/namespaces/:namespace/ingresses/:name', readNetworkingV1NamespacedIngress)

router.patch('/apis/networking.k8s.io/v1/namespaces/:namespace/ingresses/:name', patchNetworkingV1NamespacedIngress)

router.put('/apis/networking.k8s.io/v1/namespaces/:namespace/ingresses/:name', replaceNetworkingV1NamespacedIngress)

export default router;
