// Path: routes/ApisStoragemigration.k8s.ioV1alpha1StorageversionmigrationsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteStoragemigrationV1alpha1CollectionStorageVersionMigration } from '../controllers/StoragemigrationV1alpha1Controller'
import { listStoragemigrationV1alpha1StorageVersionMigration } from '../controllers/StoragemigrationV1alpha1Controller'
import { createStoragemigrationV1alpha1StorageVersionMigration } from '../controllers/StoragemigrationV1alpha1Controller'

import {router} from './router';

router.delete('/apis/storagemigration.k8s.io/v1alpha1/storageversionmigrations', deleteStoragemigrationV1alpha1CollectionStorageVersionMigration)

router.get('/apis/storagemigration.k8s.io/v1alpha1/storageversionmigrations', listStoragemigrationV1alpha1StorageVersionMigration)

router.post('/apis/storagemigration.k8s.io/v1alpha1/storageversionmigrations', createStoragemigrationV1alpha1StorageVersionMigration)

export default router;
