// Path: routes/ApisStorage.k8s.ioV1WatchCsidriversRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchStorageV1CSIDriverList } from '../controllers/StorageV1Controller'

import {router} from './router';

router.get('/apis/storage.k8s.io/v1/watch/csidrivers', watchStorageV1CSIDriverList)

export default router;
