// Path: routes/ApisFlowcontrol.apiserver.k8s.ioV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getFlowcontrolApiserverV1APIResources } from '../controllers/FlowcontrolApiserverV1Controller'

import {router} from './router';

router.get('/apis/flowcontrol.apiserver.k8s.io/v1/', getFlowcontrolApiserverV1APIResources)

export default router;
