// Path: routes/ApisPolicyV1Namespaces{namespace}Poddisruptionbudgets{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deletePolicyV1NamespacedPodDisruptionBudget } from '../controllers/PolicyV1Controller'
import { readPolicyV1NamespacedPodDisruptionBudget } from '../controllers/PolicyV1Controller'
import { patchPolicyV1NamespacedPodDisruptionBudget } from '../controllers/PolicyV1Controller'
import { replacePolicyV1NamespacedPodDisruptionBudget } from '../controllers/PolicyV1Controller'

import {router} from './router';

router.delete('/apis/policy/v1/namespaces/:namespace/poddisruptionbudgets/:name', deletePolicyV1NamespacedPodDisruptionBudget)

router.get('/apis/policy/v1/namespaces/:namespace/poddisruptionbudgets/:name', readPolicyV1NamespacedPodDisruptionBudget)

router.patch('/apis/policy/v1/namespaces/:namespace/poddisruptionbudgets/:name', patchPolicyV1NamespacedPodDisruptionBudget)

router.put('/apis/policy/v1/namespaces/:namespace/poddisruptionbudgets/:name', replacePolicyV1NamespacedPodDisruptionBudget)

export default router;
