// Path: routes/ApisAppsV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getAppsV1APIResources } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/', getAppsV1APIResources)

export default router;
