// Path: routes/ApisAppsV1WatchNamespaces{namespace}DeploymentsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAppsV1NamespacedDeploymentList } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/watch/namespaces/:namespace/deployments', watchAppsV1NamespacedDeploymentList)

export default router;
