// Path: routes/ApisRbac.authorization.k8s.ioV1Namespaces{namespace}RolesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteRbacAuthorizationV1CollectionNamespacedRole } from '../controllers/RbacAuthorizationV1Controller'
import { listRbacAuthorizationV1NamespacedRole } from '../controllers/RbacAuthorizationV1Controller'
import { createRbacAuthorizationV1NamespacedRole } from '../controllers/RbacAuthorizationV1Controller'

import {router} from './router';

router.delete('/apis/rbac.authorization.k8s.io/v1/namespaces/:namespace/roles', deleteRbacAuthorizationV1CollectionNamespacedRole)

router.get('/apis/rbac.authorization.k8s.io/v1/namespaces/:namespace/roles', listRbacAuthorizationV1NamespacedRole)

router.post('/apis/rbac.authorization.k8s.io/v1/namespaces/:namespace/roles', createRbacAuthorizationV1NamespacedRole)

export default router;
