// Path: routes/ApisFlowcontrol.apiserver.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getFlowcontrolApiserverAPIGroup } from '../controllers/FlowcontrolApiserverController'

import {router} from './router';

router.get('/apis/flowcontrol.apiserver.k8s.io/', getFlowcontrolApiserverAPIGroup)

export default router;
