// Path: routes/ApisAuthentication.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getAuthenticationAPIGroup } from '../controllers/AuthenticationController'

import {router} from './router';

router.get('/apis/authentication.k8s.io/', getAuthenticationAPIGroup)

export default router;
