// Path: routes/ApisScheduling.k8s.ioV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getSchedulingV1APIResources } from '../controllers/SchedulingV1Controller'

import {router} from './router';

router.get('/apis/scheduling.k8s.io/v1/', getSchedulingV1APIResources)

export default router;
