// Path: routes/ApisResource.k8s.ioV1alpha3WatchDeviceclassesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchResourceV1alpha3DeviceClassList } from '../controllers/ResourceV1alpha3Controller'

import {router} from './router';

router.get('/apis/resource.k8s.io/v1alpha3/watch/deviceclasses', watchResourceV1alpha3DeviceClassList)

export default router;
