// Path: routes/ApisResource.k8s.ioV1alpha3Resourceslices{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteResourceV1alpha3ResourceSlice } from '../controllers/ResourceV1alpha3Controller'
import { readResourceV1alpha3ResourceSlice } from '../controllers/ResourceV1alpha3Controller'
import { patchResourceV1alpha3ResourceSlice } from '../controllers/ResourceV1alpha3Controller'
import { replaceResourceV1alpha3ResourceSlice } from '../controllers/ResourceV1alpha3Controller'

import {router} from './router';

router.delete('/apis/resource.k8s.io/v1alpha3/resourceslices/:name', deleteResourceV1alpha3ResourceSlice)

router.get('/apis/resource.k8s.io/v1alpha3/resourceslices/:name', readResourceV1alpha3ResourceSlice)

router.patch('/apis/resource.k8s.io/v1alpha3/resourceslices/:name', patchResourceV1alpha3ResourceSlice)

router.put('/apis/resource.k8s.io/v1alpha3/resourceslices/:name', replaceResourceV1alpha3ResourceSlice)

export default router;
