// Path: routes/ApisPolicyV1Namespaces{namespace}Poddisruptionbudgets{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readPolicyV1NamespacedPodDisruptionBudgetStatus } from '../controllers/PolicyV1Controller'
import { patchPolicyV1NamespacedPodDisruptionBudgetStatus } from '../controllers/PolicyV1Controller'
import { replacePolicyV1NamespacedPodDisruptionBudgetStatus } from '../controllers/PolicyV1Controller'

import {router} from './router';

router.get('/apis/policy/v1/namespaces/:namespace/poddisruptionbudgets/:name/status', readPolicyV1NamespacedPodDisruptionBudgetStatus)

router.patch('/apis/policy/v1/namespaces/:namespace/poddisruptionbudgets/:name/status', patchPolicyV1NamespacedPodDisruptionBudgetStatus)

router.put('/apis/policy/v1/namespaces/:namespace/poddisruptionbudgets/:name/status', replacePolicyV1NamespacedPodDisruptionBudgetStatus)

export default router;
