// Path: routes/ApisCertificates.k8s.ioV1Certificatesigningrequests{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readCertificatesV1CertificateSigningRequestStatus } from '../controllers/CertificatesV1Controller'
import { patchCertificatesV1CertificateSigningRequestStatus } from '../controllers/CertificatesV1Controller'
import { replaceCertificatesV1CertificateSigningRequestStatus } from '../controllers/CertificatesV1Controller'

import {router} from './router';

router.get('/apis/certificates.k8s.io/v1/certificatesigningrequests/:name/status', readCertificatesV1CertificateSigningRequestStatus)

router.patch('/apis/certificates.k8s.io/v1/certificatesigningrequests/:name/status', patchCertificatesV1CertificateSigningRequestStatus)

router.put('/apis/certificates.k8s.io/v1/certificatesigningrequests/:name/status', replaceCertificatesV1CertificateSigningRequestStatus)

export default router;
