// Path: routes/ApisAppsV1WatchNamespaces{namespace}Statefulsets{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAppsV1NamespacedStatefulSet } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/watch/namespaces/:namespace/statefulsets/:name', watchAppsV1NamespacedStatefulSet)

export default router;
