// Path: routes/ApisApiextensions.k8s.ioV1Customresourcedefinitions{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteApiextensionsV1CustomResourceDefinition } from '../controllers/ApiextensionsV1Controller'
import { readApiextensionsV1CustomResourceDefinition } from '../controllers/ApiextensionsV1Controller'
import { patchApiextensionsV1CustomResourceDefinition } from '../controllers/ApiextensionsV1Controller'
import { replaceApiextensionsV1CustomResourceDefinition } from '../controllers/ApiextensionsV1Controller'

import {router} from './router';

router.delete('/apis/apiextensions.k8s.io/v1/customresourcedefinitions/:name', deleteApiextensionsV1CustomResourceDefinition)

router.get('/apis/apiextensions.k8s.io/v1/customresourcedefinitions/:name', readApiextensionsV1CustomResourceDefinition)

router.patch('/apis/apiextensions.k8s.io/v1/customresourcedefinitions/:name', patchApiextensionsV1CustomResourceDefinition)

router.put('/apis/apiextensions.k8s.io/v1/customresourcedefinitions/:name', replaceApiextensionsV1CustomResourceDefinition)

export default router;
