// Path: routes/ApisStorage.k8s.ioV1Namespaces{namespace}Csistoragecapacities{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteStorageV1NamespacedCSIStorageCapacity } from '../controllers/StorageV1Controller'
import { readStorageV1NamespacedCSIStorageCapacity } from '../controllers/StorageV1Controller'
import { patchStorageV1NamespacedCSIStorageCapacity } from '../controllers/StorageV1Controller'
import { replaceStorageV1NamespacedCSIStorageCapacity } from '../controllers/StorageV1Controller'

import {router} from './router';

router.delete('/apis/storage.k8s.io/v1/namespaces/:namespace/csistoragecapacities/:name', deleteStorageV1NamespacedCSIStorageCapacity)

router.get('/apis/storage.k8s.io/v1/namespaces/:namespace/csistoragecapacities/:name', readStorageV1NamespacedCSIStorageCapacity)

router.patch('/apis/storage.k8s.io/v1/namespaces/:namespace/csistoragecapacities/:name', patchStorageV1NamespacedCSIStorageCapacity)

router.put('/apis/storage.k8s.io/v1/namespaces/:namespace/csistoragecapacities/:name', replaceStorageV1NamespacedCSIStorageCapacity)

export default router;
