// Path: routes/ApisBatchV1WatchNamespaces{namespace}CronjobsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchBatchV1NamespacedCronJobList } from '../controllers/BatchV1Controller'

import {router} from './router';

router.get('/apis/batch/v1/watch/namespaces/:namespace/cronjobs', watchBatchV1NamespacedCronJobList)

export default router;
