// Path: routes/ApisDiscovery.k8s.ioV1EndpointslicesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listDiscoveryV1EndpointSliceForAllNamespaces } from '../controllers/DiscoveryV1Controller'

import {router} from './router';

router.get('/apis/discovery.k8s.io/v1/endpointslices', listDiscoveryV1EndpointSliceForAllNamespaces)

export default router;
