// Path: routes/ApisResource.k8s.ioV1alpha3Namespaces{namespace}ResourceclaimtemplatesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteResourceV1alpha3CollectionNamespacedResourceClaimTemplate } from '../controllers/ResourceV1alpha3Controller'
import { listResourceV1alpha3NamespacedResourceClaimTemplate } from '../controllers/ResourceV1alpha3Controller'
import { createResourceV1alpha3NamespacedResourceClaimTemplate } from '../controllers/ResourceV1alpha3Controller'

import {router} from './router';

router.delete('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaimtemplates', deleteResourceV1alpha3CollectionNamespacedResourceClaimTemplate)

router.get('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaimtemplates', listResourceV1alpha3NamespacedResourceClaimTemplate)

router.post('/apis/resource.k8s.io/v1alpha3/namespaces/:namespace/resourceclaimtemplates', createResourceV1alpha3NamespacedResourceClaimTemplate)

export default router;
