// Path: routes/ApisBatchV1WatchJobsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchBatchV1JobListForAllNamespaces } from '../controllers/BatchV1Controller'

import {router} from './router';

router.get('/apis/batch/v1/watch/jobs', watchBatchV1JobListForAllNamespaces)

export default router;
