// Path: routes/ApisCoordination.k8s.ioV1LeasesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listCoordinationV1LeaseForAllNamespaces } from '../controllers/CoordinationV1Controller'

import {router} from './router';

router.get('/apis/coordination.k8s.io/v1/leases', listCoordinationV1LeaseForAllNamespaces)

export default router;
