// Path: routes/ApisRbac.authorization.k8s.ioV1Clusterrolebindings{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteRbacAuthorizationV1ClusterRoleBinding } from '../controllers/RbacAuthorizationV1Controller'
import { readRbacAuthorizationV1ClusterRoleBinding } from '../controllers/RbacAuthorizationV1Controller'
import { patchRbacAuthorizationV1ClusterRoleBinding } from '../controllers/RbacAuthorizationV1Controller'
import { replaceRbacAuthorizationV1ClusterRoleBinding } from '../controllers/RbacAuthorizationV1Controller'

import {router} from './router';

router.delete('/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/:name', deleteRbacAuthorizationV1ClusterRoleBinding)

router.get('/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/:name', readRbacAuthorizationV1ClusterRoleBinding)

router.patch('/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/:name', patchRbacAuthorizationV1ClusterRoleBinding)

router.put('/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/:name', replaceRbacAuthorizationV1ClusterRoleBinding)

export default router;
