// Path: routes/ApisAppsV1WatchNamespaces{namespace}ControllerrevisionsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAppsV1NamespacedControllerRevisionList } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/watch/namespaces/:namespace/controllerrevisions', watchAppsV1NamespacedControllerRevisionList)

export default router;
