// Path: routes/ApisAdmissionregistration.k8s.ioV1alpha1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getAdmissionregistrationV1alpha1APIResources } from '../controllers/AdmissionregistrationV1alpha1Controller'

import {router} from './router';

router.get('/apis/admissionregistration.k8s.io/v1alpha1/', getAdmissionregistrationV1alpha1APIResources)

export default router;
