// Path: routes/ApisNetworking.k8s.ioV1beta1ServicecidrsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNetworkingV1beta1CollectionServiceCIDR } from '../controllers/NetworkingV1beta1Controller'
import { listNetworkingV1beta1ServiceCIDR } from '../controllers/NetworkingV1beta1Controller'
import { createNetworkingV1beta1ServiceCIDR } from '../controllers/NetworkingV1beta1Controller'

import {router} from './router';

router.delete('/apis/networking.k8s.io/v1beta1/servicecidrs', deleteNetworkingV1beta1CollectionServiceCIDR)

router.get('/apis/networking.k8s.io/v1beta1/servicecidrs', listNetworkingV1beta1ServiceCIDR)

router.post('/apis/networking.k8s.io/v1beta1/servicecidrs', createNetworkingV1beta1ServiceCIDR)

export default router;
