// Path: routes/ApisNode.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getNodeAPIGroup } from '../controllers/NodeController'

import {router} from './router';

router.get('/apis/node.k8s.io/', getNodeAPIGroup)

export default router;
