// Path: routes/ApisAppsV1Namespaces{namespace}DaemonsetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAppsV1CollectionNamespacedDaemonSet } from '../controllers/AppsV1Controller'
import { listAppsV1NamespacedDaemonSet } from '../controllers/AppsV1Controller'
import { createAppsV1NamespacedDaemonSet } from '../controllers/AppsV1Controller'

import {router} from './router';

router.delete('/apis/apps/v1/namespaces/:namespace/daemonsets', deleteAppsV1CollectionNamespacedDaemonSet)

router.get('/apis/apps/v1/namespaces/:namespace/daemonsets', listAppsV1NamespacedDaemonSet)

router.post('/apis/apps/v1/namespaces/:namespace/daemonsets', createAppsV1NamespacedDaemonSet)

export default router;
