// Path: routes/ApisCertificates.k8s.ioV1alpha1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getCertificatesV1alpha1APIResources } from '../controllers/CertificatesV1alpha1Controller'

import {router} from './router';

router.get('/apis/certificates.k8s.io/v1alpha1/', getCertificatesV1alpha1APIResources)

export default router;
