// Path: routes/ApisResource.k8s.ioV1beta1Namespaces{namespace}ResourceclaimsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteResourceV1beta1CollectionNamespacedResourceClaim } from '../controllers/ResourceV1beta1Controller'
import { listResourceV1beta1NamespacedResourceClaim } from '../controllers/ResourceV1beta1Controller'
import { createResourceV1beta1NamespacedResourceClaim } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.delete('/apis/resource.k8s.io/v1beta1/namespaces/:namespace/resourceclaims', deleteResourceV1beta1CollectionNamespacedResourceClaim)

router.get('/apis/resource.k8s.io/v1beta1/namespaces/:namespace/resourceclaims', listResourceV1beta1NamespacedResourceClaim)

router.post('/apis/resource.k8s.io/v1beta1/namespaces/:namespace/resourceclaims', createResourceV1beta1NamespacedResourceClaim)

export default router;
