// Path: routes/ApisStorage.k8s.ioV1WatchNamespaces{namespace}Csistoragecapacities{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchStorageV1NamespacedCSIStorageCapacity } from '../controllers/StorageV1Controller'

import {router} from './router';

router.get('/apis/storage.k8s.io/v1/watch/namespaces/:namespace/csistoragecapacities/:name', watchStorageV1NamespacedCSIStorageCapacity)

export default router;
