// Path: routes/ApisResource.k8s.ioV1beta1WatchResourceslicesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchResourceV1beta1ResourceSliceList } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.get('/apis/resource.k8s.io/v1beta1/watch/resourceslices', watchResourceV1beta1ResourceSliceList)

export default router;
