// Path: routes/ApisAppsV1Namespaces{namespace}Daemonsets{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readAppsV1NamespacedDaemonSetStatus } from '../controllers/AppsV1Controller'
import { patchAppsV1NamespacedDaemonSetStatus } from '../controllers/AppsV1Controller'
import { replaceAppsV1NamespacedDaemonSetStatus } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/namespaces/:namespace/daemonsets/:name/status', readAppsV1NamespacedDaemonSetStatus)

router.patch('/apis/apps/v1/namespaces/:namespace/daemonsets/:name/status', patchAppsV1NamespacedDaemonSetStatus)

router.put('/apis/apps/v1/namespaces/:namespace/daemonsets/:name/status', replaceAppsV1NamespacedDaemonSetStatus)

export default router;
