// Path: routes/ApisNetworking.k8s.ioV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getNetworkingV1APIResources } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1/', getNetworkingV1APIResources)

export default router;
