// Path: routes/ApisResource.k8s.ioV1beta1ResourceclaimtemplatesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listResourceV1beta1ResourceClaimTemplateForAllNamespaces } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.get('/apis/resource.k8s.io/v1beta1/resourceclaimtemplates', listResourceV1beta1ResourceClaimTemplateForAllNamespaces)

export default router;
