// Path: routes/ApisNetworking.k8s.ioV1beta1Servicecidrs{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNetworkingV1beta1ServiceCIDR } from '../controllers/NetworkingV1beta1Controller'
import { readNetworkingV1beta1ServiceCIDR } from '../controllers/NetworkingV1beta1Controller'
import { patchNetworkingV1beta1ServiceCIDR } from '../controllers/NetworkingV1beta1Controller'
import { replaceNetworkingV1beta1ServiceCIDR } from '../controllers/NetworkingV1beta1Controller'

import {router} from './router';

router.delete('/apis/networking.k8s.io/v1beta1/servicecidrs/:name', deleteNetworkingV1beta1ServiceCIDR)

router.get('/apis/networking.k8s.io/v1beta1/servicecidrs/:name', readNetworkingV1beta1ServiceCIDR)

router.patch('/apis/networking.k8s.io/v1beta1/servicecidrs/:name', patchNetworkingV1beta1ServiceCIDR)

router.put('/apis/networking.k8s.io/v1beta1/servicecidrs/:name', replaceNetworkingV1beta1ServiceCIDR)

export default router;
