// Path: routes/ApisNetworking.k8s.ioV1WatchIngressclasses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchNetworkingV1IngressClass } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1/watch/ingressclasses/:name', watchNetworkingV1IngressClass)

export default router;
