// Path: routes/ApisAppsV1WatchNamespaces{namespace}Daemonsets{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAppsV1NamespacedDaemonSet } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/watch/namespaces/:namespace/daemonsets/:name', watchAppsV1NamespacedDaemonSet)

export default router;
