// Path: routes/ApisApiregistration.k8s.ioV1Apiservices{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteApiregistrationV1APIService } from '../controllers/ApiregistrationV1Controller'
import { readApiregistrationV1APIService } from '../controllers/ApiregistrationV1Controller'
import { patchApiregistrationV1APIService } from '../controllers/ApiregistrationV1Controller'
import { replaceApiregistrationV1APIService } from '../controllers/ApiregistrationV1Controller'

import {router} from './router';

router.delete('/apis/apiregistration.k8s.io/v1/apiservices/:name', deleteApiregistrationV1APIService)

router.get('/apis/apiregistration.k8s.io/v1/apiservices/:name', readApiregistrationV1APIService)

router.patch('/apis/apiregistration.k8s.io/v1/apiservices/:name', patchApiregistrationV1APIService)

router.put('/apis/apiregistration.k8s.io/v1/apiservices/:name', replaceApiregistrationV1APIService)

export default router;
