// Path: routes/ApisStorage.k8s.ioV1VolumeattachmentsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteStorageV1CollectionVolumeAttachment } from '../controllers/StorageV1Controller'
import { listStorageV1VolumeAttachment } from '../controllers/StorageV1Controller'
import { createStorageV1VolumeAttachment } from '../controllers/StorageV1Controller'

import {router} from './router';

router.delete('/apis/storage.k8s.io/v1/volumeattachments', deleteStorageV1CollectionVolumeAttachment)

router.get('/apis/storage.k8s.io/v1/volumeattachments', listStorageV1VolumeAttachment)

router.post('/apis/storage.k8s.io/v1/volumeattachments', createStorageV1VolumeAttachment)

export default router;
