// Path: routes/ApisResource.k8s.ioV1beta1DeviceclassesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteResourceV1beta1CollectionDeviceClass } from '../controllers/ResourceV1beta1Controller'
import { listResourceV1beta1DeviceClass } from '../controllers/ResourceV1beta1Controller'
import { createResourceV1beta1DeviceClass } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.delete('/apis/resource.k8s.io/v1beta1/deviceclasses', deleteResourceV1beta1CollectionDeviceClass)

router.get('/apis/resource.k8s.io/v1beta1/deviceclasses', listResourceV1beta1DeviceClass)

router.post('/apis/resource.k8s.io/v1beta1/deviceclasses', createResourceV1beta1DeviceClass)

export default router;
