// Path: routes/ApisAdmissionregistration.k8s.ioV1Validatingwebhookconfigurations{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAdmissionregistrationV1ValidatingWebhookConfiguration } from '../controllers/AdmissionregistrationV1Controller'
import { readAdmissionregistrationV1ValidatingWebhookConfiguration } from '../controllers/AdmissionregistrationV1Controller'
import { patchAdmissionregistrationV1ValidatingWebhookConfiguration } from '../controllers/AdmissionregistrationV1Controller'
import { replaceAdmissionregistrationV1ValidatingWebhookConfiguration } from '../controllers/AdmissionregistrationV1Controller'

import {router} from './router';

router.delete('/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations/:name', deleteAdmissionregistrationV1ValidatingWebhookConfiguration)

router.get('/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations/:name', readAdmissionregistrationV1ValidatingWebhookConfiguration)

router.patch('/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations/:name', patchAdmissionregistrationV1ValidatingWebhookConfiguration)

router.put('/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations/:name', replaceAdmissionregistrationV1ValidatingWebhookConfiguration)

export default router;
