// Path: routes/ApisNetworking.k8s.ioV1beta1Ipaddresses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNetworkingV1beta1IPAddress } from '../controllers/NetworkingV1beta1Controller'
import { readNetworkingV1beta1IPAddress } from '../controllers/NetworkingV1beta1Controller'
import { patchNetworkingV1beta1IPAddress } from '../controllers/NetworkingV1beta1Controller'
import { replaceNetworkingV1beta1IPAddress } from '../controllers/NetworkingV1beta1Controller'

import {router} from './router';

router.delete('/apis/networking.k8s.io/v1beta1/ipaddresses/:name', deleteNetworkingV1beta1IPAddress)

router.get('/apis/networking.k8s.io/v1beta1/ipaddresses/:name', readNetworkingV1beta1IPAddress)

router.patch('/apis/networking.k8s.io/v1beta1/ipaddresses/:name', patchNetworkingV1beta1IPAddress)

router.put('/apis/networking.k8s.io/v1beta1/ipaddresses/:name', replaceNetworkingV1beta1IPAddress)

export default router;
