// Path: routes/ApisAppsV1Namespaces{namespace}Daemonsets{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAppsV1NamespacedDaemonSet } from '../controllers/AppsV1Controller'
import { readAppsV1NamespacedDaemonSet } from '../controllers/AppsV1Controller'
import { patchAppsV1NamespacedDaemonSet } from '../controllers/AppsV1Controller'
import { replaceAppsV1NamespacedDaemonSet } from '../controllers/AppsV1Controller'

import {router} from './router';

router.delete('/apis/apps/v1/namespaces/:namespace/daemonsets/:name', deleteAppsV1NamespacedDaemonSet)

router.get('/apis/apps/v1/namespaces/:namespace/daemonsets/:name', readAppsV1NamespacedDaemonSet)

router.patch('/apis/apps/v1/namespaces/:namespace/daemonsets/:name', patchAppsV1NamespacedDaemonSet)

router.put('/apis/apps/v1/namespaces/:namespace/daemonsets/:name', replaceAppsV1NamespacedDaemonSet)

export default router;
