// Path: routes/ApisResource.k8s.ioV1beta1WatchDeviceclassesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchResourceV1beta1DeviceClassList } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.get('/apis/resource.k8s.io/v1beta1/watch/deviceclasses', watchResourceV1beta1DeviceClassList)

export default router;
