// Path: routes/ApisResource.k8s.ioV1beta1WatchNamespaces{namespace}Resourceclaimtemplates{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchResourceV1beta1NamespacedResourceClaimTemplate } from '../controllers/ResourceV1beta1Controller'

import {router} from './router';

router.get('/apis/resource.k8s.io/v1beta1/watch/namespaces/:namespace/resourceclaimtemplates/:name', watchResourceV1beta1NamespacedResourceClaimTemplate)

export default router;
