// Path: routes/ApisNetworking.k8s.ioV1Namespaces{namespace}Ingresses{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readNetworkingV1NamespacedIngressStatus } from '../controllers/NetworkingV1Controller'
import { patchNetworkingV1NamespacedIngressStatus } from '../controllers/NetworkingV1Controller'
import { replaceNetworkingV1NamespacedIngressStatus } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1/namespaces/:namespace/ingresses/:name/status', readNetworkingV1NamespacedIngressStatus)

router.patch('/apis/networking.k8s.io/v1/namespaces/:namespace/ingresses/:name/status', patchNetworkingV1NamespacedIngressStatus)

router.put('/apis/networking.k8s.io/v1/namespaces/:namespace/ingresses/:name/status', replaceNetworkingV1NamespacedIngressStatus)

export default router;
