// Path: routes/ApisCertificates.k8s.ioV1alpha1WatchClustertrustbundles{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCertificatesV1alpha1ClusterTrustBundle } from '../controllers/CertificatesV1alpha1Controller'

import {router} from './router';

router.get('/apis/certificates.k8s.io/v1alpha1/watch/clustertrustbundles/:name', watchCertificatesV1alpha1ClusterTrustBundle)

export default router;
