// Path: routes/ApisAppsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getAppsAPIGroup } from '../controllers/AppsController'

import {router} from './router';

router.get('/apis/apps/', getAppsAPIGroup)

export default router;
