// Path: routes/ApisStorage.k8s.ioV1beta1Volumeattributesclasses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteStorageV1beta1VolumeAttributesClass } from '../controllers/StorageV1beta1Controller'
import { readStorageV1beta1VolumeAttributesClass } from '../controllers/StorageV1beta1Controller'
import { patchStorageV1beta1VolumeAttributesClass } from '../controllers/StorageV1beta1Controller'
import { replaceStorageV1beta1VolumeAttributesClass } from '../controllers/StorageV1beta1Controller'

import {router} from './router';

router.delete('/apis/storage.k8s.io/v1beta1/volumeattributesclasses/:name', deleteStorageV1beta1VolumeAttributesClass)

router.get('/apis/storage.k8s.io/v1beta1/volumeattributesclasses/:name', readStorageV1beta1VolumeAttributesClass)

router.patch('/apis/storage.k8s.io/v1beta1/volumeattributesclasses/:name', patchStorageV1beta1VolumeAttributesClass)

router.put('/apis/storage.k8s.io/v1beta1/volumeattributesclasses/:name', replaceStorageV1beta1VolumeAttributesClass)

export default router;
