// Path: routes/ApisRbac.authorization.k8s.ioV1ClusterrolebindingsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteRbacAuthorizationV1CollectionClusterRoleBinding } from '../controllers/RbacAuthorizationV1Controller'
import { listRbacAuthorizationV1ClusterRoleBinding } from '../controllers/RbacAuthorizationV1Controller'
import { createRbacAuthorizationV1ClusterRoleBinding } from '../controllers/RbacAuthorizationV1Controller'

import {router} from './router';

router.delete('/apis/rbac.authorization.k8s.io/v1/clusterrolebindings', deleteRbacAuthorizationV1CollectionClusterRoleBinding)

router.get('/apis/rbac.authorization.k8s.io/v1/clusterrolebindings', listRbacAuthorizationV1ClusterRoleBinding)

router.post('/apis/rbac.authorization.k8s.io/v1/clusterrolebindings', createRbacAuthorizationV1ClusterRoleBinding)

export default router;
