// Path: routes/ApisAutoscalingV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getAutoscalingV1APIResources } from '../controllers/AutoscalingV1Controller'

import {router} from './router';

router.get('/apis/autoscaling/v1/', getAutoscalingV1APIResources)

export default router;
