// Path: routes/ApisEvents.k8s.ioV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getEventsV1APIResources } from '../controllers/EventsV1Controller'

import {router} from './router';

router.get('/apis/events.k8s.io/v1/', getEventsV1APIResources)

export default router;
