// Path: routes/ApisBatchV1Namespaces{namespace}Jobs{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteBatchV1NamespacedJob } from '../controllers/BatchV1Controller'
import { readBatchV1NamespacedJob } from '../controllers/BatchV1Controller'
import { patchBatchV1NamespacedJob } from '../controllers/BatchV1Controller'
import { replaceBatchV1NamespacedJob } from '../controllers/BatchV1Controller'

import {router} from './router';

router.delete('/apis/batch/v1/namespaces/:namespace/jobs/:name', deleteBatchV1NamespacedJob)

router.get('/apis/batch/v1/namespaces/:namespace/jobs/:name', readBatchV1NamespacedJob)

router.patch('/apis/batch/v1/namespaces/:namespace/jobs/:name', patchBatchV1NamespacedJob)

router.put('/apis/batch/v1/namespaces/:namespace/jobs/:name', replaceBatchV1NamespacedJob)

export default router;
