// Path: routes/ApisApiextensions.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getApiextensionsAPIGroup } from '../controllers/ApiextensionsController'

import {router} from './router';

router.get('/apis/apiextensions.k8s.io/', getApiextensionsAPIGroup)

export default router;
