// Path: routes/ApisAdmissionregistration.k8s.ioV1WatchValidatingwebhookconfigurationsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAdmissionregistrationV1ValidatingWebhookConfigurationList } from '../controllers/AdmissionregistrationV1Controller'

import {router} from './router';

router.get('/apis/admissionregistration.k8s.io/v1/watch/validatingwebhookconfigurations', watchAdmissionregistrationV1ValidatingWebhookConfigurationList)

export default router;
