// Path: routes/ApisAppsV1Namespaces{namespace}Replicasets{name}ScaleRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readAppsV1NamespacedReplicaSetScale } from '../controllers/AppsV1Controller'
import { patchAppsV1NamespacedReplicaSetScale } from '../controllers/AppsV1Controller'
import { replaceAppsV1NamespacedReplicaSetScale } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/namespaces/:namespace/replicasets/:name/scale', readAppsV1NamespacedReplicaSetScale)

router.patch('/apis/apps/v1/namespaces/:namespace/replicasets/:name/scale', patchAppsV1NamespacedReplicaSetScale)

router.put('/apis/apps/v1/namespaces/:namespace/replicasets/:name/scale', replaceAppsV1NamespacedReplicaSetScale)

export default router;
