// Path: routes/ApisResource.k8s.ioV1alpha3DeviceclassesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteResourceV1alpha3CollectionDeviceClass } from '../controllers/ResourceV1alpha3Controller'
import { listResourceV1alpha3DeviceClass } from '../controllers/ResourceV1alpha3Controller'
import { createResourceV1alpha3DeviceClass } from '../controllers/ResourceV1alpha3Controller'

import {router} from './router';

router.delete('/apis/resource.k8s.io/v1alpha3/deviceclasses', deleteResourceV1alpha3CollectionDeviceClass)

router.get('/apis/resource.k8s.io/v1alpha3/deviceclasses', listResourceV1alpha3DeviceClass)

router.post('/apis/resource.k8s.io/v1alpha3/deviceclasses', createResourceV1alpha3DeviceClass)

export default router;
