// Path: routes/ApisNetworking.k8s.ioV1Namespaces{namespace}Networkpolicies{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNetworkingV1NamespacedNetworkPolicy } from '../controllers/NetworkingV1Controller'
import { readNetworkingV1NamespacedNetworkPolicy } from '../controllers/NetworkingV1Controller'
import { patchNetworkingV1NamespacedNetworkPolicy } from '../controllers/NetworkingV1Controller'
import { replaceNetworkingV1NamespacedNetworkPolicy } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.delete('/apis/networking.k8s.io/v1/namespaces/:namespace/networkpolicies/:name', deleteNetworkingV1NamespacedNetworkPolicy)

router.get('/apis/networking.k8s.io/v1/namespaces/:namespace/networkpolicies/:name', readNetworkingV1NamespacedNetworkPolicy)

router.patch('/apis/networking.k8s.io/v1/namespaces/:namespace/networkpolicies/:name', patchNetworkingV1NamespacedNetworkPolicy)

router.put('/apis/networking.k8s.io/v1/namespaces/:namespace/networkpolicies/:name', replaceNetworkingV1NamespacedNetworkPolicy)

export default router;
