// Path: routes/ApisStorage.k8s.ioV1Volumeattachments{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteStorageV1VolumeAttachment } from '../controllers/StorageV1Controller'
import { readStorageV1VolumeAttachment } from '../controllers/StorageV1Controller'
import { patchStorageV1VolumeAttachment } from '../controllers/StorageV1Controller'
import { replaceStorageV1VolumeAttachment } from '../controllers/StorageV1Controller'

import {router} from './router';

router.delete('/apis/storage.k8s.io/v1/volumeattachments/:name', deleteStorageV1VolumeAttachment)

router.get('/apis/storage.k8s.io/v1/volumeattachments/:name', readStorageV1VolumeAttachment)

router.patch('/apis/storage.k8s.io/v1/volumeattachments/:name', patchStorageV1VolumeAttachment)

router.put('/apis/storage.k8s.io/v1/volumeattachments/:name', replaceStorageV1VolumeAttachment)

export default router;
