// Path: routes/ApisAdmissionregistration.k8s.ioV1beta1ValidatingadmissionpoliciesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteAdmissionregistrationV1beta1CollectionValidatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1beta1Controller'
import { listAdmissionregistrationV1beta1ValidatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1beta1Controller'
import { createAdmissionregistrationV1beta1ValidatingAdmissionPolicy } from '../controllers/AdmissionregistrationV1beta1Controller'

import {router} from './router';

router.delete('/apis/admissionregistration.k8s.io/v1beta1/validatingadmissionpolicies', deleteAdmissionregistrationV1beta1CollectionValidatingAdmissionPolicy)

router.get('/apis/admissionregistration.k8s.io/v1beta1/validatingadmissionpolicies', listAdmissionregistrationV1beta1ValidatingAdmissionPolicy)

router.post('/apis/admissionregistration.k8s.io/v1beta1/validatingadmissionpolicies', createAdmissionregistrationV1beta1ValidatingAdmissionPolicy)

export default router;
