// Path: routes/ApisEvents.k8s.ioV1Namespaces{namespace}Events{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteEventsV1NamespacedEvent } from '../controllers/EventsV1Controller'
import { readEventsV1NamespacedEvent } from '../controllers/EventsV1Controller'
import { patchEventsV1NamespacedEvent } from '../controllers/EventsV1Controller'
import { replaceEventsV1NamespacedEvent } from '../controllers/EventsV1Controller'

import {router} from './router';

router.delete('/apis/events.k8s.io/v1/namespaces/:namespace/events/:name', deleteEventsV1NamespacedEvent)

router.get('/apis/events.k8s.io/v1/namespaces/:namespace/events/:name', readEventsV1NamespacedEvent)

router.patch('/apis/events.k8s.io/v1/namespaces/:namespace/events/:name', patchEventsV1NamespacedEvent)

router.put('/apis/events.k8s.io/v1/namespaces/:namespace/events/:name', replaceEventsV1NamespacedEvent)

export default router;
