// Path: routes/ApisNetworking.k8s.ioV1IngressclassesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNetworkingV1CollectionIngressClass } from '../controllers/NetworkingV1Controller'
import { listNetworkingV1IngressClass } from '../controllers/NetworkingV1Controller'
import { createNetworkingV1IngressClass } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.delete('/apis/networking.k8s.io/v1/ingressclasses', deleteNetworkingV1CollectionIngressClass)

router.get('/apis/networking.k8s.io/v1/ingressclasses', listNetworkingV1IngressClass)

router.post('/apis/networking.k8s.io/v1/ingressclasses', createNetworkingV1IngressClass)

export default router;
