// Path: routes/ApisNetworking.k8s.ioV1Ingressclasses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteNetworkingV1IngressClass } from '../controllers/NetworkingV1Controller'
import { readNetworkingV1IngressClass } from '../controllers/NetworkingV1Controller'
import { patchNetworkingV1IngressClass } from '../controllers/NetworkingV1Controller'
import { replaceNetworkingV1IngressClass } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.delete('/apis/networking.k8s.io/v1/ingressclasses/:name', deleteNetworkingV1IngressClass)

router.get('/apis/networking.k8s.io/v1/ingressclasses/:name', readNetworkingV1IngressClass)

router.patch('/apis/networking.k8s.io/v1/ingressclasses/:name', patchNetworkingV1IngressClass)

router.put('/apis/networking.k8s.io/v1/ingressclasses/:name', replaceNetworkingV1IngressClass)

export default router;
