// Path: routes/ApisNetworking.k8s.ioV1WatchIpaddressesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchNetworkingV1IPAddressList } from '../controllers/NetworkingV1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1/watch/ipaddresses', watchNetworkingV1IPAddressList)

export default router;
