// Path: routes/ApisStorage.k8s.ioV1Namespaces{namespace}CsistoragecapacitiesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteStorageV1CollectionNamespacedCSIStorageCapacity } from '../controllers/StorageV1Controller'
import { listStorageV1NamespacedCSIStorageCapacity } from '../controllers/StorageV1Controller'
import { createStorageV1NamespacedCSIStorageCapacity } from '../controllers/StorageV1Controller'

import {router} from './router';

router.delete('/apis/storage.k8s.io/v1/namespaces/:namespace/csistoragecapacities', deleteStorageV1CollectionNamespacedCSIStorageCapacity)

router.get('/apis/storage.k8s.io/v1/namespaces/:namespace/csistoragecapacities', listStorageV1NamespacedCSIStorageCapacity)

router.post('/apis/storage.k8s.io/v1/namespaces/:namespace/csistoragecapacities', createStorageV1NamespacedCSIStorageCapacity)

export default router;
