// Path: routes/ApisFlowcontrol.apiserver.k8s.ioV1WatchPrioritylevelconfigurationsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchFlowcontrolApiserverV1PriorityLevelConfigurationList } from '../controllers/FlowcontrolApiserverV1Controller'

import {router} from './router';

router.get('/apis/flowcontrol.apiserver.k8s.io/v1/watch/prioritylevelconfigurations', watchFlowcontrolApiserverV1PriorityLevelConfigurationList)

export default router;
