// Path: routes/ApisStorage.k8s.ioV1WatchStorageclassesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchStorageV1StorageClassList } from '../controllers/StorageV1Controller'

import {router} from './router';

router.get('/apis/storage.k8s.io/v1/watch/storageclasses', watchStorageV1StorageClassList)

export default router;
