// Path: routes/ApisFlowcontrol.apiserver.k8s.ioV1WatchPrioritylevelconfigurations{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchFlowcontrolApiserverV1PriorityLevelConfiguration } from '../controllers/FlowcontrolApiserverV1Controller'

import {router} from './router';

router.get('/apis/flowcontrol.apiserver.k8s.io/v1/watch/prioritylevelconfigurations/:name', watchFlowcontrolApiserverV1PriorityLevelConfiguration)

export default router;
