// Path: routes/ApisAppsV1DaemonsetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listAppsV1DaemonSetForAllNamespaces } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/daemonsets', listAppsV1DaemonSetForAllNamespaces)

export default router;
