// Path: routes/ApisBatchV1Namespaces{namespace}JobsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteBatchV1CollectionNamespacedJob } from '../controllers/BatchV1Controller'
import { listBatchV1NamespacedJob } from '../controllers/BatchV1Controller'
import { createBatchV1NamespacedJob } from '../controllers/BatchV1Controller'

import {router} from './router';

router.delete('/apis/batch/v1/namespaces/:namespace/jobs', deleteBatchV1CollectionNamespacedJob)

router.get('/apis/batch/v1/namespaces/:namespace/jobs', listBatchV1NamespacedJob)

router.post('/apis/batch/v1/namespaces/:namespace/jobs', createBatchV1NamespacedJob)

export default router;
