// Path: routes/ApisRbac.authorization.k8s.ioV1RolebindingsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listRbacAuthorizationV1RoleBindingForAllNamespaces } from '../controllers/RbacAuthorizationV1Controller'

import {router} from './router';

router.get('/apis/rbac.authorization.k8s.io/v1/rolebindings', listRbacAuthorizationV1RoleBindingForAllNamespaces)

export default router;
