// Path: routes/ApisAutoscalingV2WatchNamespaces{namespace}Horizontalpodautoscalers{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchAutoscalingV2NamespacedHorizontalPodAutoscaler } from '../controllers/AutoscalingV2Controller'

import {router} from './router';

router.get('/apis/autoscaling/v2/watch/namespaces/:namespace/horizontalpodautoscalers/:name', watchAutoscalingV2NamespacedHorizontalPodAutoscaler)

export default router;
