// Path: routes/ApisAdmissionregistration.k8s.ioV1Validatingadmissionpolicies{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readAdmissionregistrationV1ValidatingAdmissionPolicyStatus } from '../controllers/AdmissionregistrationV1Controller'
import { patchAdmissionregistrationV1ValidatingAdmissionPolicyStatus } from '../controllers/AdmissionregistrationV1Controller'
import { replaceAdmissionregistrationV1ValidatingAdmissionPolicyStatus } from '../controllers/AdmissionregistrationV1Controller'

import {router} from './router';

router.get('/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies/:name/status', readAdmissionregistrationV1ValidatingAdmissionPolicyStatus)

router.patch('/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies/:name/status', patchAdmissionregistrationV1ValidatingAdmissionPolicyStatus)

router.put('/apis/admissionregistration.k8s.io/v1/validatingadmissionpolicies/:name/status', replaceAdmissionregistrationV1ValidatingAdmissionPolicyStatus)

export default router;
