// Path: routes/ApisNetworking.k8s.ioV1beta1Servicecidrs{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readNetworkingV1beta1ServiceCIDRStatus } from '../controllers/NetworkingV1beta1Controller'
import { patchNetworkingV1beta1ServiceCIDRStatus } from '../controllers/NetworkingV1beta1Controller'
import { replaceNetworkingV1beta1ServiceCIDRStatus } from '../controllers/NetworkingV1beta1Controller'

import {router} from './router';

router.get('/apis/networking.k8s.io/v1beta1/servicecidrs/:name/status', readNetworkingV1beta1ServiceCIDRStatus)

router.patch('/apis/networking.k8s.io/v1beta1/servicecidrs/:name/status', patchNetworkingV1beta1ServiceCIDRStatus)

router.put('/apis/networking.k8s.io/v1beta1/servicecidrs/:name/status', replaceNetworkingV1beta1ServiceCIDRStatus)

export default router;
