// Path: routes/ApisAuthorization.k8s.ioV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getAuthorizationV1APIResources } from '../controllers/AuthorizationV1Controller'

import {router} from './router';

router.get('/apis/authorization.k8s.io/v1/', getAuthorizationV1APIResources)

export default router;
