// Path: routes/ApisAdmissionregistration.k8s.ioV1beta1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getAdmissionregistrationV1beta1APIResources } from '../controllers/AdmissionregistrationV1beta1Controller'

import {router} from './router';

router.get('/apis/admissionregistration.k8s.io/v1beta1/', getAdmissionregistrationV1beta1APIResources)

export default router;
