// Path: routes/ApisAppsV1StatefulsetsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listAppsV1StatefulSetForAllNamespaces } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/statefulsets', listAppsV1StatefulSetForAllNamespaces)

export default router;
