// Path: routes/ApisBatchV1CronjobsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listBatchV1CronJobForAllNamespaces } from '../controllers/BatchV1Controller'

import {router} from './router';

router.get('/apis/batch/v1/cronjobs', listBatchV1CronJobForAllNamespaces)

export default router;
