// Path: routes/ApisStorage.k8s.ioV1CsinodesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteStorageV1CollectionCSINode } from '../controllers/StorageV1Controller'
import { listStorageV1CSINode } from '../controllers/StorageV1Controller'
import { createStorageV1CSINode } from '../controllers/StorageV1Controller'

import {router} from './router';

router.delete('/apis/storage.k8s.io/v1/csinodes', deleteStorageV1CollectionCSINode)

router.get('/apis/storage.k8s.io/v1/csinodes', listStorageV1CSINode)

router.post('/apis/storage.k8s.io/v1/csinodes', createStorageV1CSINode)

export default router;
