// Path: routes/ApisBatchV1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getBatchV1APIResources } from '../controllers/BatchV1Controller'

import {router} from './router';

router.get('/apis/batch/v1/', getBatchV1APIResources)

export default router;
