// Path: routes/ApisApiregistration.k8s.ioV1Apiservices{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readApiregistrationV1APIServiceStatus } from '../controllers/ApiregistrationV1Controller'
import { patchApiregistrationV1APIServiceStatus } from '../controllers/ApiregistrationV1Controller'
import { replaceApiregistrationV1APIServiceStatus } from '../controllers/ApiregistrationV1Controller'

import {router} from './router';

router.get('/apis/apiregistration.k8s.io/v1/apiservices/:name/status', readApiregistrationV1APIServiceStatus)

router.patch('/apis/apiregistration.k8s.io/v1/apiservices/:name/status', patchApiregistrationV1APIServiceStatus)

router.put('/apis/apiregistration.k8s.io/v1/apiservices/:name/status', replaceApiregistrationV1APIServiceStatus)

export default router;
