// Path: routes/ApisResource.k8s.ioV1alpha3ResourceclaimtemplatesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listResourceV1alpha3ResourceClaimTemplateForAllNamespaces } from '../controllers/ResourceV1alpha3Controller'

import {router} from './router';

router.get('/apis/resource.k8s.io/v1alpha3/resourceclaimtemplates', listResourceV1alpha3ResourceClaimTemplateForAllNamespaces)

export default router;
