// Path: routes/ApisCertificates.k8s.ioRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getCertificatesAPIGroup } from '../controllers/CertificatesController'

import {router} from './router';

router.get('/apis/certificates.k8s.io/', getCertificatesAPIGroup)

export default router;
