// Path: routes/ApisAppsV1ControllerrevisionsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listAppsV1ControllerRevisionForAllNamespaces } from '../controllers/AppsV1Controller'

import {router} from './router';

router.get('/apis/apps/v1/controllerrevisions', listAppsV1ControllerRevisionForAllNamespaces)

export default router;
