// Path: routes/ApisStoragemigration.k8s.ioV1alpha1Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getStoragemigrationV1alpha1APIResources } from '../controllers/StoragemigrationV1alpha1Controller'

import {router} from './router';

router.get('/apis/storagemigration.k8s.io/v1alpha1/', getStoragemigrationV1alpha1APIResources)

export default router;
