// Path: routes/LogsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { logFileListHandler } from '../controllers/LogsController'

import {router} from './router';

router.get('/logs/', logFileListHandler)

export default router;
