// Path: routes/OpenidV1JwksRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getServiceAccountIssuerOpenIDKeyset } from '../controllers/OpenidController'

import {router} from './router';

router.get('/openid/v1/jwks/', getServiceAccountIssuerOpenIDKeyset)

export default router;
