// Path: routes/Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getCoreAPIVersions } from '../controllers/CoreController'

import { router } from './router';

router.get('/api/', getCoreAPIVersions)

export default router;
