// Path: routes/V1Componentstatuses{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readCoreV1ComponentStatus } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/componentstatuses/:name', readCoreV1ComponentStatus)

export default router;
