// Path: routes/V1ConfigmapsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listCoreV1ConfigMapForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/configmaps', listCoreV1ConfigMapForAllNamespaces)

export default router;
