// Path: routes/V1EndpointsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listCoreV1EndpointsForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/endpoints', listCoreV1EndpointsForAllNamespaces)

export default router;
