// Path: routes/V1EventsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listCoreV1EventForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/events', listCoreV1EventForAllNamespaces)

export default router;
