// Path: routes/V1LimitrangesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listCoreV1LimitRangeForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/limitranges', listCoreV1LimitRangeForAllNamespaces)

export default router;
