// Path: routes/V1Namespaces{namespace}Pods{name}PortforwardRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { connectCoreV1GetNamespacedPodPortforward } from '../controllers/CoreV1Controller'
import { connectCoreV1PostNamespacedPodPortforward } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/namespaces/:namespace/pods/:name/portforward', connectCoreV1GetNamespacedPodPortforward)

router.post('/api/v1/namespaces/:namespace/pods/:name/portforward', connectCoreV1PostNamespacedPodPortforward)

export default router;
