// Path: routes/V1Namespaces{namespace}Pods{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readCoreV1NamespacedPodStatus } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedPodStatus } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedPodStatus } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/namespaces/:namespace/pods/:name/status', readCoreV1NamespacedPodStatus)

router.patch('/api/v1/namespaces/:namespace/pods/:name/status', patchCoreV1NamespacedPodStatus)

router.put('/api/v1/namespaces/:namespace/pods/:name/status', replaceCoreV1NamespacedPodStatus)

export default router;
