// Path: routes/V1Namespaces{namespace}Pods{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1NamespacedPod } from '../controllers/CoreV1Controller'
import { readCoreV1NamespacedPod } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedPod } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedPod } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/pods/:name', deleteCoreV1NamespacedPod)

router.get('/api/v1/namespaces/:namespace/pods/:name', readCoreV1NamespacedPod)

router.patch('/api/v1/namespaces/:namespace/pods/:name', patchCoreV1NamespacedPod)

router.put('/api/v1/namespaces/:namespace/pods/:name', replaceCoreV1NamespacedPod)

export default router;
