// Path: routes/V1Namespaces{namespace}Pods{name}Proxy{path}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { connectCoreV1DeleteNamespacedPodProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1GetNamespacedPodProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1HeadNamespacedPodProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1OptionsNamespacedPodProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1PatchNamespacedPodProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1PostNamespacedPodProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1PutNamespacedPodProxyWithPath } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/pods/:name/proxy/:path', connectCoreV1DeleteNamespacedPodProxyWithPath)

router.get('/api/v1/namespaces/:namespace/pods/:name/proxy/:path', connectCoreV1GetNamespacedPodProxyWithPath)

router.head('/api/v1/namespaces/:namespace/pods/:name/proxy/:path', connectCoreV1HeadNamespacedPodProxyWithPath)

router.options('/api/v1/namespaces/:namespace/pods/:name/proxy/:path', connectCoreV1OptionsNamespacedPodProxyWithPath)

router.patch('/api/v1/namespaces/:namespace/pods/:name/proxy/:path', connectCoreV1PatchNamespacedPodProxyWithPath)

router.post('/api/v1/namespaces/:namespace/pods/:name/proxy/:path', connectCoreV1PostNamespacedPodProxyWithPath)

router.put('/api/v1/namespaces/:namespace/pods/:name/proxy/:path', connectCoreV1PutNamespacedPodProxyWithPath)

export default router;
