// Path: routes/V1Namespaces{namespace}Pods{name}LogRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readCoreV1NamespacedPodLog } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/namespaces/:namespace/pods/:name/log', readCoreV1NamespacedPodLog)

export default router;
