// Path: routes/V1Namespaces{namespace}Pods{name}AttachRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { connectCoreV1GetNamespacedPodAttach } from '../controllers/CoreV1Controller'
import { connectCoreV1PostNamespacedPodAttach } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/namespaces/:namespace/pods/:name/attach', connectCoreV1GetNamespacedPodAttach)

router.post('/api/v1/namespaces/:namespace/pods/:name/attach', connectCoreV1PostNamespacedPodAttach)

export default router;
