// Path: routes/V1Namespaces{namespace}Serviceaccounts{name}TokenRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { createCoreV1NamespacedServiceAccountToken } from '../controllers/CoreV1Controller'

import {router} from './router';

router.post('/api/v1/namespaces/:namespace/serviceaccounts/:name/token', createCoreV1NamespacedServiceAccountToken)

export default router;
