// Path: routes/V1Namespaces{namespace}Serviceaccounts{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1NamespacedServiceAccount } from '../controllers/CoreV1Controller'
import { readCoreV1NamespacedServiceAccount } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedServiceAccount } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedServiceAccount } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/serviceaccounts/:name', deleteCoreV1NamespacedServiceAccount)

router.get('/api/v1/namespaces/:namespace/serviceaccounts/:name', readCoreV1NamespacedServiceAccount)

router.patch('/api/v1/namespaces/:namespace/serviceaccounts/:name', patchCoreV1NamespacedServiceAccount)

router.put('/api/v1/namespaces/:namespace/serviceaccounts/:name', replaceCoreV1NamespacedServiceAccount)

export default router;
