// Path: routes/V1Namespaces{namespace}Replicationcontrollers{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readCoreV1NamespacedReplicationControllerStatus } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedReplicationControllerStatus } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedReplicationControllerStatus } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/namespaces/:namespace/replicationcontrollers/:name/status', readCoreV1NamespacedReplicationControllerStatus)

router.patch('/api/v1/namespaces/:namespace/replicationcontrollers/:name/status', patchCoreV1NamespacedReplicationControllerStatus)

router.put('/api/v1/namespaces/:namespace/replicationcontrollers/:name/status', replaceCoreV1NamespacedReplicationControllerStatus)

export default router;
