// Path: routes/V1Namespaces{namespace}Pods{name}EvictionRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { createCoreV1NamespacedPodEviction } from '../controllers/CoreV1Controller'

import {router} from './router';

router.post('/api/v1/namespaces/:namespace/pods/:name/eviction', createCoreV1NamespacedPodEviction)

export default router;
