// Path: routes/V1Namespaces{namespace}Pods{name}BindingRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { createCoreV1NamespacedPodBinding } from '../controllers/CoreV1Controller'

import {router} from './router';

router.post('/api/v1/namespaces/:namespace/pods/:name/binding', createCoreV1NamespacedPodBinding)

export default router;
