// Path: routes/V1Namespaces{namespace}ResourcequotasRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1CollectionNamespacedResourceQuota } from '../controllers/CoreV1Controller'
import { listCoreV1NamespacedResourceQuota } from '../controllers/CoreV1Controller'
import { createCoreV1NamespacedResourceQuota } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/resourcequotas', deleteCoreV1CollectionNamespacedResourceQuota)

router.get('/api/v1/namespaces/:namespace/resourcequotas', listCoreV1NamespacedResourceQuota)

router.post('/api/v1/namespaces/:namespace/resourcequotas', createCoreV1NamespacedResourceQuota)

export default router;
