// Path: routes/V1Namespaces{namespace}Secrets{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1NamespacedSecret } from '../controllers/CoreV1Controller'
import { readCoreV1NamespacedSecret } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedSecret } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedSecret } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/secrets/:name', deleteCoreV1NamespacedSecret)

router.get('/api/v1/namespaces/:namespace/secrets/:name', readCoreV1NamespacedSecret)

router.patch('/api/v1/namespaces/:namespace/secrets/:name', patchCoreV1NamespacedSecret)

router.put('/api/v1/namespaces/:namespace/secrets/:name', replaceCoreV1NamespacedSecret)

export default router;
