// Path: routes/V1Namespaces{namespace}Resourcequotas{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1NamespacedResourceQuota } from '../controllers/CoreV1Controller'
import { readCoreV1NamespacedResourceQuota } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedResourceQuota } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedResourceQuota } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/resourcequotas/:name', deleteCoreV1NamespacedResourceQuota)

router.get('/api/v1/namespaces/:namespace/resourcequotas/:name', readCoreV1NamespacedResourceQuota)

router.patch('/api/v1/namespaces/:namespace/resourcequotas/:name', patchCoreV1NamespacedResourceQuota)

router.put('/api/v1/namespaces/:namespace/resourcequotas/:name', replaceCoreV1NamespacedResourceQuota)

export default router;
