// Path: routes/V1Namespaces{namespace}ReplicationcontrollersRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1CollectionNamespacedReplicationController } from '../controllers/CoreV1Controller'
import { listCoreV1NamespacedReplicationController } from '../controllers/CoreV1Controller'
import { createCoreV1NamespacedReplicationController } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/replicationcontrollers', deleteCoreV1CollectionNamespacedReplicationController)

router.get('/api/v1/namespaces/:namespace/replicationcontrollers', listCoreV1NamespacedReplicationController)

router.post('/api/v1/namespaces/:namespace/replicationcontrollers', createCoreV1NamespacedReplicationController)

export default router;
