// Path: routes/V1NamespacesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listCoreV1Namespace } from '../controllers/CoreV1Controller'
import { createCoreV1Namespace } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/namespaces', listCoreV1Namespace)

router.post('/api/v1/namespaces', createCoreV1Namespace)

export default router;
