// Path: routes/V1Namespaces{namespace}Events{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1NamespacedEvent } from '../controllers/CoreV1Controller'
import { readCoreV1NamespacedEvent } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedEvent } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedEvent } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/events/:name', deleteCoreV1NamespacedEvent)

router.get('/api/v1/namespaces/:namespace/events/:name', readCoreV1NamespacedEvent)

router.patch('/api/v1/namespaces/:namespace/events/:name', patchCoreV1NamespacedEvent)

router.put('/api/v1/namespaces/:namespace/events/:name', replaceCoreV1NamespacedEvent)

export default router;
