// Path: routes/V1Namespaces{namespace}Pods{name}ResizeRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readCoreV1NamespacedPodResize } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedPodResize } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedPodResize } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/namespaces/:namespace/pods/:name/resize', readCoreV1NamespacedPodResize)

router.patch('/api/v1/namespaces/:namespace/pods/:name/resize', patchCoreV1NamespacedPodResize)

router.put('/api/v1/namespaces/:namespace/pods/:name/resize', replaceCoreV1NamespacedPodResize)

export default router;
