// Path: routes/V1Namespaces{namespace}Services{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1NamespacedService } from '../controllers/CoreV1Controller'
import { readCoreV1NamespacedService } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedService } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedService } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/services/:name', deleteCoreV1NamespacedService)

router.get('/api/v1/namespaces/:namespace/services/:name', readCoreV1NamespacedService)

router.patch('/api/v1/namespaces/:namespace/services/:name', patchCoreV1NamespacedService)

router.put('/api/v1/namespaces/:namespace/services/:name', replaceCoreV1NamespacedService)

export default router;
