// Path: routes/V1Namespaces{namespace}Limitranges{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1NamespacedLimitRange } from '../controllers/CoreV1Controller'
import { readCoreV1NamespacedLimitRange } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedLimitRange } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedLimitRange } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/limitranges/:name', deleteCoreV1NamespacedLimitRange)

router.get('/api/v1/namespaces/:namespace/limitranges/:name', readCoreV1NamespacedLimitRange)

router.patch('/api/v1/namespaces/:namespace/limitranges/:name', patchCoreV1NamespacedLimitRange)

router.put('/api/v1/namespaces/:namespace/limitranges/:name', replaceCoreV1NamespacedLimitRange)

export default router;
