// Path: routes/V1Namespaces{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readCoreV1NamespaceStatus } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespaceStatus } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespaceStatus } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/namespaces/:name/status', readCoreV1NamespaceStatus)

router.patch('/api/v1/namespaces/:name/status', patchCoreV1NamespaceStatus)

router.put('/api/v1/namespaces/:name/status', replaceCoreV1NamespaceStatus)

export default router;
