// Path: routes/V1Namespaces{namespace}Persistentvolumeclaims{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readCoreV1NamespacedPersistentVolumeClaimStatus } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedPersistentVolumeClaimStatus } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedPersistentVolumeClaimStatus } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/namespaces/:namespace/persistentvolumeclaims/:name/status', readCoreV1NamespacedPersistentVolumeClaimStatus)

router.patch('/api/v1/namespaces/:namespace/persistentvolumeclaims/:name/status', patchCoreV1NamespacedPersistentVolumeClaimStatus)

router.put('/api/v1/namespaces/:namespace/persistentvolumeclaims/:name/status', replaceCoreV1NamespacedPersistentVolumeClaimStatus)

export default router;
