// Path: routes/V1Namespaces{namespace}PodtemplatesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1CollectionNamespacedPodTemplate } from '../controllers/CoreV1Controller'
import { listCoreV1NamespacedPodTemplate } from '../controllers/CoreV1Controller'
import { createCoreV1NamespacedPodTemplate } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/podtemplates', deleteCoreV1CollectionNamespacedPodTemplate)

router.get('/api/v1/namespaces/:namespace/podtemplates', listCoreV1NamespacedPodTemplate)

router.post('/api/v1/namespaces/:namespace/podtemplates', createCoreV1NamespacedPodTemplate)

export default router;
