// Path: routes/V1Namespaces{namespace}EndpointsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1CollectionNamespacedEndpoints } from '../controllers/CoreV1Controller'
import { listCoreV1NamespacedEndpoints } from '../controllers/CoreV1Controller'
import { createCoreV1NamespacedEndpoints } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/endpoints', deleteCoreV1CollectionNamespacedEndpoints)

router.get('/api/v1/namespaces/:namespace/endpoints', listCoreV1NamespacedEndpoints)

router.post('/api/v1/namespaces/:namespace/endpoints', createCoreV1NamespacedEndpoints)

export default router;
