// Path: routes/V1Namespaces{namespace}Persistentvolumeclaims{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1NamespacedPersistentVolumeClaim } from '../controllers/CoreV1Controller'
import { readCoreV1NamespacedPersistentVolumeClaim } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedPersistentVolumeClaim } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedPersistentVolumeClaim } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/persistentvolumeclaims/:name', deleteCoreV1NamespacedPersistentVolumeClaim)

router.get('/api/v1/namespaces/:namespace/persistentvolumeclaims/:name', readCoreV1NamespacedPersistentVolumeClaim)

router.patch('/api/v1/namespaces/:namespace/persistentvolumeclaims/:name', patchCoreV1NamespacedPersistentVolumeClaim)

router.put('/api/v1/namespaces/:namespace/persistentvolumeclaims/:name', replaceCoreV1NamespacedPersistentVolumeClaim)

export default router;
