// Path: routes/V1Namespaces{namespace}Pods{name}ExecRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { connectCoreV1GetNamespacedPodExec } from '../controllers/CoreV1Controller'
import { connectCoreV1PostNamespacedPodExec } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/namespaces/:namespace/pods/:name/exec', connectCoreV1GetNamespacedPodExec)

router.post('/api/v1/namespaces/:namespace/pods/:name/exec', connectCoreV1PostNamespacedPodExec)

export default router;
