// Path: routes/V1Namespaces{namespace}BindingsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { createCoreV1NamespacedBinding } from '../controllers/CoreV1Controller'

import {router} from './router';

router.post('/api/v1/namespaces/:namespace/bindings', createCoreV1NamespacedBinding)

export default router;
