// Path: routes/V1Namespaces{namespace}ServiceaccountsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1CollectionNamespacedServiceAccount } from '../controllers/CoreV1Controller'
import { listCoreV1NamespacedServiceAccount } from '../controllers/CoreV1Controller'
import { createCoreV1NamespacedServiceAccount } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/serviceaccounts', deleteCoreV1CollectionNamespacedServiceAccount)

router.get('/api/v1/namespaces/:namespace/serviceaccounts', listCoreV1NamespacedServiceAccount)

router.post('/api/v1/namespaces/:namespace/serviceaccounts', createCoreV1NamespacedServiceAccount)

export default router;
