// Path: routes/V1Namespaces{namespace}Podtemplates{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1NamespacedPodTemplate } from '../controllers/CoreV1Controller'
import { readCoreV1NamespacedPodTemplate } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedPodTemplate } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedPodTemplate } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/podtemplates/:name', deleteCoreV1NamespacedPodTemplate)

router.get('/api/v1/namespaces/:namespace/podtemplates/:name', readCoreV1NamespacedPodTemplate)

router.patch('/api/v1/namespaces/:namespace/podtemplates/:name', patchCoreV1NamespacedPodTemplate)

router.put('/api/v1/namespaces/:namespace/podtemplates/:name', replaceCoreV1NamespacedPodTemplate)

export default router;
