// Path: routes/V1Namespaces{namespace}Pods{name}ProxyRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { connectCoreV1DeleteNamespacedPodProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1GetNamespacedPodProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1HeadNamespacedPodProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1OptionsNamespacedPodProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1PatchNamespacedPodProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1PostNamespacedPodProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1PutNamespacedPodProxy } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/pods/:name/proxy', connectCoreV1DeleteNamespacedPodProxy)

router.get('/api/v1/namespaces/:namespace/pods/:name/proxy', connectCoreV1GetNamespacedPodProxy)

router.head('/api/v1/namespaces/:namespace/pods/:name/proxy', connectCoreV1HeadNamespacedPodProxy)

router.options('/api/v1/namespaces/:namespace/pods/:name/proxy', connectCoreV1OptionsNamespacedPodProxy)

router.patch('/api/v1/namespaces/:namespace/pods/:name/proxy', connectCoreV1PatchNamespacedPodProxy)

router.post('/api/v1/namespaces/:namespace/pods/:name/proxy', connectCoreV1PostNamespacedPodProxy)

router.put('/api/v1/namespaces/:namespace/pods/:name/proxy', connectCoreV1PutNamespacedPodProxy)

export default router;
