// Path: routes/V1Namespaces{namespace}Services{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readCoreV1NamespacedServiceStatus } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedServiceStatus } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedServiceStatus } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/namespaces/:namespace/services/:name/status', readCoreV1NamespacedServiceStatus)

router.patch('/api/v1/namespaces/:namespace/services/:name/status', patchCoreV1NamespacedServiceStatus)

router.put('/api/v1/namespaces/:namespace/services/:name/status', replaceCoreV1NamespacedServiceStatus)

export default router;
