// Path: routes/V1Namespaces{namespace}ServicesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1CollectionNamespacedService } from '../controllers/CoreV1Controller'
import { listCoreV1NamespacedService } from '../controllers/CoreV1Controller'
import { createCoreV1NamespacedService } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/services', deleteCoreV1CollectionNamespacedService)

router.get('/api/v1/namespaces/:namespace/services', listCoreV1NamespacedService)

router.post('/api/v1/namespaces/:namespace/services', createCoreV1NamespacedService)

export default router;
