// Path: routes/V1Namespaces{namespace}EventsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1CollectionNamespacedEvent } from '../controllers/CoreV1Controller'
import { listCoreV1NamespacedEvent } from '../controllers/CoreV1Controller'
import { createCoreV1NamespacedEvent } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/events', deleteCoreV1CollectionNamespacedEvent)

router.get('/api/v1/namespaces/:namespace/events', listCoreV1NamespacedEvent)

router.post('/api/v1/namespaces/:namespace/events', createCoreV1NamespacedEvent)

export default router;
