// Path: routes/V1Namespaces{namespace}Pods{name}EphemeralcontainersRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readCoreV1NamespacedPodEphemeralcontainers } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedPodEphemeralcontainers } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedPodEphemeralcontainers } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/namespaces/:namespace/pods/:name/ephemeralcontainers', readCoreV1NamespacedPodEphemeralcontainers)

router.patch('/api/v1/namespaces/:namespace/pods/:name/ephemeralcontainers', patchCoreV1NamespacedPodEphemeralcontainers)

router.put('/api/v1/namespaces/:namespace/pods/:name/ephemeralcontainers', replaceCoreV1NamespacedPodEphemeralcontainers)

export default router;
