// Path: routes/V1Namespaces{namespace}PersistentvolumeclaimsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1CollectionNamespacedPersistentVolumeClaim } from '../controllers/CoreV1Controller'
import { listCoreV1NamespacedPersistentVolumeClaim } from '../controllers/CoreV1Controller'
import { createCoreV1NamespacedPersistentVolumeClaim } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/persistentvolumeclaims', deleteCoreV1CollectionNamespacedPersistentVolumeClaim)

router.get('/api/v1/namespaces/:namespace/persistentvolumeclaims', listCoreV1NamespacedPersistentVolumeClaim)

router.post('/api/v1/namespaces/:namespace/persistentvolumeclaims', createCoreV1NamespacedPersistentVolumeClaim)

export default router;
