// Path: routes/V1Namespaces{name}FinalizeRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { replaceCoreV1NamespaceFinalize } from '../controllers/CoreV1Controller'

import {router} from './router';

router.put('/api/v1/namespaces/:name/finalize', replaceCoreV1NamespaceFinalize)

export default router;
