// Path: routes/V1Namespaces{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1Namespace } from '../controllers/CoreV1Controller'
import { readCoreV1Namespace } from '../controllers/CoreV1Controller'
import { patchCoreV1Namespace } from '../controllers/CoreV1Controller'
import { replaceCoreV1Namespace } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:name', deleteCoreV1Namespace)

router.get('/api/v1/namespaces/:name', readCoreV1Namespace)

router.patch('/api/v1/namespaces/:name', patchCoreV1Namespace)

router.put('/api/v1/namespaces/:name', replaceCoreV1Namespace)

export default router;
