// Path: routes/V1Namespaces{namespace}Replicationcontrollers{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1NamespacedReplicationController } from '../controllers/CoreV1Controller'
import { readCoreV1NamespacedReplicationController } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedReplicationController } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedReplicationController } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/replicationcontrollers/:name', deleteCoreV1NamespacedReplicationController)

router.get('/api/v1/namespaces/:namespace/replicationcontrollers/:name', readCoreV1NamespacedReplicationController)

router.patch('/api/v1/namespaces/:namespace/replicationcontrollers/:name', patchCoreV1NamespacedReplicationController)

router.put('/api/v1/namespaces/:namespace/replicationcontrollers/:name', replaceCoreV1NamespacedReplicationController)

export default router;
