// Path: routes/V1Namespaces{namespace}Configmaps{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1NamespacedConfigMap } from '../controllers/CoreV1Controller'
import { readCoreV1NamespacedConfigMap } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedConfigMap } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedConfigMap } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/configmaps/:name', deleteCoreV1NamespacedConfigMap)

router.get('/api/v1/namespaces/:namespace/configmaps/:name', readCoreV1NamespacedConfigMap)

router.patch('/api/v1/namespaces/:namespace/configmaps/:name', patchCoreV1NamespacedConfigMap)

router.put('/api/v1/namespaces/:namespace/configmaps/:name', replaceCoreV1NamespacedConfigMap)

export default router;
