// Path: routes/V1Namespaces{namespace}Endpoints{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1NamespacedEndpoints } from '../controllers/CoreV1Controller'
import { readCoreV1NamespacedEndpoints } from '../controllers/CoreV1Controller'
import { patchCoreV1NamespacedEndpoints } from '../controllers/CoreV1Controller'
import { replaceCoreV1NamespacedEndpoints } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/endpoints/:name', deleteCoreV1NamespacedEndpoints)

router.get('/api/v1/namespaces/:namespace/endpoints/:name', readCoreV1NamespacedEndpoints)

router.patch('/api/v1/namespaces/:namespace/endpoints/:name', patchCoreV1NamespacedEndpoints)

router.put('/api/v1/namespaces/:namespace/endpoints/:name', replaceCoreV1NamespacedEndpoints)

export default router;
