// Path: routes/V1Namespaces{namespace}PodsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1CollectionNamespacedPod } from '../controllers/CoreV1Controller'
import { listCoreV1NamespacedPod } from '../controllers/CoreV1Controller'
import { createCoreV1NamespacedPod } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/pods', deleteCoreV1CollectionNamespacedPod)

router.get('/api/v1/namespaces/:namespace/pods', listCoreV1NamespacedPod)

router.post('/api/v1/namespaces/:namespace/pods', createCoreV1NamespacedPod)

export default router;
