// Path: routes/V1Namespaces{namespace}Services{name}Proxy{path}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { connectCoreV1DeleteNamespacedServiceProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1GetNamespacedServiceProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1HeadNamespacedServiceProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1OptionsNamespacedServiceProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1PatchNamespacedServiceProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1PostNamespacedServiceProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1PutNamespacedServiceProxyWithPath } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/services/:name/proxy/:path', connectCoreV1DeleteNamespacedServiceProxyWithPath)

router.get('/api/v1/namespaces/:namespace/services/:name/proxy/:path', connectCoreV1GetNamespacedServiceProxyWithPath)

router.head('/api/v1/namespaces/:namespace/services/:name/proxy/:path', connectCoreV1HeadNamespacedServiceProxyWithPath)

router.options('/api/v1/namespaces/:namespace/services/:name/proxy/:path', connectCoreV1OptionsNamespacedServiceProxyWithPath)

router.patch('/api/v1/namespaces/:namespace/services/:name/proxy/:path', connectCoreV1PatchNamespacedServiceProxyWithPath)

router.post('/api/v1/namespaces/:namespace/services/:name/proxy/:path', connectCoreV1PostNamespacedServiceProxyWithPath)

router.put('/api/v1/namespaces/:namespace/services/:name/proxy/:path', connectCoreV1PutNamespacedServiceProxyWithPath)

export default router;
