// Path: routes/V1Namespaces{namespace}Services{name}ProxyRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { connectCoreV1DeleteNamespacedServiceProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1GetNamespacedServiceProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1HeadNamespacedServiceProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1OptionsNamespacedServiceProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1PatchNamespacedServiceProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1PostNamespacedServiceProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1PutNamespacedServiceProxy } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/namespaces/:namespace/services/:name/proxy', connectCoreV1DeleteNamespacedServiceProxy)

router.get('/api/v1/namespaces/:namespace/services/:name/proxy', connectCoreV1GetNamespacedServiceProxy)

router.head('/api/v1/namespaces/:namespace/services/:name/proxy', connectCoreV1HeadNamespacedServiceProxy)

router.options('/api/v1/namespaces/:namespace/services/:name/proxy', connectCoreV1OptionsNamespacedServiceProxy)

router.patch('/api/v1/namespaces/:namespace/services/:name/proxy', connectCoreV1PatchNamespacedServiceProxy)

router.post('/api/v1/namespaces/:namespace/services/:name/proxy', connectCoreV1PostNamespacedServiceProxy)

router.put('/api/v1/namespaces/:namespace/services/:name/proxy', connectCoreV1PutNamespacedServiceProxy)

export default router;
