// Path: routes/V1Nodes{name}Proxy{path}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { connectCoreV1DeleteNodeProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1GetNodeProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1HeadNodeProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1OptionsNodeProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1PatchNodeProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1PostNodeProxyWithPath } from '../controllers/CoreV1Controller'
import { connectCoreV1PutNodeProxyWithPath } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/nodes/:name/proxy/:path', connectCoreV1DeleteNodeProxyWithPath)

router.get('/api/v1/nodes/:name/proxy/:path', connectCoreV1GetNodeProxyWithPath)

router.head('/api/v1/nodes/:name/proxy/:path', connectCoreV1HeadNodeProxyWithPath)

router.options('/api/v1/nodes/:name/proxy/:path', connectCoreV1OptionsNodeProxyWithPath)

router.patch('/api/v1/nodes/:name/proxy/:path', connectCoreV1PatchNodeProxyWithPath)

router.post('/api/v1/nodes/:name/proxy/:path', connectCoreV1PostNodeProxyWithPath)

router.put('/api/v1/nodes/:name/proxy/:path', connectCoreV1PutNodeProxyWithPath)

export default router;
