// Path: routes/V1Nodes{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1Node } from '../controllers/CoreV1Controller'
import { readCoreV1Node } from '../controllers/CoreV1Controller'
import { patchCoreV1Node } from '../controllers/CoreV1Controller'
import { replaceCoreV1Node } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/nodes/:name', deleteCoreV1Node)

router.get('/api/v1/nodes/:name', readCoreV1Node)

router.patch('/api/v1/nodes/:name', patchCoreV1Node)

router.put('/api/v1/nodes/:name', replaceCoreV1Node)

export default router;
