// Path: routes/V1NodesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { deleteCoreV1CollectionNode } from '../controllers/CoreV1Controller'
import { listCoreV1Node } from '../controllers/CoreV1Controller'
import { createCoreV1Node } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/nodes', deleteCoreV1CollectionNode)

router.get('/api/v1/nodes', listCoreV1Node)

router.post('/api/v1/nodes', createCoreV1Node)

export default router;
