// Path: routes/V1Nodes{name}ProxyRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { connectCoreV1DeleteNodeProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1GetNodeProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1HeadNodeProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1OptionsNodeProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1PatchNodeProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1PostNodeProxy } from '../controllers/CoreV1Controller'
import { connectCoreV1PutNodeProxy } from '../controllers/CoreV1Controller'

import {router} from './router';

router.delete('/api/v1/nodes/:name/proxy', connectCoreV1DeleteNodeProxy)

router.get('/api/v1/nodes/:name/proxy', connectCoreV1GetNodeProxy)

router.head('/api/v1/nodes/:name/proxy', connectCoreV1HeadNodeProxy)

router.options('/api/v1/nodes/:name/proxy', connectCoreV1OptionsNodeProxy)

router.patch('/api/v1/nodes/:name/proxy', connectCoreV1PatchNodeProxy)

router.post('/api/v1/nodes/:name/proxy', connectCoreV1PostNodeProxy)

router.put('/api/v1/nodes/:name/proxy', connectCoreV1PutNodeProxy)

export default router;
