// Path: routes/V1Nodes{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readCoreV1NodeStatus } from '../controllers/CoreV1Controller'
import { patchCoreV1NodeStatus } from '../controllers/CoreV1Controller'
import { replaceCoreV1NodeStatus } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/nodes/:name/status', readCoreV1NodeStatus)

router.patch('/api/v1/nodes/:name/status', patchCoreV1NodeStatus)

router.put('/api/v1/nodes/:name/status', replaceCoreV1NodeStatus)

export default router;
