// Path: routes/V1Persistentvolumes{name}StatusRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { readCoreV1PersistentVolumeStatus } from '../controllers/CoreV1Controller'
import { patchCoreV1PersistentVolumeStatus } from '../controllers/CoreV1Controller'
import { replaceCoreV1PersistentVolumeStatus } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/persistentvolumes/:name/status', readCoreV1PersistentVolumeStatus)

router.patch('/api/v1/persistentvolumes/:name/status', patchCoreV1PersistentVolumeStatus)

router.put('/api/v1/persistentvolumes/:name/status', replaceCoreV1PersistentVolumeStatus)

export default router;
