// Path: routes/V1PersistentvolumeclaimsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listCoreV1PersistentVolumeClaimForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/persistentvolumeclaims', listCoreV1PersistentVolumeClaimForAllNamespaces)

export default router;
