// Path: routes/V1PodsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listCoreV1PodForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/pods', listCoreV1PodForAllNamespaces)

export default router;
