// Path: routes/V1PodtemplatesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listCoreV1PodTemplateForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/podtemplates', listCoreV1PodTemplateForAllNamespaces)

export default router;
