// Path: routes/V1ResourcequotasRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listCoreV1ResourceQuotaForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/resourcequotas', listCoreV1ResourceQuotaForAllNamespaces)

export default router;
