// Path: routes/V1ServiceaccountsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listCoreV1ServiceAccountForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/serviceaccounts', listCoreV1ServiceAccountForAllNamespaces)

export default router;
