// Path: routes/V1SecretsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { listCoreV1SecretForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/secrets', listCoreV1SecretForAllNamespaces)

export default router;
