// Path: routes/V1WatchSecretsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1SecretListForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/secrets', watchCoreV1SecretListForAllNamespaces)

export default router;
