// Path: routes/V1WatchNamespaces{namespace}ReplicationcontrollersRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedReplicationControllerList } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/replicationcontrollers', watchCoreV1NamespacedReplicationControllerList)

export default router;
