// Path: routes/V1WatchPersistentvolumeclaimsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1PersistentVolumeClaimListForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/persistentvolumeclaims', watchCoreV1PersistentVolumeClaimListForAllNamespaces)

export default router;
