// Path: routes/V1WatchNamespaces{namespace}Secrets{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedSecret } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/secrets/:name', watchCoreV1NamespacedSecret)

export default router;
