// Path: routes/V1WatchEventsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1EventListForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/events', watchCoreV1EventListForAllNamespaces)

export default router;
