// Path: routes/V1WatchNamespaces{namespace}Services{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedService } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/services/:name', watchCoreV1NamespacedService)

export default router;
