// Path: routes/V1WatchResourcequotasRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1ResourceQuotaListForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/resourcequotas', watchCoreV1ResourceQuotaListForAllNamespaces)

export default router;
