// Path: routes/V1WatchPodsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1PodListForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/pods', watchCoreV1PodListForAllNamespaces)

export default router;
