// Path: routes/V1WatchNamespaces{namespace}Limitranges{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedLimitRange } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/limitranges/:name', watchCoreV1NamespacedLimitRange)

export default router;
