// Path: routes/V1WatchNamespaces{namespace}PodtemplatesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedPodTemplateList } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/podtemplates', watchCoreV1NamespacedPodTemplateList)

export default router;
