// Path: routes/V1WatchPersistentvolumesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1PersistentVolumeList } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/persistentvolumes', watchCoreV1PersistentVolumeList)

export default router;
