// Path: routes/V1WatchNamespaces{namespace}Podtemplates{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedPodTemplate } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/podtemplates/:name', watchCoreV1NamespacedPodTemplate)

export default router;
