// Path: routes/V1WatchReplicationcontrollersRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1ReplicationControllerListForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/replicationcontrollers', watchCoreV1ReplicationControllerListForAllNamespaces)

export default router;
