// Path: routes/V1WatchConfigmapsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1ConfigMapListForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/configmaps', watchCoreV1ConfigMapListForAllNamespaces)

export default router;
