// Path: routes/V1WatchNamespaces{namespace}Configmaps{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedConfigMap } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/configmaps/:name', watchCoreV1NamespacedConfigMap)

export default router;
