// Path: routes/V1WatchNamespaces{namespace}PersistentvolumeclaimsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedPersistentVolumeClaimList } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/persistentvolumeclaims', watchCoreV1NamespacedPersistentVolumeClaimList)

export default router;
