// Path: routes/V1WatchNamespaces{namespace}Pods{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedPod } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/pods/:name', watchCoreV1NamespacedPod)

export default router;
