// Path: routes/V1WatchNamespaces{namespace}Events{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedEvent } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/events/:name', watchCoreV1NamespacedEvent)

export default router;
