// Path: routes/V1WatchNamespaces{namespace}ConfigmapsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedConfigMapList } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/configmaps', watchCoreV1NamespacedConfigMapList)

export default router;
