// Path: routes/V1WatchNamespaces{namespace}Resourcequotas{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedResourceQuota } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/resourcequotas/:name', watchCoreV1NamespacedResourceQuota)

export default router;
