// Path: routes/V1WatchNodes{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1Node } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/nodes/:name', watchCoreV1Node)

export default router;
