// Path: routes/V1WatchPersistentvolumes{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1PersistentVolume } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/persistentvolumes/:name', watchCoreV1PersistentVolume)

export default router;
