// Path: routes/V1WatchNamespaces{namespace}EndpointsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedEndpointsList } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/endpoints', watchCoreV1NamespacedEndpointsList)

export default router;
