// Path: routes/V1WatchNamespaces{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1Namespace } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:name', watchCoreV1Namespace)

export default router;
