// Path: routes/V1WatchNamespaces{namespace}PodsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedPodList } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/pods', watchCoreV1NamespacedPodList)

export default router;
