// Path: routes/V1WatchNamespaces{namespace}Persistentvolumeclaims{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedPersistentVolumeClaim } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/persistentvolumeclaims/:name', watchCoreV1NamespacedPersistentVolumeClaim)

export default router;
