// Path: routes/V1WatchServicesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1ServiceListForAllNamespaces } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/services', watchCoreV1ServiceListForAllNamespaces)

export default router;
