// Path: routes/V1WatchNamespaces{namespace}Endpoints{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedEndpoints } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/endpoints/:name', watchCoreV1NamespacedEndpoints)

export default router;
