// Path: routes/V1WatchNamespaces{namespace}ServicesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedServiceList } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/services', watchCoreV1NamespacedServiceList)

export default router;
