// Path: routes/V1WatchNamespaces{namespace}Serviceaccounts{name}Route.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedServiceAccount } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/serviceaccounts/:name', watchCoreV1NamespacedServiceAccount)

export default router;
