// Path: routes/V1WatchNamespaces{namespace}LimitrangesRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedLimitRangeList } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/limitranges', watchCoreV1NamespacedLimitRangeList)

export default router;
