// Path: routes/V1WatchNamespaces{namespace}ResourcequotasRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedResourceQuotaList } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/resourcequotas', watchCoreV1NamespacedResourceQuotaList)

export default router;
