// Path: routes/V1WatchNamespaces{namespace}SecretsRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { watchCoreV1NamespacedSecretList } from '../controllers/CoreV1Controller'

import {router} from './router';

router.get('/api/v1/watch/namespaces/:namespace/secrets', watchCoreV1NamespacedSecretList)

export default router;
