// Path: routes/VersionRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getCodeVersion } from '../controllers/VersionController'

import {router} from './router';

router.get('/version/', getCodeVersion)

export default router;
