// Path: routes/.well-knownOpenid-configurationRoute.ts
// This file is auto-generated. Do not edit this file.
import { Router } from 'express';

import { getServiceAccountIssuerOpenIDConfiguration } from '../controllers/WellKnownController'

import {router} from './router';

router.get('/.well-known/openid-configuration/', getServiceAccountIssuerOpenIDConfiguration)

export default router;
